### ISSUE TITLE
'window' object

### ISSUE THREAD

**Issue by rightaway** [patriksimek/vm2#106]
If the script has something like `window.myfunc = function() {.....}` (to be invoked later as simply `myfunc()`), there's a ReferenceError saying `window is not defined`. It's valid JS isn't it? How can I get it to work?

**Comment by rightaway** [comment]
If it's valid JS without having to prepend that then I think it should work as is.

**Comment by n-riesco** [comment]
@rightaway `window` isn't defined in Node.js.  See https://nodejs.org/api/globals.html#globals_global
