### ISSUE TITLE
able to access __dirname and __filename of hosts

### ISSUE THREAD

**Issue by rajbrt** [patriksimek/vm2#109]
in vm2 sandbox code, able to access the hosts directory structure using the objects - "__dirname" and "__filename".

**Comment by Aetheryx** [comment]
I believe this might've been patched since:   
```
> const { VM } = require('vm2')
undefined
> const vm = new VM()
undefined
> vm.run('__dirname')
ReferenceError: __dirname is not defined
```

**Comment by teleclimber** [comment]
Using `NodeVM` you can read the host directory structure in`__dirname`.

It would be nice if VM2 allowed us to supply a mapping function for `__dirname`. It would take the host's `__dirname` of a sandboxed module as an input and output the `__dirname` that we want the sandboxed code to see.
