### ISSUE TITLE
require() does not default when specified "main" does not exist

### ISSUE THREAD

**Issue by ChrisMiskowiec** [patriksimek/vm2#110]
### Summary
When a package is required which lists an invalid main file, node.js falls back on index.js, but vm2 throws an error.

### Example
Given file structure:
```
node_modules
|- test_module
   |- index.js
   |- package.json
index.js
```

With `node_modules/test_module/package.json` containing:
```json
{
  "name": "test_module",
  "main": "foo.js"
}
```

And calling `require('test_module')`:
* Outside vm2 (plain node.js), loads `node_modules/test_module/index.js`.
* Inside vm2, throws an error "Cannot find module 'test_module'".

**Comment by thesayyn** [comment]
Any update on this ?
