### ISSUE TITLE
Infinite loop in Promise.then hangs whole process

### ISSUE THREAD

**Issue by GingerPlusPlus** [patriksimek/vm2#116]
This code disregards the timeout and hangs the process:

```js
'use strict'

const {VM} = require('vm2')

const vm = new VM({
	timeout: 5000,
})

console.log('Runs')

vm.run('Promise.resolve(42).then(() => {while(true) {}})') // hangs the process

setImmediate(console.log, 'Will never run')
```

And Promise can't be easily disabled: #74.

**Comment by awiebe** [comment]
Readme.md

> IMPORTANT: Timeout is not effective for NodeVM so it is not immune to while (true) {} or similar evil.

**Comment by GingerPlusPlus** [comment]
@awiebe except, I'm using `VM`, not `NodeVM`.

**Comment by patriksimek** [comment]
Unfortunately, this is another limitation of node's timeout feature - it doesn't work for asynchronous calls, even if they're running in the sandbox.
