### ISSUE TITLE
vm2 should use child_process.fork() to protect against while(true){}

### ISSUE THREAD

**Issue by awiebe** [patriksimek/vm2#118]
VM2 can't stop some infinite loops in process(https://github.com/patriksimek/vm2/issues/116), but it could run the process in a child, and if then if child hangs `subprocess.kill('SIGTERM')`, then if it still hangs `subprocess.kill('SIGKILL')`

e.g.
s.js
```
//...
.then(while(true){})
```

main.js
```
vm2.runFile(s.js,vm.js,timeout=5000).then(
//...
).error(
//...
)
```
internals.js
```
function runfile(f,vm,timeout)
{
options={"execArgv":f}
 var p = subprocess.fork(vm,...,options)
 //start timer
 //on timer pop, check if process running
 //if running send sigterm, wait 2 seconds
 //if running send sigkill
 //wait for killed
 //callback error
 //else callback then
}
```

vm.js
```
//setup your vm here
//read contents of file given by process.execArgv[0]
vm.run('script contents')
```

**Comment by blaskovicz** [comment]
https://github.com/blaskovicz/playground-nodejs/blob/master/index.js#L57
https://github.com/blaskovicz/playground-nodejs/blob/master/executor.js

**Comment by Yaty** [comment]
VM2 could use : 
- https://github.com/Yaty/workestrator
- https://github.com/rvagg/node-worker-farm
