### ISSUE TITLE
Custom modules support

### ISSUE THREAD

**Issue by hedin-hiervard** [patriksimek/vm2#121]
Can you explain how I can use custom modules in sandboxed code?
E.g. I have some main `script` code string variable and some `module` string variable.
I want to `require` my `module` from my `script`.

For some reasons I do not store my `module`'s source code on disk, only in memory. That's why the usual `require.external` approach doesn't work.

I see these options:
1. Use `require.mock`, however, I'm not sure how that deals with ES6 classes, which I want to export from `module`.
2. Use `require.context`. No documentation, no ideas how to use it.
3. Use `require.import`.  The documentation says:

> Array of modules to be loaded into NodeVM on start.

However, I can't figure out how can I represent my `module` as an array.

Any help? Is it possible at all?

**Comment by dolencd** [comment]
I'm running into the same issues. Help?

**Comment by beltsonata** [comment]
Can you post some code? I'm struggling to understand what you mean.

**Comment by Hedinhiervard** [comment]
Can you please elaborate more (maybe a config example with)?

**Comment by beltsonata** [comment]
```
var nodeVm = new vm.NodeVM({
        sandbox,
        wrapper: null,
        require: {
            external: true,
            builtin: ['events', 'util', 'assert'],
            context: 'sandbox'
        }
    });
```
This works for me. I can run a script on the VM that imports other modules that I have written. I can import the builtin modules into those modules too. Without seeing an example from you I can't really tell what you're doing.

**Comment by Hedinhiervard** [comment]
`external: true` allows importing all modules from `/node_modules`, isn't it? How can I restrict the VM to import only specific set of modules?

**Comment by AminHuang** [comment]
> `external: true` allows importing all modules from `node_modules`, isn't it? How can I restrict the VM to import only specific set of modules?
> 
> But my question was about another thing. How can I define a module in my own code and import it not from the disk, but from the memory?
> I want to build a system where users can upload 2 types of things: scripts and modules. Say a user uploads modules `M1` and `M2` and script `S` as text snippets. The text of `S` says:
> 
> ```
> import M1 from 'M1`
> import `M2` from 'M2'
> do_something_with_the_code();
> ```
> 
> So, I can dynamically compile and execute `S`'s code. It also can import builtin or external modules from `node_modules` (as you suggest). But how can I compile `M1`, and allow `import M1 from 'M1'` in VM?

hello, any suggestions of it?

**Comment by axtrur** [comment]
> `external: true` allows importing all modules from `node_modules`, isn't it? How can I restrict the VM to import only specific set of modules?
> 
> But my question was about another thing. How can I define a module in my own code and import it not from the disk, but from the memory?
> I want to build a system where users can upload 2 types of things: scripts and modules. Say a user uploads modules `M1` and `M2` and script `S` as text snippets. The text of `S` says:
> 
> ```
> import M1 from 'M1`
> import `M2` from 'M2'
> do_something_with_the_code();
> ```
> 
> So, I can dynamically compile and execute `S`'s code. It also can import builtin or external modules from `node_modules` (as you suggest). But how can I compile `M1`, and allow `import M1 from 'M1'` in VM?

i am searching the same question too? is there any solution?
