### ISSUE TITLE
NodeVM's require does not obey require.root

### ISSUE THREAD

**Issue by tylerjwatson** [patriksimek/vm2#123]
Hi guys,

I have a VM configured as follows: 

```
        this.VM = new NodeVM({
            console: 'redirect',
            require: {
                external: true,
                builtin: ['path'],
                context: 'sandbox',
                root: path.join(__dirname, "../modules"),
            },
            sandbox: this,
            timeout: 10000,
            wrapper: 'none',
        });
```

It turns out that `this.VM.require('./sub-module')` does not obey the path specified in `require.root`.  Is this a bug that requires a patch? Or am I confused about what `options.require.root` is for?  The documentation on it isn't clear.

Cheers,
T.

**Comment by tcf909** [comment]
You have to make sure to specify a path when you run code:
```
VM.run(<code here>, path.join(__dirname, 'sandbox.js'))
```

**Comment by tcf909** [comment]
Make sure to close the issue if it answered your question.

Otherwise let me know how else I can help!
