### ISSUE TITLE
global modification

### ISSUE THREAD

**Issue by tcf909** [patriksimek/vm2#126]
Hello,

How do I go about making sure the global provided context (sandbox) can not be modified:

VM.run('global.test = 123') //FAILES

I've tried to pre-freeze the object provide to sandbox and a bunch of other things that never seem to succeed. 

Suggestions?

Thanks.

**Comment by teleclimber** [comment]
Are you using `"use strict"` in your sandboxed script? It doesn't work without it. This works for me:

```js
const { NodeVM } = require( 'vm2' );
const vm2_instance = new NodeVM( {
	sandbox: {},
});
const preq = { body: { number: 5 } };
const script = `"use strict"; preq.body.number = 8;`;
vm2_instance.freeze( preq, 'preq' );
vm2_instance.run( script );
```

...in the sense that it throws an error. If you take `"use script"` out it doesn't throw and successfully mutates the object.

**Comment by teleclimber** [comment]
Also, if you are using `NodeVM` and you want the object to be frozen within required modules, make sure you set `require.context = 'sandbox'`
