### ISSUE TITLE
Is it possible to set a RAM limit for the VM?

### ISSUE THREAD

**Issue by metabench** [patriksimek/vm2#139]
I'm looking for a way to prevent users of the VM from using too much RAM, however much that is.

Is there a way to limit the amount of RAM that would be used? If not, can you see a pathway towards how that would get done?

Is it possible to tell how much RAM any sandbox node process is using?

**Comment by Yaty** [comment]
You can create a fork (then launch vm2 inside) and use some options in `execArgv` like : 
- max-executable-size
- max-old-space-size
- max-semi-space-size
- max-old-space-size
