### ISSUE TITLE
Documentation for sandbox using vm2

### ISSUE THREAD

**Issue by Mandar911** [patriksimek/vm2#14]
Is there a way to set up the sand box such that the parent script launching the child script can pass objects by reference to the child script so that it can call into the objects/methods? There is very thin documentation on sandbox for vm2 hence the question. I tried something like

var VM = require('vm2').VM;
var localvar = 'foo';
var localvar2 = 'bar';
function myobj(input)
{
    this.localvar= = input;
}

var options = {
timeout : 1000,
sandbox: {myobj, localvar2}
};

var vm = new VM(options);
vm.run('myobj(localvar2);');

This does not give me the desired result. Any pointers would be very much appreciated.

Also would be good to know why the sanbox offered by vm2 is better than the sandbox from node.js

**Comment by patriksimek** [comment]
Unfortunatly this is not supported because it allows attacker to access global object outside VM.

```
yourReferencedObject.hasOwnProperty.constructor("return (function(){return this})()")()
```

And your to you second question - vm in node.js doesn't care about security, it's just a vm.
