### ISSUE TITLE
how to pass variable?

### ISSUE THREAD

**Issue by ZhyMC** [patriksimek/vm2#140]
const {NodeVM}=require("vm2");
var vm=new NodeVM();

vm.run("var a=123");
//how to pass?it work well only when vm instanceof vm2.VM
vm.run("console.log('a')");

it is necessary for me ,thx

**Comment by eight04** [comment]
They are not in the same context. You can export the variable from the first module then pass it to the another:
```js
const {NodeVM}=require("vm2");
var vm=new NodeVM();

var moduleA = vm.run("exports.a=123");
var moduleB = vm.run("exports.logVar = value => console.log(value)");
moduleB.logVar(moduleA.a);
```
