### ISSUE TITLE
SyntaxError is hidden

### ISSUE THREAD

**Issue by Yaty** [patriksimek/vm2#142]
Hi,

```js
vm.run('toto truc')
```

It throws an error, but when printing the error I get an empy object `{}`.
But If I print the name property I'm getting the proper error name `SyntaxError`.

**Comment by jdalton** [comment]
I'm seeing this too. This is because of a mixup in 
https://github.com/patriksimek/vm2/blob/fe10656e56fe562ab6e6d2ae627fde7e7d524e0c/lib/contextify.js#L213-L235

because the error is not of the current context so the `instanceof` check fails and it's treated as a plain object.
