### ISSUE TITLE
Sandbox strict execution should be optional.

### ISSUE THREAD

**Issue by TheAifam5** [patriksimek/vm2#143]
Hey,
Actualy the code is written into a variable which defines `use 'strict'`. The TypeScript acutally generates it also, so would be nice to have a option to disable it.

**Comment by patriksimek** [comment]
Can you please explain the issue in detail? I'm not sure I understand what you mean. Thank you.

**Comment by TheAifam5** [comment]
In sandbox.js you have a variable ‘code’ which has a function with module, export .. parameters. There is ‘use strict’ which after remove my vode started to work, because could not use one of the js dependencies from nose_modules.
Nice option would be to make it as optional :)

**Comment by patriksimek** [comment]
The problem with that is that vm2 is not developed/tested against a code that doesn't have the `use strict` header. So adding that option would require a lot of work on ensuring it doesn't open a new security hole.

I was doing some tests with multiple `use strict` headers in the same file and it seems like it's working fine.
