### ISSUE TITLE
Cannot read property 'isTTY' of undefined (NodeVM)

### ISSUE THREAD

**Issue by TheAifam5** [patriksimek/vm2#145]
Hey,

I trying to run the nestjs in the VM.. I used webpack to compile into single file that I can run it directly in the VM.
The problem is, that `console` in VM does not contain stdin, stderr, stdout.

Workaround:
```js
require: {
  mock: {
    console,
  },
},
``` 

Regards,
TheAifam5

**Comment by vtulin** [comment]
Hi @TheAifam5 
Please tell me where to put this workaround, it looks like a webpack configuration, but what part of it?
Thank you.

**Comment by TheAifam5** [comment]
No its not a webpack config since webpack does not have „mock“ property - its s configuration of NodeVM.
The problem is, that the „isTTY“ is not there, also when I set the console to redirect or inherit.
The worksround is that how I fixed it for my problem which can be far from final solution since I give whole „console“ object to the VM.

**Comment by vtulin** [comment]
My problem was I didn't set `target: 'node'` in my webpack configuration, so stupid!
