### ISSUE TITLE
How to listen on `exit` event in a vm?

### ISSUE THREAD

**Issue by zhaoyi0113** [patriksimek/vm2#149]
I am using `NodeVM` to create a sandbox to run some code but how I can listen on the exit of my code. Is there any event in the `vm` emitted when the code is finished? 

Below is the full code. I want to return all the console output in my method. Since `vm.run` is running asynchronously, I don't know when it will return.

```
runNativeCode(db, code) {
    let log = "";
    const l = e => {
      log += e;
    };
    const vm = new NodeVM({
      timeout: 1000,
      sandbox: { db },
      console: "redirect"
    });
    vm.on("console.log", l);
    vm.run(code);
    return log;
  }
```

**Comment by momocow** [comment]
> Since vm.run is running asynchronously, I don't know when it will return.

It will return right immediately after all synchronous codes are evaluated without waiting for those asynchronous parts.
-------

You can make use of **callbacks** or **Promises** to trace life-time of codes.

The callback example is right there in the [`NodeVM` document](https://github.com/patriksimek/vm2#nodevm).

```js
// Async

let functionWithCallbackInSandbox = vm.run("module.exports = function(who, callback) { callback('hello '+ who); }");
functionWithCallbackInSandbox('world', (greeting) => {
    console.log(greeting);
});
```

And I also write an example using Promise.
```js
const { NodeVM } = require('vm2')
const vm = new NodeVM({
    sandbox: { setTimeout }
})

const code = `
module.exports = new Promise(function (resolve){
    setTimeout(function () {
        resolve('world')
    }, 1000)
})
`

vm.run(code)
    .then(who => {
        console.log('Hello %s!', who) // "Hello world!"
    })
```

**Comment by zhaoyi0113** [comment]
Thanks for the workaround solution.
