### ISSUE TITLE
Is it possible to reuse one context object, but pass new data to VM?

### ISSUE THREAD

**Issue by darahayes** [patriksimek/vm2#157]
Hi there, firstly thanks so much for this module it's a really great piece of work. I have a question that I was hoping you might be able to answer. I'm trying to see can I run some *potentially untrustworthy* code in `vm2` inside a server application as part of a request handler.

I'd like to be able to pass some incoming params/arguments to the code running inside, **without creating a new context for every request**. Initially, I was creating a new context with each request but I've found this to be particularly slow and I was wondering if there's any way around this.

Take the following example:

```js
const http = require('http')
const url = require('url')
const querystring = require('querystring')

const {VM, VMScript} = require('vm2')

const sandbox = {
  foo: 'bar'
}

const script = new VMScript(`foo`) // potentially dangerous code e.g. while(true){}

const vm = new VM({
  sandbox,
  timeout: 3000
})

const server = http.createServer((req, res) => {
  const query = querystring.parse(url.parse(req.url).query)

  res.end(vm.run(script))
})

server.listen(1337, '127.0.0.1', () => {
  console.log(`listening`);
})
```

Here I'm creating the vm + sandbox once and I'm wondering is there some way I can pass the `query` to the code inside the vm?

I was thinking I could do something like this:

```js

const someCode = `return query'`

const script = new VMScript(`
function someFunc(query) {
  ${someCode}
}

someFunc
`)

const someFunc = vm.run(script)

// this could be run inside the http handler
someFunc(query)

```

This works and it's good for performance, but it would not be protected against something like `while (true) {}.` I'm wondering do you know if there's any other way I can approach it?

Maybe it's not possible and this is a silly thing to ask. If so, feel free to close. Thanks!

**Comment by morfies** [comment]
I am using NodeVM and encountered same efficiency issue.
```js
          const t = Date.now();
          const vm = new NodeVM({
            console: 'inherit',
            sandbox: { params: workerData.params }, // query params per context
            require: {
              external: [ 'request-promise', 'lodash' ], 
              builtin: [],
              import: [ 'request-promise', 'lodash' ], // a bit faster if added
            },
          });

          const fnn = vm.run(workerData.code, workerData.filename);
          console.log('time cost by initializing vm:', Date.now() - t);
```
The avg time cost for the above bit of code is some 200+ms.   
All sorts of help on the optimization are welcomed. 
Big thank you.
