### ISSUE TITLE
Is it safe to assign a function to a sandbox before VM execution

### ISSUE THREAD

**Issue by liamray** [patriksimek/vm2#164]
Hello, I have a function which has an access to file system or something else.
I'm assigning that function to the sandbox and then executing untrusted code on the same sandbox.
Will it be safe ? I mean can untrusted code somehow access a "fs" module ?
Thank you !

```javascript
const VM = require('vm2').VM;
const fs = require('fs');

const sandbox = {
	someFunc: function () {
		// doing some stuff with [fs]...
		fs.readFileSync(...);
		return 0;
	}
};

const vm = new VM({
	sandbox: sandbox,
	timeout: 1000
});

// untrusted code does some stuff with someFunc()
const untrustedCode = 'someFunc();';

var result = vm.run(untrustedCode);
console.log(result);
```

**Comment by matthew-dean** [comment]
@liamray Isn't this testable? You should be able to try loading a file with the untrusted code and see if it fails?

**Comment by patriksimek** [comment]
Yes, the code you posted should be fine.
