### ISSUE TITLE
Debugging/Inspecting code running inside the VM

### ISSUE THREAD

**Issue by edopalmieri** [patriksimek/vm2#166]
Hi,
Apologies in advance if this has been asked/explained somewhere. I have searched through the documentation and posts on this space and could not find anything specific to this topic.

Is it possible to inspect or use a debugger on the code that is executed inside the VM? 
I would like to step through the code that is being executed inside the VM.

Thanks 
Edoardo.

**Comment by patriksimek** [comment]
Yes, you can debug sandboxed code. I've just updated the docs - https://github.com/patriksimek/vm2#debugging-a-sandboxed-code

**Comment by edopalmieri** [comment]
Hi,

That's great! Thanks for getting back to me. I just tested that and it works perfectly. 
A side question: if the VM is created and executed by a "host" piece of code, is it possible to do remote debugging to the VM without allowing the debugger to hit the host code? 
In other words, is it possible to somehow expose an ip/port for remote debugging inside the VM without it also allowing stepping through the host's code?

Cheers
Edoardo.

**Comment by patriksimek** [comment]
I'm 99% sure it's not possible. Maybe there's some secret switch to modify the behavior of the inspector, but I don't know about that.

**Comment by relu91** [comment]
Hi, sorry for bump this old thread. 
I'm trying to set breakpoints inside a script executed with vm2. I'm using the same snipped you posted above: 
```javascript
const {VM, VMScript} = require('.');
const fs = require('fs');
const file = `${__dirname}/sandbox.js`;

// By providing a file name as second argument you enable breakpoints
const script = new VMScript(fs.readFileSync(file), file);

new VM().run(script);
```
and this is the executed code:
```javascript
'use strict'

var tempObj = {
    field: "random"
}
console.log("Hello from the other side")
```
I've set one breakpoint in the last line of the executed script `console.log("Hello from the other side")`. Although, both vscode and chrome debuggers skip the breakpoint.  What am I missing? Should I always use the `debugger` keyword?
