### ISSUE TITLE
Continuous communication with the sandbox

### ISSUE THREAD

**Issue by myme** [patriksimek/vm2#17]
This is not an issue with vm2 itself, but a question about functionality (and perhaps to extend the docs with examples):

I have a scenario where I want to use a sandbox/jail to run long-lived untrusted code (similar to a Web Worker). The code should use an API to both listen to events from an outside system and respond by performing simple actions restricted by the API (aka Macros). Optimally, these snippets of code supplied by system administrators should only have access to this API and not much else. I don't mind the untrusted code hogging the event loop (e.g. `while (true) {}`) for the time being.

What are the options for having event-driven input and output between the sandbox context and the outside world? The API in question uses an underlaying Duplex stream of JSON data, which would be nice to proxy/relay into the sandbox. E.g. connecting (via methods/callbacks if necessary) a global and a contextified stream would most likely be sufficient. Would vm2 be able to support this in a way? Could you provide any thoughts/input on a minimal viable example for this?

**Comment by patriksimek** [comment]
Just released 3.0 with a lot of changes. It is now possible to use streams or external libraries inside the sandbox. There is no need for minimal example, just whitelist required modules and you're ready.

**Comment by lpgeiger** [comment]
@patriksimek Can you take a look at the question again? I'm not sure I understand your answer.

Is it possible for the sandbox to communicate the scope outside of the sandbox? For example using 'pipe' or  'ipc' message options like in node child_process

**Comment by patriksimek** [comment]
Yes, in v3, sandboxed script can communicate with anything you allow it to. You don't even need to use ipc, you can just exchange objects, functions, everything...

**Comment by lpgeiger** [comment]
@patriksimek Thanks. Though I can't see this in the docs. Can you give me a quick example?  
I'm trying to 1) start the sandbox, 2) run a function outside the sandbox and 3) return the result back to the sandbox which is waiting for the outer function.

**Comment by lpgeiger** [comment]
@patriksimek  Sorry but I must be missing something obvious. What's the best practice for 'exchanging objects' as you describe?

**Comment by patriksimek** [comment]
You can do it like this:

```javascript
const {VM} = require('.');
const vm = new VM({
	sandbox: {
		greet: (name) => `Hello ${name}!`
	}
});

console.log(vm.run(`greet('world')`));
```

**Comment by lpgeiger** [comment]
@patriksimek thanks for your attention on this. But I'm having trouble seeing how to implement "continuous communication" as in the title of this issue. For example how could I asynchronously communicate between two sandboxes?

**Comment by patriksimek** [comment]
What exactly continuous communication means for you? You can create a function in one sandbox and pass it to another sandbox so once you call the function from second sandbox, it will call a code in first sandbox.

**Comment by lpgeiger** [comment]
@patriksimek thanks for the response. I'm looking to have a sandbox call an asnyc function in another sandbox  and wait for the callback. I don't want to nest the second sandbox within the first one. I'm not sure what you mean: " so once you call the function from second sandbox, it will call a code in first sandbox." Can you provide a brief example? Thanks again

**Comment by patriksimek** [comment]
Example:
```javascript 
const {NodeVM} = require('vm2');

const vm1 = new NodeVM();
const fn = vm1.run(`module.exports = function(callback) { callback(null, 123) }`);

const vm2 = new NodeVM({
	sandbox: {
		fn
	}
});
vm2.run(`fn((err, res) => { console.log(res); })`);
```
