### ISSUE TITLE
How to use nodejs vm2 sandbox with inheritance mechanism?

### ISSUE THREAD

**Issue by msmumbucoglu** [patriksimek/vm2#189]
Hi friends,

I have a problem with vm2 sandbox. I mentioned about it at Stackoverflow.com.Could you please help me about it?

https://stackoverflow.com/questions/54649379/how-to-use-nodejs-vm2-sandbox-with-inheritance-mechanism

**Comment by patriksimek** [comment]
I believe the problem is mentioned in the known issues section in the readme:

> It is not possible to define class that extends proxied class.

**Comment by msmumbucoglu** [comment]
You are right my brother.I didn't pay attention to that.Well how can I overcome such a problem without using vm2. Can you make a comment please?

**Comment by patriksimek** [comment]
Look at the https://github.com/laverdet/isolated-vm
