### ISSUE TITLE
Timeout option work for vm but not for NodeVM

### ISSUE THREAD

**Issue by r3vsan** [patriksimek/vm2#195]
I found a different behavior between VM and NodeVM in timeout option operation

const {NodeVM, VM} = require('vm2')
const nodeVM = new NodeVM({
    timeout: 100,
    sandbox: {}
});
const vm = new VM({
    timeout: 100,
    sandbox: {}
});

vm.run('while(true) {}');  //This correctly throw exception
nodeVM.run('while(true) {}'); //This doesn't stop

**Comment by patriksimek** [comment]
That's right, it is mentioned in the docs:

> IMPORTANT: Timeout is not effective for NodeVM so it is not immune to while (true) {} or similar evil.
