### ISSUE TITLE
Strangely formatted output

### ISSUE THREAD

**Issue by stuffaboutpete** [patriksimek/vm2#196]
Can anyone explain this output?

```javascript
const { VM } = require('vm2');
console.log(new VM().run('[1, 2, 3]'));
```
```javascript
[ 1, 2, 3, '0': 1, '1': 2, '2': 3 ]
```

The equivalent `eval` looks like this (as you'd expect)...
```javascript
console.log(eval('[1, 2, 3]'));
```
```javascript
[ 1, 2, 3 ]
```

**Comment by stuffaboutpete** [comment]
Thanks @patriksimek, I'm still interested in an answer if someone has any insight.

**Comment by OleksiyRudenko** [comment]
@stuffaboutpete check #198 out.
One of workarounds is to downgrade Node to v8.10.0

**Comment by stuffaboutpete** [comment]
Thank you @OleksiyRudenko. I'll close as these are definitely duplicates.

Plus, that workaround is useful for me 👍
