### ISSUE TITLE
Is it possible to reuse one VM instance, but create new context when run()?

### ISSUE THREAD

**Issue by Pingze-github** [patriksimek/vm2#204]
I found `new VM()` is inefficient. Reuse a vm instance is good for performance.

But If I use `const` variable declarations in code, it will throw an error: `SyntaxError: Identifier 'xx' has already been declared`.

I found that the context inside of a vm instance is valid in all the vm's lifetime, so reuse a vm instance is unsafe.

It there anyway to use it efficient and safe? 

(May be this is a silly question, just close this)

**Comment by upsala** [comment]
Would this be a possible solution, to clean up the context and use const in scripts?

let vm = new VM();
vm.run("{"+script+"}");

Object.keys(vm._context).filter((key) => key !== 'VMError' && key !== 'Buffer').forEach((key) => {
  delete vm._context[key];
});

**Comment by patriksimek** [comment]
What about wrapping the code into a function? That way you can prevent polluting the global.

**Comment by Pingze-github** [comment]
> 
> 
> What about wrapping the code into a function? That way you can prevent polluting the global.

That's a good solution, I can run code safely without recreate VM. Thx!

**Comment by bugs181** [comment]
I recommend creating your script code as a class, which you can instantiate with the `new` keyword. Then for each "run", you have a new instance of that class. The alternative is to create a function as mentioned above by @patriksimek 

Here's a pseudo-code example:
```
const vm = new NodeVM({
  console: 'inherit',
})

const script = new VMScript(fs.readFileSync(moduleFile), moduleFile)
const someClass = vm.run(script)

// New instance code here
const someInstance = new someClass()
```
