### ISSUE TITLE
SyntaxError is not instanceOf Error and returns {} with console.log

### ISSUE THREAD

**Issue by digipigeon** [patriksimek/vm2#207]
I am quite sure that this is unexpected behavior, if nothing else it caused me about an hour of debugging to eventually distill it down to this.

The Syntax Error `await is only valid in async function` should be thrown and should be of type `SyntaxError`, which should be an instance of `Error`.

More importantly I would have expected `e` to print some more detailed information when I ran `console.log(e)` other than just `{}`

```
const {NodeVM} = require('vm2');
const vm = new NodeVM({wrapper: 'none'});
const util = require('util');

var script = `function test(){
	return await Promise.resolve();
}`;

try{
	console.log(vm.run(`${script}\nreturn test()`));
} catch (e) {
	console.error(e); // Output: {}
	console.log(e instanceof Error) // Output: false
	console.log(e.message); // Output: await is only valid in async function
}
```

**Comment by patriksimek** [comment]
Thanks! Fix released in 3.8.1.
