### ISSUE TITLE
question about running scripts in vm2

### ISSUE THREAD

**Issue by jjwyse** [patriksimek/vm2#21]
First off, thanks so much for all your work on `vm2`.  Huge fan!  Quick question:

My use case for executing these scripts requires that they are, as securely as possible, sandboxed.  I know there are always edge cases and potential vulnerabilities, but one of the major ones we have right now when using `vm2` is that it doesn't spawn a sub process to execute in.  This makes it pretty easy to right a script that just uses a *ton* of memory and causes our `node` process to die.  As I have looked at some of the other libraries out there (`sandcastle`, `sandbox`, `jailed`, etc.) they seem to spawn child process to protect against something like this.  I was just curious if you had attempted this at all with `vm2`?  I'm more than willing to fork the repository and implement myself, but before doing so, I was just curious if you had any insight.

Thanks again!

**Comment by patriksimek** [comment]
Thank you for your interest in improving this library. I was thinking about implementing this feature many times, but so far I have not found the time. I do not think this can be easily implemented while maintaining all the functionality of current design. I mean features such as object-sharing or bidirectional function calls. Anyway, I will be very glad if you try. Thank you for your effort.

**Comment by jjwyse** [comment]
Thanks for the quick response.  Hoping to have time to work on this and will let you know if I have any questions.

**Comment by patriksimek** [comment]
Closing this, feel free to reopen anytime you have any question.
