### ISSUE TITLE
Regex literal in sandbox vm2

### ISSUE THREAD

**Issue by rrichardson** [patriksimek/vm2#210]
When i run a bit of code specifying sandbox, e.g. 

```javascript

const ctx = { mylist: ['lala', 'blah'] };

const vm = new VM({
    timeout: 1000,
    sandbox: Object.assign({
        Array,
        RegExp,
    }, ctx)
});

 // this works as long as I pass RegExp into the sandbox
vm.run('mylist.filter(m => (m.match(new RegExp("la")))).length');  // returns 2

// this fails all the time
vm.run('mylist.filter(m => (m.match(/la/))).length');  // returns undefined
```

What do I need to do to leverage regex literals in vm code?   

I am trying to make a DSL of sorts by augmenting Array and String to allow the user to "select" data from a complex object.  At the high level, is there a better approach for this?

**Comment by patriksimek** [comment]
Why do you send `RegExp` and `Array` objects to the sandbox? That doesn't seem reasonable.

By the way, this works fine for me:

```javascript
const vm = new VM({
    timeout: 1000,
    sandbox: { mylist: ['lala', 'blah'] }
});

console.log(vm.run('mylist.filter(m => m.match(new RegExp("la"))).length'));  // returns 2
console.log(vm.run('mylist.filter(m => m.match(/la/)).length'));  // returns 2
```

**Comment by rrichardson** [comment]
@PatrickE94 - 
Huh.  I swear that exact test above was failing.. now it works.  No problems here, I guess.
