### ISSUE TITLE
VMError: Cannot find module since 3.8

### ISSUE THREAD

**Issue by frederik** [patriksimek/vm2#211]
Hi,

Thanks for the great work on this library!

I have noticed that npm libraries that specify a main key in package.json without the file ending (e.g. xmlbuilder specifies lib/index instead of lib/index.js) are not imported anymore. Reverting from 3.8 to 3.7 solves the issue. The following script (with only vm2 and xmlbuilder installed) reproduces the issue.

Best
Frederik

```
const { NodeVM } = require('vm2');

const vm = new NodeVM({
    require: {
        external: true
    }
});

// works
vm.run('require(\'xmlbuilder/lib/index\')', 'vm.js');
// VMError: Cannot find module 'xmlbuilder'
vm.run('require(\'xmlbuilder\')', 'vm.js');
```

**Comment by patriksimek** [comment]
Thanks! Fix released in 3.8.1.
