### ISSUE TITLE
Able to require external modules, when shouldn't be allowed

### ISSUE THREAD

**Issue by freeall** [patriksimek/vm2#221]
My VM is set up like this

``` javascript
  const vm = new NodeVM({
    require: {
      root: 'sandbox',
      external: {
        modules: ['request']
      }
    }
  })
```

What I want is to allow `request` to be required, but not any other module in `sandbox`. As an example `request` uses the `getpass` module, so it will be in the `sandbox/node_modules` folder.

This fails as expected:
``` javascript
require('getpass')
```

However, this won't:
``` javascript
require('./node_modules/getpass')
```

How can I set it up so that it is only allowed to require EXACTLY what I put in `require.external.modules` and nothing else? Is this possible?

**Comment by AashishUpadhyay** [comment]
@freeall what did you do to fix this?
