### ISSUE TITLE
Momentjs initialization from js date instance

### ISSUE THREAD

**Issue by pofider** [patriksimek/vm2#226]
Code to reproduce

```js
const { NodeVM } = require('vm2')
const moment = require('moment')

const code = `
console.log(moment(new Date(2016, 5, 5)).format('YYYY-MM-DD'));
`
new NodeVM({ sandbox: { moment } }).run(code)
```

It is expected to print `2016-06-05` however the current date is printed `2019-08-19`.
Thank you!

**Comment by artu-ole** [comment]
Can't reproduce on
node v10.16.0
-- vm2@3.8.3
-- moment@2.24.0

Which versions are you running?

**Comment by pofider** [comment]
Ups, I had a bit older vm2. It works on the latest.
Thank you for checking on this.
