### ISSUE TITLE
Use of Realms

### ISSUE THREAD

**Issue by gabegorelick** [patriksimek/vm2#227]
Since the [previous discussion about Isolates](https://github.com/patriksimek/vm2/issues/167) was enlightening, here is an interesting description of using Realms for sandboxing: https://www.figma.com/blog/how-we-built-the-figma-plugin-system/

ECMAScript proposal: https://github.com/tc39/proposal-realms
Implementation: https://github.com/Agoric/realms-shim

May be worth investigating.

**Comment by NotWearingPants** [comment]
Electron is planning to drop support for Node.js's vm module (which vm2 relies on) in future versions: https://github.com/electron/electron/pull/26087
(for now its usage prints a warning to the console).
So now might be a good time to re-open the issue and discuss moving forward.
