### ISSUE TITLE
Potential memory leak?

### ISSUE THREAD

**Issue by almercier** [patriksimek/vm2#232]
We are seeing large memory leaks when creating/running a vm in our project. It's jumping about 300 KB each time a VM is created/executed

Here's a simple express app that replicates it
```javascript
const express = require('express');
const { VM } = require('vm2');
const app = express();
const port = 3000;
let counter = 0;

app.get('/', (req, res) => {
    let vm = new VM();
    vm.run(`console.log("I'm inside a VM!");`);
    res.send(`Executed ${++counter} times`);
});

app.listen(port, () => console.log(`Example app listening on port ${port}!`));
```
I then start the server with `node --inspect index.js`, inspect the node server through chrome dev tools, snapshot memory, and then repeatedly go to `localhost:3000` (which will create and execute a vm each time) and take another snapshot. The results are below.

![Screen Shot 2019-09-09 at 1 22 07 PM](https://user-images.githubusercontent.com/30079507/64553291-19a53500-d307-11e9-9665-c1cd86561f71.png)

If I change it to use `NodeVM` instead, I still get leaks but it is significantly less. ~60 KB per VM created/run. Same repro above, results are below. There are leaky strings for each VM that is created/executed.

![Screen Shot 2019-09-09 at 1 44 42 PM](https://user-images.githubusercontent.com/30079507/64553964-72c19880-d308-11e9-861a-d71ede093f44.png)

(Note: In the first pic I had taken the comparison between two adjacent snapshots so I only see the leaks after one call, whereas in the second I had taken the comparison from the first to the last snapshot so I see leaks for each call.)

**Comment by XmiliaH** [comment]
I am wondering how the console object gets into the sandbox in your first example. I thought that console is not given to the sandbox by default.
For the second image I would say that if there is a leak, then it is in node.js since there is only one native reference left. There is no reference to the string from js any more. For the first image the question is why is the vm retained and not collected.
Maybe because console.log(x) oftern retains x until the console is cleard. This could retain the whole VM.
What I also would like to know, how does the snapshots display not jet garbage collected objects. Does it hide them or are they also displayed?

Did you try to create the VM's in an endless loop?

**Comment by almercier** [comment]
That's a good point in that `console` is available in the standard `VM`. I wonder if it's similar to `Math.<x>` which is also exposed without explicitly exposing it through the sandbox. IE: I could change the VM to run `console.log(Math.random())` without issue.

You are right, the one I showed in the picture may be retained by node.js as I didn't realize `vm.js` was internal node source code. However there's several other strings that are retained other than the one that I showed in the pic as well (some with retainers in contextify.js and sandbox.js), and they are strings that are not `"I'm inside a VM!"` or `console.log("I'm inside a VM!");` which I _would_ expect to "leak" based on how V8 caches string literals like you said.

Taking a snapshot forces a garbage collection first, so each snapshot contains anything that is truly being retained in memory and nothing that is going to be garbage collected. The comparison view does show what was freed between snapshots as well, but I only focused on what was _added and not freed_ as that would indicate a leak.

I could (and just did) create them in a loop which will provide the same results of jumping the used memory for each vm created/executed. Doing it through a request makes it easier to see what and how much is being leaked per iteration though.

**Comment by almercier** [comment]
Using the heap allocation timeline makes it much more obvious as you can see the spikes (blue bar is retained memory) for each call. Each call creates/executes 5 VM's, and I see retained memory usages increasing in sets of 5... Like 27kb strings, recompiled 34kb contextify.js per VM
```javascript
const express = require('express');
const { NodeVM, VM } = require('vm2');
express().listen(3000, () => console.log(`Example app listening on port 3000}!`));

global.executeVMs = function (useNodeVM) {
    for (let i = 0; i < 5; i++) {
        const vm = useNodeVM ? new NodeVM() : new VM();
        vm.run(`console.log(Math.random());`);
    }
};
```
![Screen Shot 2019-09-10 at 2 52 45 PM](https://user-images.githubusercontent.com/30079507/64641784-dfa56300-d3da-11e9-8a59-dc40b76c12ce.png)

**Comment by XmiliaH** [comment]
Its quite strage. I don't have a console object in the vm. Which version of node do you use?
As for the memory leak: VM2 does not store any values in global objects as far as I know, so the only idea I have is that console.log() retains the object passed which jn turn retains the whole vm.
Does it also happen if you don't use console.log jnside of the vm?

**Comment by almercier** [comment]
Node 8.12.0

I change my VM script to 
`vm.run(`let foo = 6 + 10; foo = foo / 8;`);`
And I still get it.

**Comment by almercier** [comment]
I get the same leaking behavior on node 10.12.0 (latest LTS). However on current 12.10.0, although I still get access to the console when using the VM module, it is leaking only the 60 KB instead of the 300 KB.

**Comment by Lizhooh** [comment]
The only way is to disable the console

```js 
const sandbox = {
    console: undefined,
};
```

**Comment by almercier** [comment]
@Lizhooh Sure, I can get around the console `nodevm` memory leak by just disabling console or using node 10.12.0 or later. But the smaller non-console related memory leaks appear to still exist.

**Comment by harpagon210** [comment]
@almercier the issue is actually in the "vm" module itself not in "vm2". Basically the "contexts" created via "vm.createContext()" are heavy objects and because of that the garbage collector doesn't necessary go and release the memory they're using until it reaches "max-old-space-size". When using node v13.7.0 I don't see memory leaks anymore.
