### ISSUE TITLE
Can no longer catch compile errors

### ISSUE THREAD

**Issue by almercier** [patriksimek/vm2#239]
The documentation has this little snippet of code that shows how to precompile and catch script compile errors before executing the script. (Changed "Math.random()" to "asdf(;" which should be a compilation error).
```javascript
try {
    var script = new VMScript("asdf(;").compile();
} catch (err) {
    console.error('Failed to compile script.', err);
}
```

However I never seem to hit the catch block in v3.8.4, whereas I do on v3.8.3.
If this functionality of catching compile errors before execution was intentionally removed with #234 , then the snippet in the documentation should be removed.

**Comment by XmiliaH** [comment]
Thanks for reporting. 
The function now compiles the code for VM again. If the code is later supplied to NodeVM then the code will be recompiled.
