### ISSUE TITLE
Trying to upgrade from using vm module

### ISSUE THREAD

**Issue by philiply** [patriksimek/vm2#247]
I'm currently using the vm module in my code but would like to use vm2 for better security. Had a few questions:

- Is there a difference in level of security between 2.x and 3.x versions of vm2? (We need to use an older version of node at the moment)
- What is the equivalent of `vm.createContext` and applying that context in `vm.runInContext` when using vm2?
- Is vm2 promise-based? or will I have to use a promise library around it?

Thanks!

**Comment by XmiliaH** [comment]
I don't konw a lot about 2.x but we have a wiki page about 2.x https://github.com/patriksimek/vm2/wiki/1.x-and-2.x-docs. So basically `vm.createContext` becomes `new VM()` and `vm.runInContext(ctx, code)` is `ctx.run(code)`. We don't use Promise anywhere, so I guess we are not promise-based. As for security, since I don't know 2.x I can't say anything about the security of it or which is better.

**Comment by philiply** [comment]
I was trying to pass in some functions into the sandbox parameter but they turn out differently when i checked the vm2 object. Like... when i check vm2.sandbox, they are exactly as i pass them, but when i look at the GLOBALs, I see the same key, but the function itself is altered. Do you have any idea why that would happen?

Thanks!

**Comment by XmiliaH** [comment]
We can't just give your function into the sandbox, else one could get the constructor of that function and escape it, so we use a wrapper around your method. However, I don't know how exactly this was done in 2.x.

**Comment by philiply** [comment]
is there documentation on this wrapper? How do I use it?

**Comment by XmiliaH** [comment]
If you pass a function via sandbox option into the sandbox, the function will be wrapped via:
```JS
wrappedFunction = function() {
  return yourFunction.apply(null, arguments);
};
```
original in coffeescript
```COFFEE
wrappedFunction = ->yourFunction arguments...
```

No properties on a function will be copied and this parameter seems to be not passed, however arguments are not wrapped, so care should be taken.
