### ISSUE TITLE
require.mock doesn't work for nested require

### ISSUE THREAD

**Issue by lwyj123** [patriksimek/vm2#251]
Here is the code
```Javascript
const vm = new NodeVM({
  require: {
    external: true,
    mock: {
      fs: {
        readFileSync: "Nice",
      }
    },
  },
});

vm.run(
  `
    var test = require('./test.js')
    console.log(test) // Output: [Function: readFile], which should be 'Nice'
`,
  'vm.js',
);
```

here is the ./test.js
```Javascript
module.exports = require("fs").readFile;
```

the output of `console.log(test)` is '[Function: readFile]', not 'Nice'.

Is this the correct result? because in a real situation I need to mock `fs`, but my user may use 'fs-extra'. and the `fs-extra` should use my mock not the actual `fs`

**Comment by XmiliaH** [comment]
Did you try setting require.context to "sandbox", if not require will load the modules in the host and then the module will use the host's require which cannot be intercepted.

**Comment by lwyj123** [comment]
It works, Thank you
