### ISSUE TITLE
running ecma6? or typescipt?

### ISSUE THREAD

**Issue by u007** [patriksimek/vm2#257]
hi, 

is it possible to run vmscript in that import other files that uses ecma6 code?

**Comment by XmiliaH** [comment]
Since ecma6 support is only in the experimental state, we did not yet implement ecma6 module support.

**Comment by u007** [comment]
nice, please update me when its up :) i think node12 onwards, ecma6 is built in

**Comment by gultar** [comment]
Actually, I was thinking about using a Typescript compiler library and having vm2 run the commonJS output. Do you think it's worthwhile?

**Comment by umang-malik** [comment]
Hi, is there any update on this?
