### ISSUE TITLE
Memory and CPU usage tracking of vm2

### ISSUE THREAD

**Issue by gultar** [patriksimek/vm2#258]
Implementing a way to track and restrict memory and cpu usage would be pretty neat. I'm using vm2 as a simple smart contract interpreter that is part of a homebrew blockchain and I'd like to create an additional security layer. Let me know what you think.

p.s. thanks for the amazing work!

**Comment by XmiliaH** [comment]
Since we use the vm module to create the sandbox, we can't restrict memory and cpu usage. Cpu usage can only be controlled by the timeout option, however this option has problems with async function.
