### ISSUE TITLE
does timeout work?

### ISSUE THREAD

**Issue by konsumer** [patriksimek/vm2#26]
When I run any code, timeout doesn't seemt to work. This just keeps running:

```js
const VM = require('vm2').VM
const vm = new VM({
  timeout: 1000,
  sandbox: {
    mineflayer: require('mineflayer')
  }
})

vm.run(`
var bot = mineflayer.createBot({
    host: "localhost",
    port: "25565",
    username: "Bot",
    password: null
})

bot.on('login', function() {
    bot.chat('hi everyone!')
})
`)
```

**Comment by patriksimek** [comment]
Timeout doesn't work in this case because you're execuing code that doesn't actually belong to the VM. It is only possible to handle timeout on synchronous functions executed inside VM.

**Comment by konsumer** [comment]
ahh, thanks!
