### ISSUE TITLE
can't modify sandboxed objects, only add properties

### ISSUE THREAD

**Issue by juliomsilva** [patriksimek/vm2#263]
Let's suppose my sandbox object has a property named 'one'.
I can add a nested property to it, but not overwrite the entire property with another object.

Please, there is a way to do it?

```js
const { NodeVM } = require("vm2");

const mySandbox = {
  one: {},
  anotherOne: {}
};

const vm = new NodeVM({
  sandbox: mySandbox
});

const code = `
  one = { two: 'two' }
  anotherOne.two = 'two'
`;

vm.run(code);

console.log(mySandbox); 
// { one: {}, anotherOne: { two: 'two' } }
```

Expected result: 
```js
{ one: { two: 'two' },  anotherOne: { two: 'two' } }
```

Thanks.

**Comment by XmiliaH** [comment]
This works as intended. The supplied sandbox object is shallow copied into the global object of the vm.
What you could do is something like:
```JS
const { NodeVM } = require("vm2");

const mySandbox = {
  one: {},
  anotherOne: {}
};

const vm = new NodeVM();

const init = 'return (' + function() {
  exports.setup = function(sandbox) {
    for (const k in sandbox) {
      Object.defineProperty(global, k, {
        get() { return sandbox[k]; },
        set(v) { sandbox[k] = v; },
        configurable: true,
        enumerable: true
      });
    }
  }
  return exports;
} + ')();';

vm.run(init).setup(mySandbox);

const code = `
  one = { two: 'two' }
  anotherOne.two = 'two'
`;

vm.run(code);

console.log(mySandbox); 
// { one: { two: 'two' }, anotherOne: { two: 'two' } }
```
This installs getters and setters on the global object for your sandbox object.

**Comment by juliomsilva** [comment]
resolved.

I really appreciate it.

**Comment by rafapetter** [comment]
@XmiliaH any idea how would that work inside an AWS lambda?

I'm getting the following error:

Error on VM:  ReferenceError: _defineProperty2 is not defined

**Comment by XmiliaH** [comment]
@rafapetter sorry, I don't know what AWS lambdas are. I also have no idea where you got that error.

**Comment by GabrielGonMorais** [comment]
@XmiliaH Can you help me with a similar case? I need to send a object inside sandbox with some setters
Example:
  
```
const mySandbox = {
  name: 'Gabriel',
  get age() { return 24 },
  set age(v) {throw 'you can't modify the age'},
  hobbie: 'play guitar'
};
```
I really need to show that property can't be modified
