### ISSUE TITLE
Program hangs on using while(true)

### ISSUE THREAD

**Issue by akhileshbhatia** [patriksimek/vm2#264]
The documentation suggests that this package is "immune" to `while(true)` which is not the case.

I am using version 3.8.4 and when I try to execute the `while(true)` loop, although the statements inside the loop are not executed, the program hangs indefinitely and has to be force stopped.

**Expected behavior:**
vm2 must throw some error and  stop the execution by itself (similar to what it does when it encounters the code like `process.exit()`.

**Comment by XmiliaH** [comment]
I can't resproduce with:
```JS
const {VM} = require('vm2');
new VM({timeout:1}).run(`
		while(1){}
	`);
```
This will stop execution after 1 ms.

**Comment by akhileshbhatia** [comment]
With the timeout thing, of course. But I can't use the timeout because the script that is executed might contain a legitimate loop or an operation which takes more than 1 ms (or whatever timeout) to complete execution

**Comment by XmiliaH** [comment]
This is considered immune to while(1) because of the timeout. Second, the suggestion is currently removed from the readme, since we have some problems with timeout and async functions.

**Comment by akhileshbhatia** [comment]
Reproducable using
```
const {NodeVM} = require('vm2');
const nodeVM = new NodeVM({
  timeout: 1
})

nodeVM.run('while(true) {}');
```

**Comment by XmiliaH** [comment]
From the readme:
**IMPORTANT**: Timeout is not effective for NodeVM so it is not immune to `while (true) {}` or similar evil.

Timeout is only available for the VM, not NodeVM.

**Comment by akhileshbhatia** [comment]
You are right. Thanks for that. Closing the ticket.
