### ISSUE TITLE
TypeError: 'getOwnPropertyDescriptor' on proxy: trap reported non-configurability for property '$response' which is either non-existent or configurable in the proxy target

### ISSUE THREAD

**Issue by jan-osch** [patriksimek/vm2#272]
Node:  v12.16.0
vm2: 3.9.0
aws-sdk: 2.642.0

```js
const { NodeVM } = require('vm2');

const vm = new NodeVM({
  console: 'inherit',
  require: {
    external: {
      modules: [
        'aws-sdk',
      ],
    },
  },
});

const code = `
  const AWS = require('aws-sdk');

  const s3 = new AWS.S3({
    apiVersion: '2006-03-01'
  });

  s3.listBuckets()
    .promise()
    .then(
      data => console.log(JSON.stringify(data))
    );
`;

vm.run(code, 'somescript.js');
```

I am getting an exception `TypeError: 'getOwnPropertyDescriptor' on proxy: trap reported non-configurability for property '$response' which is either non-existent or configurable in the proxy target`

I think the issue is that `aws-sdk` adds a new non-enumerable property `$response` to a Proxy 
https://github.com/aws/aws-sdk-js/blob/master/lib/request.js#L785. 

I found a mention about this error in the contextify implementation
https://github.com/patriksimek/vm2/blob/master/lib/contextify.js#L283 

The error itself is thrown in `fnc.apply` https://github.com/patriksimek/vm2/blob/master/lib/contextify.js#L179

**Comment by XmiliaH** [comment]
This is a problem with the proxies. To fix this we could copy requested non-configurable to the real proxy target, however then we can't share the proxy target like it is currently. Going to implement this fix and see how it performs.

**Comment by tqma113** [comment]
I ran into a similar problem

```
/node_modules/vm2/lib/main.js:1125
                        throw this._internal.Decontextify.value(e);
                        ^
TypeError [Error]: 'getOwnPropertyDescriptor' on proxy: trap reported non-configurable and writable for property 'prototype' which is non-configurable, non-writable in the proxy target
    at getOwnPropertyDescriptor (<anonymous>)
```
OS: MacOS
Node.js: 14.16.0
vm2@3.9.2
