### ISSUE TITLE
Invoke function error: TypeError: 'getOwnPropertyDescriptor' on proxy: trap reported non-configurability for property '__className__' which is either non-existent or configurable in the proxy target

### ISSUE THREAD

**Issue by liuxuewei** [patriksimek/vm2#273]
vm2: 3.9.0

![image](https://user-images.githubusercontent.com/1960603/77500085-f3a04600-6e8e-11ea-95dc-8eb7ee8ac4e2.png)

getting an exception TypeError: 'getOwnPropertyDescriptor' on proxy: trap reported non-configurability for property '__className__' which is either non-existent or configurable in the proxy target

**Comment by XmiliaH** [comment]
Duplicate of https://github.com/patriksimek/vm2/issues/272, just a different property.
