### ISSUE TITLE
The timeout option doesn't  work , when I run this code.

### ISSUE THREAD

**Issue by liuxuewei** [patriksimek/vm2#278]
![image](https://user-images.githubusercontent.com/1960603/78423280-e3ab1200-7697-11ea-8c1a-f3a21f86c460.png)

**Comment by liuxuewei** [comment]
async testVM() {
    const codes = ['return 123', 'return 456'];
    const runCodes = codes.map((code) => {
      return async function() {
        const vm = new VM({
          timeout: 1500,
        });
        const result = await vm.run(`(async function(){${code}})();`);
        console.log('code result', result);
      };
    });

    const vm = new VM({
      sandbox: { runCodes },
      timeout: 1500,
    });
    const code = `
      while(true){
        for (let i = 0; i < runCodes.length; i++) {
            const result = await runCodes[i]();
            console.log('runCodes', i, result);
        }
      }
    `;
    const result = await vm.run(`(async function(){${code}})();`);
    console.log('code result', result);
  }

**Comment by XmiliaH** [comment]
Thats correct, you can enable the fixAsync option via 
```JS
new VM({
  sandbox: { proc },
  timeout: 1500,
  fixAsync: true
});
```,
however this just throws when it finds an async function. When you want to use async, timeout does not work.

**Comment by liuxuewei** [comment]
> Thats correct, you can enable the fixAsync option via
> 
> ```js
> new VM({
>   sandbox: { proc },
>   timeout: 1500,
>   fixAsync: true
> });
> ```
> 
> however this just throws when it finds an async function. When you want to use async, timeout does not work.

can I stop it outside the vm2 ? Is there any  VM2 static function to stop Runing?

**Comment by XmiliaH** [comment]
No.

**Comment by haroldiedema** [comment]
You can easily implement a "workaround" that always works:

Add a global "ping" function to your VM script.
Let the 'host process' execute the "ping" function every x-amount of miliseconds. If the function does not respond within x-amount of milliseconds, the script is probably stuck in a while-loop.
