### ISSUE TITLE
False positives when using `fixAsync`

### ISSUE THREAD

**Issue by gabegorelick** [patriksimek/vm2#279]
The `fixAsync` option was added in https://github.com/patriksimek/vm2/pull/246. It is supposed to cause vm2 to throw an error whenever an async function is declared. However, it gives a lot of false positives. 

Some examples:

```js
const { VM } = require('vm2');
const vm = new VM({fixAsync: true});

// declaring a function named `async`
vm.run('function async () { return 1; }');

// declaring a variable named `async`
vm.run('const async = 1');

// calling a function named `async`
vm.run('async()');

// can't have strings with "async" in them
vm.run('"async"');
vm.run('"some text that contains async in it"');
```

All of the above throw `VMError: Async not available`.

**Comment by XmiliaH** [comment]
The problem is that I don't want to write a whole javascript parser just to filter for async functions.

**Comment by XmiliaH** [comment]
The best idea I came up with is to replace all occurences of `async` with an unused identifier. If the script has something like ``async function() {}`` it would become ``async_replacement function() {}`` and compiling it would be a syntax error, However there might be a js construct that defeats this check.

**Comment by XmiliaH** [comment]
Other idea is to replace all `async` uses with `a\u0073ync`. Using it as identifier is ok, however using it as keyword will result in `SyntaxError: Keyword must not contain escaped characters`. I think this is better than the last idea since it seems consisten.

**Comment by gabegorelick** [comment]
> The problem is that I don't want to write a whole javascript parser just to filter for async functions.

@XmiliaH Can an existing parser like https://github.com/acornjs/acorn be used?

Another idea: can https://nodejs.org/api/async_hooks.html be used to intercept the invocation of async functions?

**Comment by XmiliaH** [comment]
We don't want external dependencies, so acorn is out of the question. And async_hooks are still Experimental, will look into the if they are Stable.
