### ISSUE TITLE
Does this provide a secure wrapping for accessing folders ?

### ISSUE THREAD

**Issue by Abhay147** [patriksimek/vm2#280]
Lets say I have a folder X in the location `/Users/abhay/Documents/sandbox/X` 
Is there a way to allow access to files that are present only within the folder X, but no allow access outside it ?
the below file paths should be blocked
* `/etc/passwd`
* `/Users/abhay/Desktop/passwords.txt`
* `/Users/abhay/Documents/sandbox/X/../../../Desktop/passwords.txt`

But these files should be allowed
* `/Users/abhay/Documents/sandbox/X/project-config.json`
* `/Users/abhay/Documents/sandbox/X/repository/.gitignore`

**Comment by XmiliaH** [comment]
No, we do not provide this functionality. This can be implemented by the user of the VM and passed into the sandbox as function.
