### ISSUE TITLE
How to specify custom process.env within VM?

### ISSUE THREAD

**Issue by ivanvanderbyl** [patriksimek/vm2#282]
We have a use case where customers provide a script that we run within a VM. We'd like to make certain attributes of the host environment available to that script in a way that isn't completely custom ergonomically from running the same script with Node, which is to say `process.env.MYVAR` is ideal.

To support this we'd like to be able to override the default process.env within the VM, any plans to support this?

**Comment by phileba** [comment]
related to https://github.com/flood-io/element/pull/126

**Comment by XmiliaH** [comment]
How about
```JS
const vm = new NodeVM(...);
vm.sandbox.process.env = ...;
return vm;
```
for now?

**Comment by phileba** [comment]
> How about
> 
> ```js
> const vm = new NodeVM(...);
> vm.sandbox.process.env = ...;
> return vm;
> ```
> 
> for now?

@XmiliaH It seems that we cannot access the 'sandbox' directly from `vm`

**Comment by XmiliaH** [comment]
Then you are not using the newest version. This was added in v3.9.0.
Then you could do:
```JS
// Somewhere global or lazily
const setEnvScript = new VMScript("exports.setEnv=e=>process.env=e;return exports;");

// Every time a new vm is needed
const vm = new NodeVM(...);
vm.run(setEnvScript).setEnv(...);
return vm;
```
