### ISSUE TITLE
Script compiler not considering vm's compiler

### ISSUE THREAD

**Issue by khoshrou** [patriksimek/vm2#283]
Hi
I am using a function as compiler for NodeVM. seems new changes not considering it.
Seems you have added compiler to script. but it is not considering vm's compiler.
if you dont set a compiler for script. it seems always goes for javascript.
I sat scripts compiler to my function and now it works.

**Comment by XmiliaH** [comment]
The compiler for NodeVM is used if the run method is called with a string, if a VMScript is supplied the compiler function is not called, since the VMScript might already be compiled. Older versions wrongly called the compile function with the VMScript object. However, the function should only get string arguments.

**Comment by khoshrou** [comment]
so you say this is the correct behavior? 
I expected if the NodeVM has the compiler and  VMScript compiler is undefined then it should use NodeVm's compiler

**Comment by XmiliaH** [comment]
No, VMScript is a precompiled script. If it is passed to a NodeVM it is already compiled and so the NodeVM specific compiler is not used. If VMScript is not supplied by a compiler it defaults to javascript. If you wan't to compile a script with the NodeVM compiler, use a string. VMScript exisits to share scripts over multiple NodeVM's and if every one compiles the script with it's own compiler there would be no gain, so VMScript compiles the script once with the supplied compiler or as javascript.

**Comment by khoshrou** [comment]
I see, this sounds about right. 
This broke my code, but i did fix it
I couldn't find updates in docs
any way thanks for replies and awesome project

**Comment by XmiliaH** [comment]
You're welcome
