### ISSUE TITLE
running cpu sensitive code will block the main process

### ISSUE THREAD

**Issue by NeoyeElf** [patriksimek/vm2#291]
I find this in the README: `Runs untrusted code securely in a single process with your code side by side`

But when I run cpu sensitive code in NodeVM, e.g. 'fibonacci', it will block the main process. Is it expected?

**Comment by XmiliaH** [comment]
This is expected. From the README:
`IMPORTANT: Timeout is not effective for NodeVM so it is not immune to while (true) {} or similar evil.`

**Comment by NeoyeElf** [comment]
If I have to run cpu sensitive code using vm2, and don't want to block my main node process, any suggestions?

**Comment by XmiliaH** [comment]
That is not possible with VM2 & NodeVM, if you use VM there is a timeout option. But that is not available for NodeVM. If you want a NodeVM to run cpu intensice code side by side look for another project like isolate-vm or any other project spawning a new node process and running the script inside that.
