### ISSUE TITLE
disabling buffer access?

### ISSUE THREAD

**Issue by 8balloon** [patriksimek/vm2#299]
I would like to disable access to the `Buffer` object.

This is my current evaluation implementation for a totally locked-down eval mechanism:

```
const vm = new VM({
  timeout: 100,
  sandbox: {},
  eval: false,
  wasm: false,
  fixAsync: true,
})
const result = vm.run(`
  delete Buffer;
  (function() {
    return ${exprString}
  }.bind({}))()
`)
```

Is there a way `exprString` can access `Buffer` in this implementation? If so, is there a way around that?

This project is awesome by the way!! Great work @XmiliaH and @patriksimek

**Comment by XmiliaH** [comment]
This should work as long as you don't pass in a Buffer later on.

**Comment by 8balloon** [comment]
@XmiliaH Fantastic. Thank you!
