### ISSUE TITLE
timeout not working in Electron

### ISSUE THREAD

**Issue by Prinzhorn** [patriksimek/vm2#307]
Maybe someone knows what Electron is doing that makes this break? I wonder what else might be broken.

```js
const { VM } = require('vm2');

console.log('run');

new VM({ timeout: 1 }).run(`
    while(1){}
  `);
```

Node 12.16.2

```
 $ node index.js 
run
vm.js:131
      return super.runInContext(contextifiedObject, ...args);
                   ^

Error: Script execution timed out after 1ms
    at Script.runInContext (vm.js:131:20)
    at doWithTimeout (/vm2-timeout/node_modules/vm2/lib/main.js:467:17)
    at VM.run (/vm2-timeout/node_modules/vm2/lib/main.js:849:10)
    at Object.<anonymous> (/vm2-timeout/index.js:5:24)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  code: 'ERR_SCRIPT_EXECUTION_TIMEOUT'
}
```

Node 12.16.2 inside Electron 9.1.2 main process

```js
 $ npx electron index.js
run

// Keeps hanging forever
```

**Comment by Prinzhorn** [comment]
Still the same with Electron `10.1.5` and `11.0.0-beta.18`

**Comment by NotWearingPants** [comment]
This is a problem of Node.js's vm module with Electron (which vm2 uses), and has nothing to do with vm2.
To see this you can try running: `require('vm').runInNewContext('while (true);',{},{ timeout: 1 })`
I'm guessing this is a problem of node's event loop and chrome's event loop somehow not co-existing.

In fact, the Electron team noticed more than one problem with the vm module, and is now planning to disable it in future versions: https://github.com/electron/electron/pull/26087
While there might be a solution to your timeout problem, the real solution to the core problem is for vm2 to switch to an API which supports electron (#227) or implement everything alone while attempting to support electron (#167).

Could you describe why you need to use vm2 in Electron? Maybe enough use-cases will make the Electron team consider supporting this.

**Comment by NotWearingPants** [comment]
Btw Node.js's timeout implementation is [in this C++ code](https://github.com/nodejs/node/blob/f1ae7ea343020f608fdc1ca77d9cdfe2c093ac72/src/node_watchdog.cc#L41-L99) if anyone is interested in looking into this further.

Basically they create a new thread that waits until either the script finishes or the time runs out, and then kill the script somehow and close the thread.
I'm not sure which part is not working, but based on my understanding I'm guessing that the killing part is the problem and not the timer.

**Comment by Prinzhorn** [comment]
> In fact, the Electron team noticed more than one problem with the vm module, and is now planning to disable it in future versions: [electron/electron#26087](https://github.com/electron/electron/pull/26087)

This is (luckily) only about the renderer process. Running `electron index.js` is running in the main process, which in my opinion should support all Node.js internals as much as possible (they're already bending the rules by using BoringSSL instead of OpenSSL, but it's close enough).

> Could you describe why you need to use vm2 in Electron? Maybe enough use-cases will make the Electron team consider supporting this.

I'm working on an application for data processing. Users can extend the functionality with little scripts that transform data. I simply want to prevent them from shooting their own foot by setting a timeout (endless loops happen to the best of us) and by exposing a fixed set of modules to them. This is already happening in a worker thread spawned from the main process anyway. So it already prevents locking up the application. But the vm2 module does exactly what I need in that case.

I'll look into this some more, now that's it's clear that this is not an issue with vm2 itself.

**Comment by Prinzhorn** [comment]
https://github.com/electron/electron/issues/26560

**Comment by Prinzhorn** [comment]
> This is already happening in a worker thread spawned from the main process anyway.

Turns out in this scenario the timeout option does actually work. I should've been more careful testing this in isolation, wasn't expecting that to make a difference.

So if anyone finds this in the future (including a future version of myself) the timeout is currently broken in the Electron main process. But you shouldn't do anything in the main process anyway, so move all your vm stuff into a worker thread. The timeout works there and you're not blocking the main process.
