### ISSUE TITLE
Invalid read-only error inside new instances of ES6 classes defined from external read-only module

### ISSUE THREAD

**Issue by almercier** [patriksimek/vm2#312]
Using node-vm v3.9.2, node v12. We were not getting this behavior on 3.8.2 on node v8.

This code through the VM ~works as expected~(see comment below) without error
```javascript 
    const MyClass = require("./MyClass")
    class OuterClass{
        constructor () { }
    }
    const classInstance = new OuterClass();
    classInstance.innerInstance = new MyClass();
    classInstance.innerInstance.innerVar = 'foo';
```
But this, which effectively does the same thing but wrapped in the constructor of the locally defined class, gives me the error `'set' on proxy: trap returned falsish for property 'myVar'`
```javascript
    const MyClass = require("./MyClass")
    class OuterClass{
        constructor () {
            this.innerInstance = new MyClass();
            this.innerInstance.myVar= "foo";
        }
    }
    
    const classInstance = new OuterClass();
```

Any insight here?

**Comment by XmiliaH** [comment]
Sorry, I can't reeproduce the problem.
I used node v14.4.0 and commit 0bc2a4f6110d96f74e91315b790c0900ff43edab and tried with:
```JS
const vm = new VM.VM();
class MyClass {

}
vm.sandbox.MyClass = MyClass
const innerInstance = vm.run(`
class IntacctClient {
    constructor () {
        this.innerInstance = new MyClass();
        this.innerInstance.myVar= "foo";
    }
}

const client = new IntacctClient();
client.innerInstance
`);
console.log(innerInstance)
```
However, this seems to work.

**Comment by almercier** [comment]
Also works fine for me in that scenario, but requiring MyClass from a separate file does not

app.js (The file I am running with node)
```javascript
const {NodeVM} = require('vm2');
const path = require('path');

let vm = new NodeVM({
    require: {
        external: true,
        builtin: ["*"]
    }
});

vm.run(`
    const MyClass = require("./MyClass")
    class OuterClass{
        constructor () {
            this.innerInstance = new MyClass();
            this.innerInstance.myVar= "foo";
        }
    }
    
    const classInstance = new OuterClass();
`, path.join(__dirname, 'vm.js'));
```

MyClass.js
```javascript
class MyClass {}
module.exports = MyClass;
```

**Comment by XmiliaH** [comment]
So the reason is that the module MyClass.js is imported read only and objects created with new from the read only import will also be read only. Therefore the object created with new MyClass() is read only and so the assignment triggers the trap.

**Comment by almercier** [comment]
Yes that seems to be the case and resolving that would resolve my issue, but I am also curious why NOT wrapping the set inside an ES6 constructor (the first block of code) acts as read-only but does not throw the assignment trap error.

**Comment by XmiliaH** [comment]
The reason is https://tc39.es/ecma262/#sec-putvalue 6.b because the module is falsely loaded in non strict mode. However, the specs say https://tc39.es/ecma262/#sec-class-definitions `NOTE
A class definition is always strict mode code.`, so in the constructor strict mode is active and so the exception is thrown.
