### ISSUE TITLE
Set current working directory

### ISSUE THREAD

**Issue by fcnyp** [patriksimek/vm2#321]
Hope all is well. Looking to implement vm2 to address some security concerns.

Is there a method to change the current working directory? My untrusted code needs to have the ability to write files, however I need to programmatically control the directories that are written to.

Secondary, I need to restrict access to what files can be read/written (don't want someone reading /etc/passwd), other than using fs-lock I don't see a good option?

Thanks for feedback/direction!

**Comment by techar** [comment]
const sbfs = require("sandboxed-fs").bind(rootFolder);
....
                            mock: {fs: sbfs}

**Comment by XmiliaH** [comment]
This is out of the scope of this module.
