### ISSUE TITLE
Support TypeScript.

### ISSUE THREAD

**Issue by wintertime-inc** [patriksimek/vm2#323]
Hi there, any plans to support typescript?
Or maybe there is someone who uses the custom ts compiler in production, if so would you like to share?

**Comment by creepinson** [comment]
I would definitely like to see this, as I was trying to make a discord bot that executes typescript code but I couldn't find another typescript execution library that supports sandboxing and this is probably the best out there.

**Comment by y21** [comment]
Have you tried using the [TypeScript Compiler API](https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API)? It provides methods to transform TypeScript code into JavaScript code dynamically. I've used it before and it works great.
```js
const {VM} = require('vm2');
const ts = require('typescript');

const vm = new VM();

const res = ts.transpile(`
    let x: number = 3;
    x + 5;
`);

console.log(vm.run(res)); // 8
```

**Comment by creepinson** [comment]
Oh, for some reason I didn't think of using it in combination with vm2 lol. I will try this, thanks.

**Comment by XmiliaH** [comment]
It should also be possible to set `ts.transpile` as compiler.
```JS
const {VM} = require('vm2');
const ts = require('typescript');

const vm = new VM({compiler: ts.transpile});

console.log(vm.run(`
    let x: number = 3;
    x + 5;
`)); // 8
