### ISSUE TITLE
Block requiring Node Addons

### ISSUE THREAD

**Issue by techar** [patriksimek/vm2#327]
How do you block requiring the Node Addons? The Addons might as well be doing the same things like disallowed modules. I can't find any Node build arguments nor vm2 options.

My vm2 config is:
```
  new NodeVM({
    require: {
        external: true,
        builtin: [x,y,z],
        mock: {..},
        context: 'sandbox'
    }..
```

**Comment by XmiliaH** [comment]
You can either set option `require.external` to `false` to disable any external module or restrict modules to those in a specific path with the `require.root` option.
