### ISSUE TITLE
Possible Security Leak (Not)

### ISSUE THREAD

**Issue by philcockfield** [patriksimek/vm2#329]
@patriksimek 👋

I just wrote up details about what I think might be a hole (the main `process`/`process.env` leaking into sandboxed code.  Then paused, as if this really is a hole, I'd like to send you the details to get a fix in before publishing.

I've pinged an email into support at https://www.integromat.com/ as well trying to track you down.

Talk toon. 🌳

**Comment by techar** [comment]
process is not leaking.

It is a slimmed process that you see. Try diffing JSON.stringify(process.env) in host and sandboxed and you'll see a big diff.

It can be only leaking if you set sandbox: { process: process } so host one is passed to sandbox. 

If you don't want process then set sandbox: { process: null }

P.S. Stop sending emails bothering people unless you don't get an answer or try harder to find it yourself.

**Comment by philcockfield** [comment]
Required field `context: 'sandbox'`

```
const vm = new NodeVM({
      console: 'inherit',
      sandbox: {},
      require: {
        external: true,
        root: './',
        context: 'sandbox',
      },
    });
```
