### ISSUE TITLE
Restriction does not affect requiring in modules

### ISSUE THREAD

**Issue by pvomhoff** [patriksimek/vm2#33]
Hi,

first of all. Thank you for v3! Its really really amazing.

Unfortunately I found another bug.
It is possible to require restricted native modules in required modules.

For example:
Lets say the code in the vm want to get a file from the filesystem.

The way via fs works fine:
```javascript
var NodeVM = require('vm2').NodeVM;

var options = {
    console: 'inherit',
    require: {
        external: true,
        builtin: [],
        root: "./"
    },
    nesting: true
    
};

var vm = new NodeVM(options);
var functionInSandbox = vm.run("module.exports = function(){  var fs = require('fs');  fs.readFile('./node_modules/vm2/index.js', function (err, data) { console.log(err, ''); }); }", __filename);
vm.call(functionInSandbox);
```
It throws me an error which is correct.

But lets use one random fs module from npmjs:
```javascript
var NodeVM = require('vm2').NodeVM;

var options = {
    console: 'inherit',
    require: {
        external: true,
        builtin: [],
        root: "./"
    },
    nesting: true
    
};

var vm = new NodeVM(options);
var functionInSandbox = vm.run("module.exports = function(){  var read = require('read-file');  read('./node_modules/vm2/index.js', function (err, data) { console.log(err, data.toString('utf-8')); }); }", __filename);
vm.call(functionInSandbox);
```
This time I can read the complete file.

It looks like that the require method in the modules are not restricted.

**Comment by patriksimek** [comment]
To restrict access for required modules, you must set `require.context` option to `sandbox`. With this option, modules are loaded and compiled inside sandbox so they're sharing the same security sandbox. That means thay can only use whitelisted modules.

**Comment by pvomhoff** [comment]
Ahh ups I missed that.
Now it works like a charm.

Thanks a lot for your help and the great new version :)
