### ISSUE TITLE
Uncaught TypeError: 'set' on proxy: trap returned falsish for property 'x'

### ISSUE THREAD

**Issue by techar** [patriksimek/vm2#330]
When requiring `(context: 'sandbox')` googleapis (and some other modules) there is an exception 
`Uncaught TypeError: 'set' on proxy: trap returned falsish for property 'write'`
This can be fixed like described in [Issue 101](https://github.com/patriksimek/vm2/issues/101#issuecomment-386837451
) but it hasn't been merged. Is this secure ???

**Comment by AminHuang** [comment]
maybe can use `require.mock`, but I don't know if it's secure enough

**Comment by rbayliss** [comment]
I was seeing a similar issue when passing a mock for the `events` module to work around #102.  #346 resolves the issue for me.
