### ISSUE TITLE
Update sandbox value

### ISSUE THREAD

**Issue by gnujeremie** [patriksimek/vm2#335]
Hi,

Not a bug but a question. Is there a way to update the sandbox (I have several variables passed to the sandbox) without having to execute `new VM({ sandbox: myVariables })` ?

I am looping over several values, and would like to instanciate once the vm object, and then update the sandbox before each `run()`.  Is it possible ?

Thanks,
Jérémie

**Comment by gnujeremie** [comment]
I ended using `vm.freeze()`, and it seems to work as I expected. Would love to have someone else's input to be sure I'm doing right. :)

Thanks,
Jérémie

**Comment by XmiliaH** [comment]
There are different ways:
```JS
const vm = new VM();
vm.sandbox.myVariable = something;
vm.setGlobal("myVariable", something);
vm.setGlobals({myVariable: something});
vm.freeze(something, "myVariable");
vm.protect(something, "myVariable");
```
Note that that `vm.freeze` makes the object read only. `vm.protect` will disallow setting values on the object to functions. Note that these two functions only do the protection if the object was never accessible in the sandbox before.
