### ISSUE TITLE
Redirect console log

### ISSUE THREAD

**Issue by vaulstein** [patriksimek/vm2#336]
Is it possible to redirect console.log to the vm.run output?

Example:

```javascript
const code = 'console.log("Hello World!")';

try {
    var script = new VMScript(code).compile();
 } catch (err) {
    console.error('Failed to compile script.', err);
 }

const vm = new VM({
     timeout: 1000,
     console: 'redirect'
 });
 const data = vm.run(code, 'main.js');
```

Can I get the console.log output in data if code contains console.log? 
Also if my code has more than 1 function, it gives output as `undefined`

**Comment by y21** [comment]
AFAIK, `options.console` is only available in NodeVM. `VM` only includes JavaScript builtins, and `console.log()` writing to stdout is something implemented by Node.js. So if you want to use it, you're either going to have to use NodeVM or just add the host console object to sandbox globals. 
```diff
-    console: 'redirect'
+    sandbox: { console }
```
The latter might be unsafe for untrusted user code looking at the [implementation of NodeVM's `options.console`](https://github.com/patriksimek/vm2/blob/a81e12ce3950f41cbc3199bc03dbb7cd9bcb0121/lib/sandbox.js#L606:L666) as NodeVM also decontextifies parameters.
If you don't want to redirect it to stdout and instead want the `console.log`s as strings, you could pass a custom `console` object that simply adds parameters to a string. You can also use `util.inspect` to inspect objects to emulate Node.js' `console.log`. 
<details>
<summary>Example</summary>
.

```js 
const { VM } = require('vm2');
const { inspect } = require('util');

const code = `
    console.log(1);
    console.log({a: 3, b: [1,2]});
`;

let logs = '';

function _log(type, args) {
    logs += `[${type}] ${args.map((x) => inspect(x)).join(' ')}\n`;
}

const vm = new VM({
    timeout: 1000,
    sandbox: {
        console: {
            log: (...args) => _log('LOG', args),
            warn: (...args) => _log('WARN', args),
            // ...            
        }
    }
});

vm.run(code, 'main.js');

console.log(logs);
// Logs:
// [LOG] 1
// [LOG] { a: 3, b: [ 1, 2 ] }
```
</details>

Keep in mind that util.inspect invokes functions with a `util.inspect.custom` symbol if it exists. There's a `customInspect` option that disables this.
