### ISSUE TITLE
Unable to use the variable name 'module' in NodeVM

### ISSUE THREAD

**Issue by HaywoodSolutions** [patriksimek/vm2#339]
When using the NodeVM class

`new NodeVM({
  console: 'off',
  sandbox: {},
  require: {
    context: 'sandbox',
    external: ['@abc/abc'],
    builtin: [],
    root: "./",
    mock: {
      '@abc/abc': admin
    }
  },
  wrapper: 'none',
  nesting: false
});`

And running the below code

`const admin = require('@stupidassistant/admin');
const module = "a";`,

It shows the error `SyntaxError: Identifier 'module' has already been declared.`

What can I do to get round this to run "any" code, i.e. using module as a varable name, while still being able to import '@abc/abc'.

Thanks :)

**Comment by hirayaku** [comment]
I believe `module` is a pre-defined global variable in every js file. You can't even run this code outside the NodeVM.

If you must, try `var module`, but why?

**Comment by XmiliaH** [comment]
`NodeVM` wraps the module code with
```JS
(function (exports, require, module, __filename, __dirname) { <code>
})
```
as node does. Therefore `module` is already defined in the module.
