### ISSUE TITLE
Could access restricted modules in loaded modules

### ISSUE THREAD

**Issue by hirayaku** [patriksimek/vm2#340]
I am trying to run a script in NodeVM without access to IO-related modules (like 'fs'). The script will load a local js file for some helper functions. It turns out I could circumvent NodeVM by loading the restricted modules in the local js file. Example below.

helper.js
```js
exports.fs = require('fs');
```
run.js
```js
const {NodeVM} = require('vm2');

const vm = new NodeVM({
    require: {
        root: __dirname,
        external: [...] // I might want to load some external modules like uuid in VM
    }
});
// the following could run without error
vm.run(`console.log(require('./helper').fs.readdirSync('./'));`, __filename);
```

Is there a way to block this behavior?

**Comment by XmiliaH** [comment]
Unless you set `require.context` to `sandbox` this is expected.
