### ISSUE TITLE
Support require.resolve from a hybrid package

### ISSUE THREAD

**Issue by jiqiang90** [patriksimek/vm2#352]
Now when using `require.resolve` from a hybrid package (esm and cjs) will throw errors indicating it is a esm module which is not support.

We need the `resolve` method to be improved, which can automatically detect the supported format, and resolve from the correct path.

**Comment by XmiliaH** [comment]
The following code works for me:

```JS
const { NodeVM } = require('vm2');

const vm = new NodeVM({
    require: {
        external: true
    },
    sourceExtensions: ['cjs', 'js']
});
console.log(vm.run(`
    const {numberToHex} = require('@polkadot/util/number/toHex');
    exports.hex = 'hex:'+numberToHex(322);
`, __filename));
```

The important bit is to prioritize `cjs` over `js` files in `sourceExtensions`.
