### ISSUE TITLE
vm2 debugging breakpoints with source maps?

### ISSUE THREAD

**Issue by joetex** [patriksimek/vm2#353]
Hello,

I attempted to load a webpack'd bundle.js file through both VM and NodeVM, but I cannot make debugging breakpoints work against the original code that was bundled.  I am able to use breakpoints in the bundle.js file, but not the original code files. 

I attempted these webpack devtools:
eval-source-map, inline-source-map, source-map

VSCode shows there is a linkage between the bundle.js and my original files via the sourcemap.

Any help would be appreciated, its late and I give up trying all kind of variations.

**Comment by joetex** [comment]
I slept on it.  Drank some coffee.  Then solved this problem.  

My webpack `output` needed this:
```
devtoolModuleFilenameTemplate: 'file:///[absolute-resource-path]'
```

Now I can happily debug complex code.  Cheers.

**Comment by PaTiToMaSteR** [comment]
hey @joetex can you post the solution? Actually even with files I'm struggling to know how to debug with vm2

**Comment by joetex** [comment]
> hey @joetex can you post the solution? Actually even with files I'm struggling to know how to debug with vm2

This is how I compile/run the vm script:
```javascript
const cwd = process.cwd();
let filepath = path.join(cwd, './builds/server/server.bundle.dev.js');
let jsData = fs.readFileSync(filepath, 'utf8');
let script = new VMScript(jsData, filepath).compile();

const vm = new VM({
    console: false,
    wasm: false,
    eval: true,
    fixAsync: false
});
vm.run(script);
```

This is my webpack to build the vm script:
```javascript
const path = require('path');
var ENTRY_FILE = path.resolve(__dirname, '../../../game-server/index.js');
var OUTPUT_PATH = path.resolve(__dirname, '../../../builds/server');
module.exports = {
    entry: ENTRY_FILE,
    output: {
        path: OUTPUT_PATH,
        filename: 'server.bundle.dev.js',
        devtoolModuleFilenameTemplate: 'file:///[absolute-resource-path]'
    },
    devtool: "source-map",
    mode: 'development',
    optimization: { usedExports: true, },
};
```

The main script that runs this vm script must be run in debug mode.  You should be able to breakpoint the vm script after that.  

If you want to fix the stack trace errors to point to the actual lines, you can look at my code in the link below.  I use a try/catch block for `vm.run`, and in the catch I parse the stack trace and read the `.map` sourcemap file to output lines that are clickable.  
https://github.com/acosgames/acosgames/blob/main/simulator/server/worker.js#L492

**Comment by PaTiToMaSteR** [comment]
🤔👏🏻 I’ll try that! thanks a lot for the detailed response!💪🏻
