### ISSUE TITLE
Performance impact from data obtained from VM

### ISSUE THREAD

**Issue by krishadvani** [patriksimek/vm2#354]
I have a VM script is written, which is returning a JSONArray of about 1000 elements. When I return this data from the VM and load it into a variable, there seems to no problem. However, when I attempt to execute an operation on the data obtained from the VM, for instance, a JSON.stringification, the CPU utilization jumps up, and so does the time for executing. 

The difference in time is 30x. 

Please note: It is not the VM execution time is not considered, it's the subsequent operation that causes the high CPU utilization and increased time of execution. Yet still, the difference is huge. 

```JS
const https = require('https');
const {VM} = require('vm2');

https.get('https://at2-staging.quickwork.co/workflow/api/public/apps', (resp) => {
  let data = '';

  A chunk of data has been received.
  resp.on('data', (chunk) => {
    data += chunk;
  });

  resp.on('end', () => {
      

    // Normal Data Stringification directly on the node services
    var startTime = new Date().getTime();
    JSON.stringify(data);
    var endTime = new Date().getTime();
    console.log(endTime - startTime);

    // Data Stringification after VM execution
    const vm = new VM({timeout: 1000, sandbox: {}});
    let sameData = vm.run("var data =" + data + "; data;")

    var startTime = new Date().getTime();
    JSON.stringify(sameData);
    var endTime = new Date().getTime();
    console.log(endTime - startTime);
  });

}).on("error", (err) => {
  console.log("Error: " + err.message);
});

```

The output of the above code is:

```
2
58
```

Am I doing something wrong?

**Comment by XmiliaH** [comment]
We use JavaScript proxies to isolate VM objects from hosts ones. In this case all the operations `JSON.stringify` does need to go though the proxy. Furthermore, v8 does not optimize for the proxies resulting in additional poor performance.

You could try to get the `JSON.stringify` object from the sandbox before running unsafe code and then calling it with the data. This would reduce the amount of time spent going though the proxy.

```JS
const vm = new VM({timeout: 1000});
const sandboxJSONStringify = vm.run("JSON.stringify");
let sameData = vm.run("var data =" + data + "; data;");
sandboxJSONStringify(sameData);
```

Note that the `sandboxJSONStringify` need to be from the same VM.

For the used timeout here, I want to note here that both implementations have the problem that the timeout can be circumvented by either `async` or a custom looping JSON handler.

**Comment by krishadvani** [comment]
Thanks a lot @XmiliaH, it did work. I now understand the reason behind it. Thanks a lot for your time!
