### ISSUE TITLE
Require class and extends it, the method from child will be lost.

### ISSUE THREAD

**Issue by canguser** [patriksimek/vm2#356]
### As the title says, here are the test cases:

> `./test1.js`
```javascript
exports.A = class {
};
```
> `./test2.js`
```javascript
const { NodeVM } = require('vm2');

function run(script, options) {
  return NodeVM.code(script, './vm.js', options);
}

run(`
const {A} = require("./test1");

class B extends A {
    // a method declared
    async execute() {
        return undefined;
    }
}
const a = new B();
console.log(a.execute); // will print `undefined`, but expect `[Function: execute] [AsyncFunction]`
`, {
  require: {
    external: true
  }
});
```

**Comment by XmiliaH** [comment]
This is a known issue and falls under
 - It is not possible to define class that extends proxied class.
 
 If you would check with `instanceof` the problem is visible:
 ```JS
console.log(a instanceof B); // false
console.log(a instanceof A); // true
```

**Comment by canguser** [comment]
I don't think what you said is a reason not to fix it. This problem will lead to the failure to reference other libraries normally, and it is contrary to the semantics of JavaScript

**Comment by XmiliaH** [comment]
While I would like to fix this issue it is not that trivial. The problem is that `A` is read only and therefore the instances created from it are too. If one extends this class it is hard to ensure that the resulting instance is read only and this might result in fields written in the constructor of `B` to throw since the underlying `this` object is read only. Furthermore this bring a security risk since the extended class could override internal functions of the super class that should not be overwritten.

**Comment by canguser** [comment]
Well, can you tell me what kind of risks it will bring to make instances readable

**Comment by XmiliaH** [comment]
For example:

*test1.js*
```JS
exports.A = class {
    constructor() {
        this._functions = [x=>x*x, x=>x, x=>x+x]
        this._key = 1;
    }
    setKey(key) {
        if(typeof(key) === "number") {
            this._key = key;
        }
    }
    call(x) {
        return this._functions[this._key](x);
    }
};
```
*test.js*
```JS
const { NodeVM } = require('./index');

const vm = new NodeVM({
    require: {
        external: true
    }
});
console.log(vm.run(`
    const {A} = require('./test1');
    const a = new A();
    a._functions = x=>x;
    a._key = "constructor";
    exports.p = a.call("return process")();
`, __filename));
 ```
 
 would return the process if `A` would be writable.

**Comment by canguser** [comment]
OK, I see what you mean, but I think it's caused by external dependencies, such as the following code: 

`test1.js`
```javascript
exports.A = class {
  constructor() {
    this._functions = x=>x
    this._key = 'constructor';
  }
  setKey(key) {
    if(typeof(key) === "number") {
      this._key = key;
    }
  }
  call(x) {
    return this._functions[this._key](x);
  }
};
```
`test2.js`
```javascript
const { NodeVM } = require('vm2');

const vm = new NodeVM({
  require: {
    external: true
  }
});
console.log(vm.run(`
    const {A} = require('./test1');
    const a = new A();
    console.log(a.call('return process')());
`, __filename));
```
In this way, the process can also be obtained, so a better solution is to limit the reference of external dependencies and only refer to trusted dependencies. Besides, it's better to chain the external dependencies and run its in sandbox

**Comment by XmiliaH** [comment]
If you would load the dependencies in the sandbox the problem with extending will be gone. However, for eternal dependencies that are loaded outside of the sandbox this is not the case. While the dependencies should be trusted the one proposed my me will likely look trusted to many while the modified version trivially returns the process object which should not be shared.

**Comment by canguser** [comment]
Is it possible to load external dependencies into independent sandboxes through `require.resolve`, If external dependencies also rely on other dependencies, they can be chained into different sandboxes, and these sandboxes share a unified option as limitation.

**Comment by XmiliaH** [comment]
The VM Proxy is restricting the extension. Since the Proxy is also used to communicate between different sandboxes this is not possible.
