### ISSUE TITLE
memory reference of array of object in sandbox

### ISSUE THREAD

**Issue by b1g2h3** [patriksimek/vm2#359]
I create a sandbox for untrusted code where I initialize 1m records. When other functions run in the field after that, it is extremely slow. Is it possible destroy memory reference?
```
          // 1m records
           virtualMachine.sandbox.records = records
          // fnc is precompiled function untrusted code
            records = JSON.parse(virtualMachine.run(`JSON.stringify(fnc(records))`))
            virtualMachine.sandbox.records.length = 0
```
I solved this with JSON.stringify, but is possible solved this somehow diffrent??

**Comment by XmiliaH** [comment]
I guess the slowdown comes from the proxies used to wrap the sandbox objects. There no way to remove them or make them faster.
