### ISSUE TITLE
React SSR with JSX transform causes error in development mode

### ISSUE THREAD

**Issue by pwolaq** [patriksimek/vm2#362]
Hello! I have a problem with running React SSR in vm2.

The following code:
```javascript
const { VM } = require('vm2');

new VM({
    sandbox: {
        require
    }
}).run(`
    const jsxs = require("react/jsx-runtime").jsxs;
    const renderToStaticMarkup = require("react-dom/server").renderToStaticMarkup;
    const fn = props => jsxs("span", {
        children: ["Hello ", props.name, "!"]
    });
    renderToStaticMarkup(jsxs(fn, { name: "world" }))
`);
```
results in TypeError:

> TypeError: 'ownKeys' on proxy: trap result did not include '0'
>     at Function.freeze (<anonymous>)

However, if I replace jsxs with standard `React.createElement` everything seems fine. The issue only occurs in development mode.

This is the line that is breaking the code: https://github.com/facebook/react/blob/edfe50510b4129295cbe49f05d7b94bbfc48da5b/packages/react/src/ReactElementValidator.js#L362

**Comment by XmiliaH** [comment]
This is fixed in 3.9.6
