### ISSUE TITLE
Getting returned value

### ISSUE THREAD

**Issue by tonkku107** [patriksimek/vm2#37]
I run a NodeVM
`var result = vm.run('1+1')` (just an example)
but result becomes just an empty object.
how can I get the returned value, like I would from doing `var result = eval('1+1')`?

**Comment by junedev** [comment]
I think it says in the documentation that "run" only passes the stuff that is exported via module.exports to the outside, so this works fine:
`var result = vm.run('module.exports = 1+1');`

**Comment by tonkku107** [comment]
that brings trouble, because if I want to make a for loop for example in that code, `SyntaxError: Unexpected token for` would happen :cry:

**Comment by junedev** [comment]
Just write the "run" script as you would write a module. If you want to run some code wrap it in a function and export this function. For your for loop this would look like this:
```
const {NodeVM} = require('vm2');
let vm = new NodeVM();
let myLoop = vm.run('module.exports = function(){ for(let i=0; i<5; i++) { console.log(i); } };');
myLoop();
```
