### ISSUE TITLE
Cannot declare a function with the "root" name.

### ISSUE THREAD

**Issue by dlckdduq1107** [patriksimek/vm2#380]
I am using vm2.
I wanted to declare a function called root inside vm2.run.
But I got an error saying root is not a function.
This error was resolved through the immediate execution function, but I think it is an issue and leave a note.
thank you.
With @xvezda @longnh214 @winters0727

**Comment by XmiliaH** [comment]
This is since we define it here: https://github.com/patriksimek/vm2/blob/3a21c36222bc6b8e7948068c9152f9d691fd52de/lib/contextify.js#L39

**Comment by dlckdduq1107** [comment]
While using vm2, I accidentally created a function named root, 
but an error occurred and I was embarrassed. It was a good experience.
Thanks for the reply :)

**Comment by dlckdduq1107** [comment]
While using vm2, I accidentally created a function named root,
but an error occurred and I was embarrassed. It was a good experience.
Thanks for the reply :)
