### ISSUE TITLE
What's the proper way to set timeout?

### ISSUE THREAD

**Issue by xencodes** [patriksimek/vm2#384]
I've stored user's code in a database. It's basically a Telegram bot codes.
I run user's code with the webhook I get from Telegram. I want to make sure user's code executes within limited time. How can I do that in vm2? or do I need to do something else?

**Comment by XmiliaH** [comment]
Create the vm with
```JS
const vm = new VM({
    timeout: 1000, // 1s
    fixAsync: true // Disable async
});
```
