### ISSUE TITLE
how to extend a base module?

### ISSUE THREAD

**Issue by NoahHahm** [patriksimek/vm2#385]
extend the RegExp module that is vulnerable to ReDOS attacks. In the current VM2, prototype extension for basic modules is not possible.
Is there any way?
even if I extend RegExp in sandbox context,
It doesn't work in the literal way.
since it basically acts as a proxy and set is blocked, there is no way to block the code below.

[https://gist.github.com/watson/7682ee718b9cf4aa2a5a605a3fb4a552#file-redos-js](url)

**Comment by XmiliaH** [comment]
One can use timeouts:
```JS
const vm = new VM({timeout: 1000});
vm.run(`
var r = /([a-z]+)+$/
var s = 'aaaaaaaaaaaaaaaaaaaaaaaaaaaa!'
r.test(s)
`);

console.log("Finished");
```

**Comment by NoahHahm** [comment]
@XmiliaH If you're inside a function, and call it later, you have a problem.

**Comment by XmiliaH** [comment]
But you could just write:
```JS
while(1){}
```
why remove regex?
If you want to disable regexp you could remove everything from `RegExp.prototype`.

**Comment by NoahHahm** [comment]
I want to safely write RegExp.prototype as node-re2 .

**Comment by XmiliaH** [comment]
It might be possible to replace the functions from `RegExp.prototype`.
Not texted:
```JS
RegExp.prototype.exec = function exec(str) {
	const re = new RE2(this);
	return re.exec(str);
};
```
This should be done for all functions. Either replace them or remove them.

**Comment by NoahHahm** [comment]
Thanks no problem!
