### ISSUE TITLE
Access to all names in the sandboxed code

### ISSUE THREAD

**Issue by zenbones** [patriksimek/vm2#386]
Using Nodes plain vanilla vm, I can define sandbox and pass that into the run in a new context and sandbox will contain all the names in the sandboxed script, such that if that code is..

```JS
let foo = "hello"

function bar() {

    return foo;
}
```

...and we...

```JS
let sandbox = {};
vm.runInNewContext(<code>, sandbox);
```

...then...

`sandbox['foo']` will be 'hello'
I can `sandbox['foo'] = 'goodbye';`
and `sandbox['bar']()` would then be 'foodbye'

But if a substitute in vm2 and...

```JS
vm = new NodeVM({sandbox: sandbox})
vm.run(<code>)
```

...then sandbox is baren and empty. Is there any way to replicate the original vm's behavior nd get access to the namespace of the code being sandboxed?

**Comment by XmiliaH** [comment]
You can do
```JS
const vm = new VM();
vm.run('something="Global";');

console.log(vm.sandbox.something);
```

**Comment by zenbones** [comment]
Yes, I can. Need *vm*.sandbox, which makes perfect sense. Sorry, I do not normally work in javascript.

Thank you!
