### ISSUE TITLE
Getting functions in global namespace

### ISSUE THREAD

**Issue by zenbones** [patriksimek/vm2#387]
I asked the question about manipulating the state of sandboxed code in vm2, noting that defining sandbox externally, sandbox = {}, and passing that into the original node provided vm will give you access to the names in the sandboxed code. You pointed out that defining vm = new NodeVM() and using vm.sandbox does much the same thing, which is correct. The difference is that in plain vanilla vm the sandboxed code...

function foo() {return "Hello World"}

...will place the function foo into the namespace such that sandbox.foo() will return "Hello World". But in vm2 vm.sandbox.foo() tells you that foo is unknown. Is there a way to replicate the behavior from the original vm as I need access to both the globally defined variables and the *functions* in the sandboxed code?

**Comment by XmiliaH** [comment]
The replacement for vm is VM not NodeVM. In NodeVM the code will be wrapped in a function. This will cause foo to be declared in this function and not the global.

**Comment by zenbones** [comment]
But NodeVM has additional properties that are useful. Is there a way to get the pointer to the wrapper function such foo can be retrieved? And thank you for indulging my ignorance and responding so quickly.

**Comment by XmiliaH** [comment]
It is comparable to a Node module an so the functions need to be exported.

```JS
const vm = new NodeVM();
result = vm.run(`
function foo() {return "Sandbox";}
exports.foo = foo;
`);
console.log(result.foo());
```

**Comment by zenbones** [comment]
That is not overly burdensome, given the usage scenario, and also makes perfect sense. Thank you again!
