### ISSUE TITLE
Does #277 resolve the bypass sandbox protection mechanism?

### ISSUE THREAD

**Issue by adaniels-parabol** [patriksimek/vm2#389]
@patriksimek @orta @XmiliaH https://github.com/patriksimek/vm2/pull/277 was merged in on April 29, 2020. Does #277 resolve the bypass sandbox protection mechanism?

This resolves a security finding I'm trying to get past.

**Comment by XmiliaH** [comment]
The linked PR #277 was merged in 29 Apr 2020. However, I am currently working on an update. 3.9.6 will be released when that is finished.

**Comment by adaniels-parabol** [comment]
@XmiliaH disregard, I looked at the wrong commit date. Would you say that #277 resolves "vm2 Package for Node.js contains an unspecified flaw in the NodeVM sandbox.js script which may allow an attacker to bypass sandbox protection mechanisms. No further details have been provided."

**Comment by XmiliaH** [comment]
Yes it fixed https://github.com/patriksimek/vm2/issues/276 and https://github.com/patriksimek/vm2/issues/285 as can be seen from the added test case in the PR.

**Comment by adaniels-parabol** [comment]
Awesome! Thank you. I will close this ticket now.
