### ISSUE TITLE
node6 requirement

### ISSUE THREAD

**Issue by allain** [patriksimek/vm2#39]
Tried using this in an AWS lambda and got a warning about requiring node 6. Thinking that should be made explicit in the README.

**Comment by patriksimek** [comment]
It is, right at the top of the docs with bold notice.

![snimek obrazovky 2016-08-04 v 16 14 15](https://cloud.githubusercontent.com/assets/1000058/17405119/8ce175f8-5a5e-11e6-9d44-b821c1ed7341.png)

**Comment by allain** [comment]
Doh! Guess I got too excited at what the project does to bother reading
accurately.

**Comment by miguelperez** [comment]
Is there a version of this project that could run against v4 of node, maybe with less features?

I am currently reading about the security implications of using the node.vm module directly instead of using something similar to vm2 because lambda currently does not support node v6.

**Comment by patriksimek** [comment]
This module requires [Proxies](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Proxy) in order to work and this is unfortunately no supported on v4.

**Comment by miguelperez** [comment]
And other question what can you tell me about security issues of using the node module `vm`?

Thanks a lot for your time,
