### ISSUE TITLE
Question: How to find out end of execution? Graceful Exit

### ISSUE THREAD

**Issue by skaneprime** [patriksimek/vm2#390]
My app launches Server and after that run vm who also launches it's own server 
After it finishes How to find out or capture the finish? I can't interfere or know the containment of code But I know that it launches server, listens, and die

```js

const app = express()
const httpServer = app.listen(() => console.log("Listening port", httpServer.address()))
const vm = new NodeVM()
vm.run(`"launching a server here"`)

```
There's no way I found that would allow us to watch or observe the vm
Is there a way to listen something similar like `process.on("exit", ...)` ? 

This would work but Works only when main server is not launched.
```js
const EventEmitterFromSandbox = new EventEmitter()
... 
const vm = new NodeVM({ sandbox: { EventEmitterFromSandbox } }) 
...
vm.run("process.on(\"exit\", code => EventEmitterFromSandbox.emit(\"exit\", code)")
vm.run(`"launching a server here"`, "pathToFile")

EventEmitterFromSandbox.on("exit", code => {
     // Graceful Exit
     httpServer.close()
})
```

**Comment by XmiliaH** [comment]
There is no way we can detect when a sandbox is finished. Therefore, we cannot provide an event for this case.

**Comment by skaneprime** [comment]
@XmiliaH  Found my way with using clusters. A workaround 
example
```js
const cluster = require('cluster');

if(cluster.isWorker) {
    cluster.worker?.process.channel?.unref(); // We have to do this so it won't stuck in IPC waiting for messages. But downside is we can't send or get messages. It's a price to pay. Fair price...
    const vm = new NodeVM({ ... })
    vm.run(`server code`)
}

if(cluster.isPrimary) {
    await Serve();
    const worker = cluster.fork({ path });
    
    worker.on("exit", async code => {
        await Close();
        console.log("vm process finished with code", code)
    })
}
```
But It may side effects with some code If you don't know how clusters work
