### ISSUE TITLE
TypeError [Error]: 'set' on proxy: trap returned falsish for property; NPM module best practices question

### ISSUE THREAD

**Issue by lukwallace** [patriksimek/vm2#392]
vm2 version: `3.9.5`
node version: `14.17.1`

Error: 
```
...node_modules/vm2/lib/main.js:1237
			throw this._internal.Decontextify.value(e);
			^
TypeError [Error]: 'set' on proxy: trap returned falsish for property...
```

Hi there, I believe I've encountered an issue identical to the one described in https://github.com/patriksimek/vm2/issues/312, but my use case differed enough that I figured it might be best to ask for best practices / guidance from the vm2 team.

I'm working with an npm library that exports a singleton class instance with the expectation that you can write to it and have it alter the behavior of library methods. To elaborate, the expected usage might look something like this:

```
// configuration as a singleton; fooMethods as a namespace for methods relating to foo
const { configuration, fooMethods } = require('my-library');

// alter configuration setting
configuration.fooSetting = 456;

// make a foo call (that might utilize new settings)
fooMethods.doSomething();
```
The problem is that the line: `configuration.fooSetting = 456;` acts on a singleton class instance that seems to be read-only according to the discussion here (https://github.com/patriksimek/vm2/issues/312). I understand that this might not be common (or possibly best) practice for npm libraries, but this does seem to function in normal environments.

Is this one of those even-though-you-can-doesn't-mean-you-should-type situations? Or are there plans to support this sort of thing in the works? Since I'm a contributor to the library in question, I'm able make alterations to the codebase to avoid allowing for modifications of library persisted state in this way, but I'd love to hear rhetoric/guidance on what's best practice (or what incorrect assumptions I shouldn't have made) before coming to a decision.

Thanks!

**Comment by XmiliaH** [comment]
While it might make sense to add an option for this to the NodeVM require options there is a workaround.
It is possible to do:
```JS
const mylib = require('my-library');
const {NodeVM, VMScript} = require('vm2');

const exposeScript = new VMScript('return (exports.expose = a => a);')

function runMyCode(code) {
	const vm = new NodeVM({
		require: {
			external: true
		}
	});

	const expose = vm.run(exposeScript).expose;
	expose(mylib);

	vm.run(code, 'vm.js');
}

runMyCode('require("my-library").test = 123;');
// mylib should now have property 'test' with value 123
console.log(mylib);
```

However, this allows the script to modify properties on the module. The `expose` function needs to be called before the module is loaded in the sandbox.

**Comment by lukwallace** [comment]
Thanks for your input!

Just to give you an idea of what we ended up doing -- the workaround you described seems very useful when we know a priori the name of the library we have in mind; unfortunately, the our use case tries to be agnostic to the modules being used in the code ran by the vm. We _could_ augment our usage to try and account for this dynamic-ness by leveraging the workaround you've provided, but I feel the extra layer of chicanery we'd have to add may not be worthwhile at the moment. Ultimately, we decided the singleton-class-instance-configuration style of code maybe wasn't our brightest idea, and are currently working on alternatives.

Regarding this github issue itself and the existing behavior with the read-only class instances, please let me know what's suitable for you. In the case the vm2 team intends to resolve this at some point and it's helpful to you, I'm happy to leave this issue up as a means of tracking. Otherwise, please feel free to close this (possibly as dup of #312?).
