### ISSUE TITLE
Inheriting global namespace in required code

### ISSUE THREAD

**Issue by zenbones** [patriksimek/vm2#393]
Starting a NodeVM with {sandbox: {foo: "bar"}} provides a defined 'foo' in the global namespace in the vm initiated code. However, in code obtained via require() in the vm initiated code, 'foo' is not defined. I suspect this is a side effect of the proxy wrapping of required modules. Is there any way to have the global namespace passed into the required code, which seems like the natural expectation?

**Comment by XmiliaH** [comment]
This would be the same as creating a sandbox with `{sandbox: {foo: "bar", somemodule: require('smemodule')}}`. The required module knows nothing about the sandbox. It is possible with option `require.context='sandbox'` to load modules in the sandbox. These modules then have access to the sandbox global namespace.
