### ISSUE TITLE
Only disallow require of specific local files

### ISSUE THREAD

**Issue by DaAwesomeP** [patriksimek/vm2#4]
I want to allow requiring of all modules/files except specific files in an array. I am trying to block access to APIs in a secure system.

Also, does this block requires of requires (i.e. the module originally required requires a file that requires restricted module).

Lastly, can someone run a child process that runs the CLI version of my app? I want to allow access to CLI programs (child processes) except for mine.

**Comment by patriksimek** [comment]
1) Blacklisting a script files is not implemented.
2) Yes, it should.
3) I do not understand the intention. Could you please describe it in detail?

**Comment by DaAwesomeP** [comment]
I want to make an extension system for my app. I don't want the extension to be able to wreck complete havoc.  Ideally there would be levels of granted control. However, I would need a method of doing that.

**Comment by DaAwesomeP** [comment]
Accidentally hit close.

**Comment by DaAwesomeP** [comment]
@patriksimek is this possible or will I just have to take risks?

**Comment by patriksimek** [comment]
Once you allow access to `child_process`, the script can execute whatever it wants. I would not recomend you to allow this.
