### ISSUE TITLE
Breaking change VMScript.compile in >3.9.5

### ISSUE THREAD

**Issue by agtraveso** [patriksimek/vm2#409]
Hi! I notice that `VMScript.compile` change its behaviour on new versions: `3.9.6`, `3.9.7`, `3.9.8`. I'm not sure to consider this a bug or a breaking change.

This code (not pretty but a valid javascript code) was working in old versions:
```
const { VMScript } = require("vm2");

const code = `
class TrickyClass {
  hooray = () => {
    return 'hooray'
  }
}`;
new VMScript(code, { filename: "index.js" }).compile();
```

In newer versions it throws an exception `SyntaxError: Unexpected token (3:9)` because it doesn't like the `hooray` definition.

I've done a little research and this behaviour is related with the new `lib/transformer` function which uses some new `acorn` dependencies.

Other side-effects of this `lib/transformer` is that we have lost error 'verbosity': the error doesn't show the filename anymore and the stracktrace is kind of poor:

* before
```
new VMScript("cosnt foo = 'bar'", { filename: "index.js" }).compile();

> index.js:1
cosnt foo = 'bar'
      ^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:102:7)
    at Object.<anonymous> (vm-tests/vm.js:15:1)
```

* now:

```
new VMScript("cosnt foo = 'bar'", { filename: "index.js" }).compile();

> SyntaxError: Unexpected token (1:6)
    at Parser.pp$4.raise (vm-tests/node_modules/acorn/dist/acorn.js:3460:15)
    at Parser.pp$9.unexpected (vm-tests/node_modules/acorn/dist/acorn.js:756:10)
    at Parser.pp$9.semicolon (vm-tests/node_modules/acorn/dist/acorn.js:733:68)
    at Parser.pp$8.parseExpressionStatement (vm-tests/node_modules/acorn/dist/acorn.js:1216:10)
    at Parser.pp$8.parseStatement (vm-tests/node_modules/acorn/dist/acorn.js:949:26)
    at Parser.pp$8.parseTopLevel (vm-tests/node_modules/acorn/dist/acorn.js:813:23)
    at Parser.parse (vm-tests/node_modules/acorn/dist/acorn.js:586:17)
    at Function.parse (vm-tests/node_modules/acorn/dist/acorn.js:636:37)
    at parse (vm-tests/node_modules/acorn/dist/acorn.js:5576:19)
    at transformer (vm-tests/node_modules/vm2/lib/transformer.js:29:14) {
  pos: 6,
  loc: Position { line: 1, column: 6 },
  raisedAt: 9
}
```

A possible workround? is to use `Script` directly, avoiding `VMScript.compile`:
```
const { Script } = require("vm");

new Script("cosnt foo = 'bar'", {
  filename: "index.js",
});
```

**Comment by XmiliaH** [comment]
The first class does not compile since ECMA version 2020 was used. I will bump it to 2022.
As for the error messages I will try and supply a filename to `compileFunction`.
I am aware that the errors from acorn are not very verbose, but I am not certain how to do it better.

**Comment by agtraveso** [comment]
Thanks @XmiliaH for your quick response!

I'm curious to know the reason for changing the default compiler, is it related with some vulnerability/security issue? 

I see it's always invoked even if I provide a custom compiler to NodeVM so that lets compiler option a bit useless 🤔 

I've tried babel compiler with vm2 before that provides great traces but very poor performance, I want to try [swc](https://github.com/swc-project/swc) to see how it works. It could be a replacement for acorn

**Comment by XmiliaH** [comment]
Acorn is used for code transformation and checking and not compilation. For example, it will transform `} catch (e) {` to `} catch (e) {e = <internal>.handleException(e);` and look for async functions.
