### ISSUE TITLE
A custom compiler/transformer is ignored by require()

### ISSUE THREAD

**Issue by bartjoyce** [patriksimek/vm2#41]
If you set the `compiler` option to be coffee script or a custom function it will only be used to transform the main file you're running. If the main file includes other scripts, they won't be transformed.

As you can see in [sandbox.js, line 50](https://github.com/patriksimek/vm2/blob/master/lib/sandbox.js#L50) the required file is not passed through `_compileToJS()` before being executed.

**Comment by patriksimek** [comment]
Moved to https://github.com/patriksimek/vm2/pull/40
