### ISSUE TITLE
Major performance regression 3.9.5 -> 3.9.8

### ISSUE THREAD

**Issue by BenBirt** [patriksimek/vm2#410]
We're experiencing that code running in `vm2` is now running *much* slower, in some cases an order of magnitude slower (in wall clock time). Is this expected? Any ideas what could be happening?

**Comment by XmiliaH** [comment]
I do not know. It might be due to changes to context switch locations and since v8 cannot inline context switches (as far as I remember) this reduces JIT optimization opportunities. Furthermore, every catch now checks the exception first, but I assume that no own is timing exception paths. Maybe you should profile and look where the hotspots are.

**Comment by BenBirt** [comment]
I've been doing some profiling of our code, with no changes aside from swapping between `vm2` versions.

It's very difficult to compare profiles, presumably because of significant changes to `vm2` between `3.9.5` and `3.9.8` (I've tried to test out `3.9.6` and `3.9.7` but https://github.com/patriksimek/vm2/issues/406 makes it impossible to run the code).

However, I am able to consistently see a pretty huge difference in runtime (+50% increase in real execution time).

As far as I can tell, `vm2` seems to be spending *way* more time in `require` than it used to. In particular, stackframes that indicate code parsing seem to be taking ~30-50% of execution time. Has `vm2` changed parsing logic? (Note that we provide a custom compiler function to `vm2`, if that helps.)

**Comment by XmiliaH** [comment]
We need to do some code transformations. To do this we parse the code with acorn no matter if there is a custom compiler or not. If the script you are timing does almost nothing this might have increased runtime by the observed amount.
The require functionality was changed to resolve like node's require does it. However, this should not cause such a huge slowdown.

**Comment by BenBirt** [comment]
Thanks for the quick reply!

I'm not sure how to measure whether the script does "almost nothing" - but, in case it helps: we use `vm2` to execute arbitrary user code. Each execution is entirely one-off, i.e. we create a new, isolated sandbox each time a user requests this execution. The code we're executing, 99% of the time, all happens in `require` (i.e. each of a user's files is `require`'d once and once only, i.e. very little code is imported and used in more than one callsite). Execution is not allowed any access to any I/O (beyond `require`).

Do you have any ideas for where we could look next? I'm also happy to jump on a video call if that would help!

**Comment by XmiliaH** [comment]
To test if the acorn parser step causes the slowdown, you could add a `return code;` at https://github.com/patriksimek/vm2/blob/733579359f53d4b0c2c1beb95dc9d52eb6dc20d9/lib/transformer.js#L64
However, this will allows to break out of the sandbox and should only be done in a clean testing environment.

**Comment by XmiliaH** [comment]
My bad, the function does should not return a string but `return {__proto__: null, code, hasAsync: false};`

**Comment by BenBirt** [comment]
Great, thank you!

So - yes, I can confirm that adding that line of code *significantly* speeds up execution.

- running our code at `3.9.5`: execution time ~1s
- running our code at `3.9.8`: execution time ~1.45s
- running our code at `3.9.8` with that line of code: execution time ~1s

**Comment by BenBirt** [comment]
(Just to clarify - half a second increase wouldn't be an issue if that was generalized across user code; but the example above is just executing our example code, which is fairly simple. User projects - which we execute, as mentioned above - can be waaay more complex, and are taking multiple seconds longer to execute.)

**Comment by XmiliaH** [comment]
Unfortunately the transformer is required. The best I can come up with is:
```diff
--- a/lib/transformer.js
+++ b/lib/transformer.js
@@ -51,6 +51,9 @@ function transformer(args, body, isAsync, isGenerator, filename) {
        let argsOffset;
        if (args === null) {
                code = body;
+               if (!/\b(?:catch|import|async)\b/.test(code)) {
+                       return {__proto__: null, code, hasAsync: false};
+               }
        } else {
                code = isAsync ? '(async function' : '(function';
                if (isGenerator) code += '*';
```
But the `catch` case will often trigger and therefore reduce Performance by requiring the RegExp test.

**Comment by BenBirt** [comment]
That code is definitely a (small) improvement, my test case shows an execution time of (roughly) ~1.35s.

Would you mind elaborating on what the transformation is for / does? Are there any other potential ways we might speed it up? Might it be possible to configure acorn such that code parsing is faster?

**Comment by XmiliaH** [comment]
It is required to transform every `} catch (e) {` into something like `} catch (e) {e = <internal>.thisEnsureThis(e);`. This is required since host errors can leak into the sandbox. To do this transformation a full JS parser is required.

There is configuration for acorn known to me which could speed up things.

**Comment by BenBirt** [comment]
OK. Sounds like not much can be done here unfortunately.

**Comment by alxAgu** [comment]
This is a real bummer, this project seems to be the best out there but after spending days working on a solution that uses vm2, we realised actual user code is taking from 13 to 23 seconds to execute, while without vm2 it takes just 300ms!!!

@XmiliaH do you see this performance issue being addressed in the future? I was wondering if it is possible to export the transformed code as a string to be saved as a file and then load that transformed code during runtime and bypass transformations? just as a workaround to alleviate this performance issue.

@BenBirt, did you manage to find a workaround?

**Comment by XmiliaH** [comment]
There is nothing that can be done on the VM2 side as far as I am aware. Unfortunately we need to transform the source code since some constructs can be dangerous (async, import, catch).
When you reuse code you can try VMScript which transforms the code only once.
And you can experiment with saving `_hasAsync` and `_compiledCode` of the VMScript to file and restoring these fields on the next run though these are private and might change in the future without notice.
