### ISSUE TITLE
eval and try...catch together

### ISSUE THREAD

**Issue by Lingyan000** [patriksimek/vm2#418]
```javascript
const { VM } = require("vm2");

const vm = new VM({
  eval: true,
});

console.log(
  vm.run(`
  function _a() {
    eval("var a = 1");
    try {
      var b = 2;
    } catch (e) {
      var a = "";
    }
    return a;
  }
  _a()`)
);
```
Expected 1,Actual undefined

**Comment by XmiliaH** [comment]
DIrect eval is not supported. This is a known [issue](https://github.com/patriksimek/vm2#known-issues).

**Comment by Lingyan000** [comment]
> 

But the problem arises from
```javascript
    try {
      var b = 2;
    } catch (e) {
      var a = "";
    }
```

This code gives normal results
```javascript
const { VM } = require("vm2");

const vm = new VM({
  eval: true,
});

console.log(
  vm.run(`
  function _a() {
    eval("var a = 1");
    return a;
  }
  _a()`)
);
```

**Comment by XmiliaH** [comment]
The second case gives normal looking results as `eval("var a = 1");` will add `a` to the global. Then `return a` will return this global since there is no local declaration of `a`. This can be verified by returning `globalThis.a` instead of `a`.

**Comment by Lingyan000** [comment]
> The second case gives normal looking results as `eval("var a = 1");` will add `a` to the global. Then `return a` will return this global since there is no local declaration of `a`. This can be verified by returning `globalThis.a` instead of `a`.

Okay, now I get it.
