### ISSUE TITLE
Potential for asynchronous compiler for usage with NodeVM?

### ISSUE THREAD

**Issue by jamespantalones** [patriksimek/vm2#419]
I am running some preprocessing in the `compiler` step, and would like to offload the work to another thread/Worker if possible. I noticed the JS and CoffeeScript compile steps are all synchronous. Wondering if changing the compiler to `async` by default would be something you might consider?

**Comment by XmiliaH** [comment]
Changing the compiler to be asynchronous would require to many changes. However, no one is stopping you from running a compiler before passing the resulting JavaScript to the vm.
