### ISSUE TITLE
global.process is missing uptime function

### ISSUE THREAD

**Issue by Antoine-C** [patriksimek/vm2#424]
Some dependencies of ours rely on `process.uptime` and it's not implemented in https://github.com/patriksimek/vm2/blob/master/lib/setup-node-sandbox.js#L354

I'd like to know if there's a reason why (security, performance etc...) ? If not is there a way to add it from "outside" or can I make a PR to add this ?

Thank you

**Comment by XmiliaH** [comment]
Does PR https://github.com/patriksimek/vm2/pull/425 work for you?

**Comment by Antoine-C** [comment]
@XmiliaH works like a charm, thanks!
