### ISSUE TITLE
Graceful-fs and vm2

### ISSUE THREAD

**Issue by Antoine-C** [patriksimek/vm2#426]
We're allowing the `expect` package from jest to be required in our code. Problem is, with this package, it relies internaly on `graceful-fs` which [adds a property on fs](https://github.com/isaacs/node-graceful-fs/blob/main/graceful-fs.js#L25) and for security purpose it's not possible to set the builtin modules in vm2 (https://github.com/patriksimek/vm2/blob/master/test/nodevm.js#L143).

Do you have an idea on how to allow graceful-fs to work without jeopardizing the security ? I'm not 100% sure it's feasible.

Thanks

**Comment by XmiliaH** [comment]
Currently there is no nice solution. However, using the `mock` option it is possible to copy the fs object into the sandbox and use the copy to resolve the `fs` module.

```js
const {VM, NodeVM} = require("vm2");
const fs = require("fs");

const mock = {
	fs: undefined
};
const vm = new NodeVM({
	require: {
		mock
	}
});

const newObject = VM.prototype.run.call(vm, "()=>({})");
mock.fs = Object.assign(newObject(), fs);

console.log(vm.run("const fs = require('fs'); fs.x = 1; exports.x = fs.x;").x);
```

**Comment by Antoine-C** [comment]
Indeed I was playing with the mock option but wasn't sure it was the right way to go. Thanks for your quick help!
