### ISSUE TITLE
process.stdout and process.stderr are missing inside vm2

### ISSUE THREAD

**Issue by Antoine-C** [patriksimek/vm2#428]
We're using `mocha` inside vm2 and it uses both `process.stdout` and `process.stderr` (eg: https://github.com/mochajs/mocha/blob/master/lib/reporters/base.js#L38). Also `mocha` has `debug` as a dependency which uses them too. 

Is it possible to add them like in #425 or do they expose data outside vm2 scope ?

**Comment by XmiliaH** [comment]
This is not that easy to add. In the meantime it is possible to implement it yourself.

```js
const {NodeVM} = require("./index");
const {Writable} = require("stream");

let output = "";

const out = new Writable({
	write(chunk, encoding, callback) {
		output += chunk.toString();
		callback();
	}
});

const vm = new NodeVM();

vm.sandbox.process.stdout = out;

vm.run("process.stdout.write('Hi');");

console.log(output);
```

However, I did not check if the `Writeable` class exposes dangerous functions into the sandbox.

**Comment by Antoine-C** [comment]
Thanks for your quick feedback, I'll look into it 👍
