### ISSUE TITLE
Use child_process to keep the hand on the master process?

### ISSUE THREAD

**Issue by acorbel** [patriksimek/vm2#43]
Hi,

It is just a question, but, in order to keep the hand on the master process and avoid `while(true){}`, why no use a child process?

I'm kind of new with the sandbox and vm systems.

Here is my code:

```
//index.js
'use strict';

let child_process = require('child_process');

setInterval(function(){
    console.log('alpha');
}, 1000);

var child = child_process.fork('startCode.js');

setTimeout(function(){
    child.kill();
}, 10000);
```

```
//startCode.js
'use strict';

const NodeVM = require('vm2').NodeVM;

const vm = new NodeVM({
    console: 'inherit',
    sandbox: {},
    require: {
        external: true,
    }
});

setInterval(function(){
    console.log('alpha2'); 
}, 1000); //never shown do to infinite loop

let functionInSandbox = vm.run("while(true){}");
```

What do you think about it?

**Comment by patriksimek** [comment]
This is how many other sandboxes work so if this is a must for you, you should definitely go with other sandbox. This module allows you to directly and securely call methods, pass callbacks or share objects cross-sandbox. And thats unfortunately not possible when guest is running in separate process.
