### ISSUE TITLE
VMError: Unexpected access to key 'Symbol(nodejs.util.inspect.custom)'

### ISSUE THREAD

**Issue by loynoir** [patriksimek/vm2#431]
Error from '3.9.6' to '3.9.9'.

Last ok version is '3.9.5'

**Comment by XmiliaH** [comment]
I do not have a clue what you are doing.

**Comment by loynoir** [comment]
- vm2 newbee on day1
- spawn a node 16 repl and run the example "What is the difference between Node's vm and vm2?"

nodejs repl,  vm2 3.9.5
```js
> const {VM} = require('vm2');
> new VM().run('this.constructor.constructor("return process")().exit()');
> // OK
```

nodejs repl,  vm2 3.9.9
```js
> const {VM} = require('vm2');
> new VM().run('this.constructor.constructor("return process")().exit()');
Uncaught VMError: Unexpected access to key 'Symbol(nodejs.util.inspect.custom)'
```

**Comment by XmiliaH** [comment]
This is caused by node violating JS proxy rules in inspect. It should be easy to fix that this error does not occur any more. However, the underlying problem is not that easy to fix.
