### ISSUE TITLE
Separation of contextification from script compilation

### ISSUE THREAD

**Issue by alsterg** [patriksimek/vm2#44]
Node's VM module allows to compile a script with vm.Script() and at a later point contextify it with a number of different functions (e.g. script.runInNewContext). This is handy when one need to run the same exact code in multiple contexes. I presume that VM2 compiles the string-code every time vm.run() is called. I expect that this would result in performance degradation. 

Would it be a good idea for VM2's API to support some soft of way to reused a compiled piece of code multiple times across contexes? Is there a work-around to do this today?

**Comment by patriksimek** [comment]
This would be a nice improvement to the performance. I'm affraid there is no workaround. Feel free to submit a PR.

**Comment by patriksimek** [comment]
Implemented and released in 3.2.0.

**Comment by alsterg** [comment]
Thanks Patrik
