### ISSUE TITLE
vm2 loading files like bridge.js not playing well with packaging

### ISSUE THREAD

**Issue by skogs-pa** [patriksimek/vm2#440]
While trying to use require('vm2'), I run into the following error.

Error: ENOENT: no such file or directory, open '/red-acted/dist/bridge.js

How do you work around this? Initially, I thought it's just a problem with the bundler but it started happening with no bundler.  

Is there a solution other than copying the relevant files (bridge.js etc) to where the source code is?

**Comment by XmiliaH** [comment]
The script files loaded into the sandbox are loaded on runtime and are not included by bundlers automatically. It is possible to use plugins such as `babel-plugin-static-fs` to include the sources of the files where it would be loaded dynamically.

**Comment by skogs-pa** [comment]
Got it.  Thanks for the explanation.  I am now copying bridge.js, setup-sandbox.js, and set-node-sandbox.js files next to the bundled index.js using a plugin.  That works!

**Comment by samesfahani-tuplehealth** [comment]
May I politely ask why this is the case? Why are these files being loaded at runtime from `fs.fileSync` rather than just being imported?

**Comment by XmiliaH** [comment]
It might be possible to rewrite the files an put the code in a top level function. The source can then be obtained from the function through `toString` and imported into the VM. However, the bundler might rewrite the content in an unsafe manner.

**Comment by samesfahani-tuplehealth** [comment]
I can see how a bundler might mess with code integrity in a VM scope. It would need to be heavily tested for sure.

Ah, the joys of trying to use tools like esbuild and swc in a mature codebase... 😂
