### ISSUE TITLE
Abort a process from inside a VM

### ISSUE THREAD

**Issue by wvad** [patriksimek/vm2#449]
```js
Buffer.of().swap32.call(
  Object.defineProperty(
    Buffer.alloc(199),
    'length',
    { value: 200 }
  )
);
```
in a VM.

This also occurs when swap16 or swap64 is used instead of swap32.

**Comment by XmiliaH** [comment]
Killing the process was always possible with memory consumption `FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory.`

**Comment by maxless** [comment]
Is there any way to limit that? At least by removing the alloc calls.

**Comment by XmiliaH** [comment]
Added this to the limitations in the readme.
