### ISSUE TITLE
instanceof doesn't work

### ISSUE THREAD

**Issue by StNekroman** [patriksimek/vm2#455]
I have code
```
const events_1 = require("discord-text-games-api/events");

console.log("Event income 1 ", event);
console.log("Event income 2 ", events_1.JoinGameEvent);
console.log(event instanceof events_1.JoinGameEvent);
if (event instanceof events_1.JoinGameEvent) {
 ....
```
IF confition never resolves to true becuase `events_1.JoinGameEvent` is Proxy around real class,
while event I constructed from JoinGameEvent **outside of VM2**, so it's normal object.
Any thoughts?

**Comment by XmiliaH** [comment]
Sorry, I cannot reproduce the issue with:
```js
const { VM } = require('./index');

class A {
}

const vm = new VM({
	sandbox: {A, a: new A()}
});

console.log(vm.run(`a instanceof A`));
```

You need to provide more information.
What are the settings `NodeVM` is created with? Where comes event from?

**Comment by StNekroman** [comment]
Ah, I found the reason.
Between host and VM2 I have node thread worker layer, which serializes incomming event.
Inside worker, on receiving side, it deserializes it to plain Object, which now has different prototype.
