### ISSUE TITLE
NodeVM `require` config key cannot be false

### ISSUE THREAD

**Issue by takamonowhite** [patriksimek/vm2#456]
For my projects I am generally more comfortable to explicitly set default config values. But seems like I cannot pass `false` to `require` config key when creating new NodeVM.

![image](https://user-images.githubusercontent.com/107887993/182033072-dc55cd65-5562-406d-bce9-161ce6fcfdd3.png)

**Comment by XmiliaH** [comment]
Thanks for the feedback. Changed the allowed values to `boolean | VMRequire | undefined`.
