### ISSUE TITLE
call vm.run, error stack is incomplete

### ISSUE THREAD

**Issue by FanShiDe** [patriksimek/vm2#458]
Here is my usage, `safeScript` in picture is a long string that read from a javascript file:
<img width="582" alt="image" src="https://user-images.githubusercontent.com/21983486/182159345-b7fa8c2b-0e34-4784-9c42-01393a04a67e.png">

Error like this:
<img width="713" alt="image" src="https://user-images.githubusercontent.com/21983486/182159131-8095902f-c6e1-44f3-a45a-234667e2a644.png">

**I need to complete error stack info**, thx

**Comment by XmiliaH** [comment]
Sorry, but I cannot reproduce the issue with
```JS
const { NodeVM } = require('vm2');

const sandbox = {
	__globalDependencies: []
}
const safeScript = 'result = {};';
const variableName = 'value';

const vm = new NodeVM({
	console: 'inherit',
	eval: true,
	sandbox,
	require: {
		external: [],
		builtin: ['*'],
	},
	wrapper: 'none',
});
try {
	vm.run(
		`
			global.__globalDependencies = __globalDependencies;
			const fn = new Function(\`${safeScript}\`);
			fn();

			return result.function = global["${variableName}"]
		`
	);
} catch (e) {
	console.log(e);
}
```
Could you provide a reproducible test case and use text instead of images as it is easier to copy for testing.

**Comment by FanShiDe** [comment]
> Sorry, but I cannot reproduce the issue with
> 
> ```js
> const { NodeVM } = require('vm2');
> 
> const sandbox = {
> 	__globalDependencies: []
> }
> const safeScript = 'result = {};';
> const variableName = 'value';
> 
> const vm = new NodeVM({
> 	console: 'inherit',
> 	eval: true,
> 	sandbox,
> 	require: {
> 		external: [],
> 		builtin: ['*'],
> 	},
> 	wrapper: 'none',
> });
> try {
> 	vm.run(
> 		`
> 			global.__globalDependencies = __globalDependencies;
> 			const fn = new Function(\`${safeScript}\`);
> 			fn();
> 
> 			return result.function = global["${variableName}"]
> 		`
> 	);
> } catch (e) {
> 	console.log(e);
> }
> ```
> 
> Could you provide a reproducible test case and use text instead of images as it is easier to copy for testing.

**Comment by FanShiDe** [comment]
@XmiliaH sorry, the content of `safeScript` is private so that can't be to display in here, and the safeScript is a umd type javascript content
