### ISSUE TITLE
DOCS: Async implementation

### ISSUE THREAD

**Issue by keyscores** [patriksimek/vm2#46]
@patriksimek thanks for working on a safe sandbox. 

I'm looking for some docs on how to return sandbox results asynchronously

Do you have any advice or examples? 

I have the following suggestion below. However I see that the callback environment will be different than the sandbox env. This should normally be ok. Is there a way around this?

```
const {NodeVM} = require('vm2');
const request = require('request');

const vm = new NodeVM({
    sandbox:{
      request: request,
    }
});

let functionInSandbox = vm.run(`module.exports =  function(callback) {
  console.log('sandbox process env', process.env) ;

  request('http://google.com', function (error, response, body) {

        if (!error ) {
            callback( response.statusCode )
        }
    })
}`);

callbackFunc = function( result ){
  console.log('result after async', result);
  console.log('callback process env', process.env) ;
}

functionInSandbox( callbackFunc )
```

**Comment by patriksimek** [comment]
Thats the purpose of the vm - to change the environment so guest can't access host's properties. What do you mean by "Is there a way around this?"?

**Comment by keyscores** [comment]
What I mean is that in my callback implementation the process.env can be reached. So perhaps using a callback is not the most secure way of doing async operations, if there is a risk it can be broken out of. 

Do you have an example of how async operations should be implemented with vm2? I think the docs could benefit from that. 

Thanks in advance for maintaining this library, I think it's much needed in the community.

**Comment by patriksimek** [comment]
Your callback is running outside the vm so process.env can be accessed there. Thats correct. The code inside the vm can't access the callback because even function arguments are completly proxied. So there should be no way to break outside the sandbox.

I have updated the readme with an example.

**Comment by keyscores** [comment]
Ok I see it thanks. So I guess my assumption of using callbacks is correct. Are callbacks the only way of know if the sandbox has completed execution?

**Comment by patriksimek** [comment]
For asynchronous code, yes.

**Comment by keyscores** [comment]
Thanks for the quick response. We can close now.
