### ISSUE TITLE
WASM (WebAssembly) support with internal FS operations

### ISSUE THREAD

**Issue by zavalyshyn** [patriksimek/vm2#462]
Hi,

First of all, thanks for creating vm2 and making it available to people like me. I'm currently working on a second project where it will be used. 

I have a question rather than an issue per se. 
I'm trying to run a code that requires a wasm file (an opencv.js + opencv.wasm). After compiling a wasm binary I'm loading images and several models into internal WASM file system using FS_createDataFile() method. But it seems to get stuck there in an endless loop without throwing any error.

What is current vm2's support of wasm and internal file systems?

**Comment by XmiliaH** [comment]
There is currently no support for wasm and internal file systems.
