### ISSUE TITLE
Sandboxing modules recursively?

### ISSUE THREAD

**Issue by zxti** [patriksimek/vm2#463]
Really neat library, thank you for it!

It seems to provide "shallow" sandboxing around the literal script being executed. Any dependencies are not sandboxed, and can continue using any modules, accessing resources, etc.

Is there any way to get "deeper" sandboxing of all dependencies? Would like to be able to provide users with access to complex modules/libraries while still sandboxing requests from each other and from host. (Or if vm2 is not the right tool, is [isolated-vm](https://github.com/laverdet/isolated-vm) a better fit for this?)

```js
/** @format */

const { NodeVM } = require("vm2");
const vm = new NodeVM({
  require: {
    external: true,
    root: "./",
  },
  env: { foo: "bar" },
});

require("fs").writeFileSync("util.js", "console.log(process.env)");

vm.run(`console.log(process.env); require('./util')`, "vm.js");
```

**Comment by XmiliaH** [comment]
Try with option `require.context='sandbox'`.
```js
const vm = new NodeVM({
  require: {
    context: 'sandbox',
    external: true,
    root: "./",
  },
  env: { foo: "bar" },
});
```

**Comment by zxti** [comment]
Thank you, that looks like it!
