### ISSUE TITLE
Sandbox Breakout in VM2

### ISSUE THREAD

**Issue by oxeye-daniel** [patriksimek/vm2#467]
Hello 👋 
The [Oxeye](https://www.oxeye.io/) research team has found a sandbox breakout vulnerability in VM2. We would like to share the in-depth analysis with you so the vulnerability can be fixed. We tried to contact `security@integromat.com` but didn't get any response.

Could you please share with me an email address to keep the issue private?

Best,
Oxeye Research Team

**Comment by XmiliaH** [comment]
Thanks for reaching out, you can contact me under xmilia.hermit@gmail.com.

**Comment by XmiliaH** [comment]
Thanks for the report. This should be fixed in version 3.9.11.

**Comment by XmiliaH** [comment]
I do not have the necessary permissions in this repository to create advisories.

**Comment by Rugvip** [comment]
Ah sorry of course, is @patriksimek around? 🙏

**Comment by mchechik** [comment]
@XmiliaH - do you happen to know who the admins are for this repo and would have the necessary permissions? Thanks in advance!

**Comment by XmiliaH** [comment]
It is [patriksimek](https://github.com/patriksimek) but they are not very active in this repo.

**Comment by patriksimek** [comment]
I didn't find a way how to set roles for public repositories. Is migration to an organization the only way to allow @XmiliaH  to contribute to GitHub Security Advisory?

**Comment by mchechik** [comment]
to _create_ advisories, I think you have to make @XmiliaH an admin in this repo (under Collaborators settings), per this doc - https://docs.github.com/en/code-security/repository-security-advisories/permission-levels-for-repository-security-advisories

alternatively, you can create an empty advisory and add @XmiliaH as a collaborator (maybe @oxeye-daniel too, since they have the most details), per this doc - https://docs.github.com/en/code-security/repository-security-advisories/adding-a-collaborator-to-a-repository-security-advisory

**Comment by patriksimek** [comment]
Unfortunately, I can't see any configuration of roles in this repository.

I have created the empty advisory and shared access with both @XmiliaH  and @oxeye-daniel.

**Comment by oxeye-daniel** [comment]
Thanks, @patriksimek, for opening the advisory; it is much appreciated. 
@XmiliaH - I added my notes to the advisory, should you need any further details don't hesitate to contact me.

Thanks again everyone for the collaboration 🙏

**Comment by XmiliaH** [comment]
@oxeye-daniel Did you already request a CVE or should we do it through this advisory?

**Comment by oxeye-daniel** [comment]
@XmiliaH please request one through the advisory.

**Comment by XmiliaH** [comment]
In that case I have noting to add to the advisory. If @patriksimek has nothing to add they can publish the advisory as only they have the permissions to do so.

**Comment by oxeye-daniel** [comment]
Sounds good @XmiliaH; as I see it only @patriksimek has the permissions to create the advisory now.

**Comment by patriksimek** [comment]
Just requested the CVE and published the advisory. Let me know if there's anything else to do. Thank you @oxeye-daniel for reporting the issue and @XmiliaH for a quick fix!
