### ISSUE TITLE
Row and column are not given in certain errors since version vm2@3.9.8

### ISSUE THREAD

**Issue by JD342** [patriksimek/vm2#474]
I found a problem from starting in version 3.9.8. If we instantiate `NodeVM` like follows

```js
const nodeVm = new NodeVM({
  wrapper: "commonjs",
  console: "off",
  eval: false,
  wasm: false,
});
```

and run this code

```js
nodeVm.run(
  "\ninvalid varName = 'test'; module.exports = () => {}\n",
  "example.js"
);
```

The `SyntaxError` error that gets thrown doesn't have a `.loc` attribute any more, which we relied on to find exactly where the syntax error was in the code.

The specific example script to reproduce this regression is the following, which tries to retrieve the `.loc` attribute:

<details>
<summary>Content of test.js</summary>

```js
const { NodeVM } = require("vm2");

const nodeVm = new NodeVM({
  wrapper: "commonjs",
  console: "off",
  eval: false,
  wasm: false,
});

const code = `
invalid varName = 'test'; module.exports = () => {}
`;

try {
  nodeVm.run(code, "example.js");
} catch (e) {
  console.log(e.loc);
}
```

</details>

And what follow are the results on the command line using the versions of `vm2` from 3.9.7 up to 3.9.11. With version 3.9.7, we correctly fetch the `Position` object, while in later versions we get `undefined`.

![image](https://user-images.githubusercontent.com/11964463/192272261-0be4663d-6e6d-47b6-8955-272e04da3799.png)

**Comment by XmiliaH** [comment]
This property was never documented nor is it a default property of `SyntaxError`. The bug is more that the property was there.

**Comment by JD342** [comment]
How are you able to infer the row and column then? Doesn't seem possible other than using regular expressions on the stack trace.

**Comment by XmiliaH** [comment]
The same way one would do when getting a `SyntaxError` from a call to `eval`.
One way would be to use a library which parses the source for you again when a `SyntaxError` was thrown and gives more details about the error.
