### ISSUE TITLE
How to change and read sandbox variables value?

### ISSUE THREAD

**Issue by ZeroSkill830** [patriksimek/vm2#477]
Hello, how can i change the value of a sandbox variable?

I'm declaring a X variable in my sandbox and running a script

```
 const { NodeVM } = require("vm2");
  const fetch = require("node-fetch");
  const vm = new NodeVM({
    sandbox: { x: "Empty Sig", fetch },
    require: {
      context: "sandbox",
      external: [],
      root: "./",
      builtin: ["*"],
    },
  });

  vm.run(codeSnippet, vm.sandbox);
  console.log(vm.sandbox.x, "Sandbox X Variable");
```

where the script is:

```
async function getSignature(address) {
  let response = await fetch(
    `https://633acd46471b8c3955754d84.mockapi.io/signature?address=${address}`
  );
  let signature = await response.json();
  return {
    signature: signature[0],
  };
}

// usage example
getSignature('0x1234').then((res) =>{
  x = res.signature; //res.signature = 0x38403
});

```

But when i'm logging  `console.log(vm.sandbox.x, "Sandbox X Variable");` i still receive the first value "Empty Sig" and not "0x38403"

**Comment by XmiliaH** [comment]
This is expected as the 
```js
.then((res) =>{
  x = res.signature; //res.signature = 0x38403
});
```
will not run immediately but wait until the signature is received which is not the case at the time the console output happens.

**Comment by ZeroSkill830** [comment]
> This is expected as the
> 
> ```js
> .then((res) =>{
>   x = res.signature; //res.signature = 0x38403
> });
> ```
> 
> will not run immediately but wait until the signature is received which is not the case at the time the console output happens.

I imagined this but why delaying the console log with a setTimeout always return the original value?
How can i wait for the request response?

**Comment by XmiliaH** [comment]
> I imagined this but why delaying the console log with a setTimeout always return the original value?

That should not be the case. Maybe the time is to short and the fetch did not yet fetch the web content.

> How can i wait for the request response?

With normal `Promise` and `async` functionality. One could for example write the `Promise` from the `getSignature('0x1234')` into the `x` variable and then await on that promise outside of the sandbox.
