### ISSUE TITLE
How can I get the exported value in a script?

### ISSUE THREAD

**Issue by tal-rofe** [patriksimek/vm2#480]
I tried to get the exported object from a script:
```js
const {VM} = require('vm2');
const vm = new VM();

const script = `
module.exports = {
    glagla: {
        blabla: 2
    },
};

`;

let object = vm.run(script);

console.log(object);
```

But of course it complains: `[Error]: module is not defined`

If I use `NodeVM` it works. Is there anyway to make it work with `VM`?

**Comment by XmiliaH** [comment]
The `run` method of the `VM` returns the value of the last expression, so try:
```js
const exports = {
    glagla: {
        blabla: 2
    },
};
exports
```

**Comment by tal-rofe** [comment]
> The `run` method of the `VM` returns the value of the last expression, so try:
> 
> ```js
> const exports = {
>     glagla: {
>         blabla: 2
>     },
> };
> exports
> ```

I

**Comment by tal-rofe** [comment]
> > The `run` method of the `VM` returns the value of the last expression, so try:
> > ```js
> > const exports = {
> >     glagla: {
> >         blabla: 2
> >     },
> > };
> > exports
> > ```
> 
> I

I don't want to change the script.
Actually doing this:

```js
const {VM} = require('vm2');
const vm = new VM({
    sandbox: {
        module: {}
    }
});

const script = `
module.exports = {
    glagla: {
        blabla: 2
    },
};

`;

let object = vm.run(script);

console.log(object);
```
solved it.
Not sure why lol. Is it the correct way?

**Comment by XmiliaH** [comment]
If you are certain that the `module.exports = {...}` is the last statement this should work. If not you also could get the module back after the run with `vm.sandbox.module`.
