### ISSUE TITLE
Target's external node_modules in VM2

### ISSUE THREAD

**Issue by osztenkurden** [patriksimek/vm2#483]
Hey,

I wanted to ask if it's possible to execute file in a VM2 from specific location, in a sense that any require / import made in that file would reference node_modules from directory of that file, and not of a parent file? It would effectively mean running the whole project in a VM - and the goal would be to use target's node_modules so it will not throw if parent file's project does not have specific npm packages installed.

**Comment by XmiliaH** [comment]
Have a look at https://github.com/patriksimek/vm2#loading-modules-by-relative-path.
Assuming you have the directory `/sandbox/` with `/sandbox/node_modules` it is possible to use and load modules from the sandbox's node_modules wit:
```js
const {NodeVM} = require('vm');
const vm = new NodeVM({
    require: {
        external: true,
        root: '/sandbox/'
    }
});
vm.run('require("foobar")', '/sandbox/index.js');
```
Which will try to load foobar from the `/sandbox/node_modules` directory first.

**Comment by osztenkurden** [comment]
Thank you very much, it does precisely what I needed!

**Comment by elglogins** [comment]
Can this approach also work with not node_modules? just a regular common js, f.x. could be located int `/sandbox/` ?
