### ISSUE TITLE
Node.js crypto function not usable because of Proxy

### ISSUE THREAD

**Issue by SKoschnicke** [patriksimek/vm2#484]
When using `randomFillSync` from Node.js `crypto` module inside a NodeVM environment, it doesn't work:

```js
const { NodeVM } = require("vm2");
const vm = new NodeVM({
  require: {
    external: true,
    builtin: ["*"],
    root: "./",
  },
});

vm.run(
  `
    const crypto = require('crypto');
    const rnds8Pool = new Uint8Array(256);
    crypto.randomFillSync(rnds8Pool);
    console.log("Success", rnds8Pool);
`,
  "vm.js"
);
```

You'll get the following error (paths shortened):
```
.../nodevm-example/node_modules/vm2/lib/bridge.js:487
				throw thisFromOtherForThrow(e);
				^

TypeError [ERR_INVALID_ARG_TYPE]: The "buf" argument must be an instance of ArrayBufferView. Received an instance of Object
    at new NodeError (internal/errors.js:322:7)
    at Object.randomFillSync (internal/crypto/random.js:85:11)
    at VM2 Wrapper.apply (.../nodevm-example/node_modules/vm2/lib/bridge.js:485:11)
    at vm.js:4:12
    at VM2 Wrapper.apply (.../nodevm-example/node_modules/vm2/lib/bridge.js:485:11)
    at NodeVM.run (.../nodevm-example/node_modules/vm2/lib/nodevm.js:426:23)
    at Object.<anonymous> (.../nodevm-example/index.js:10:4)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32) {
  code: 'ERR_INVALID_ARG_TYPE'
```
I created a repository for easier reproducibility: https://github.com/SKoschnicke/nodevm-example

I think it is because the `Uint8Array` object is proxyed by vm2 and because of that the following code in the internal Node.js module fails to verify that the passed variable is of the right type:
https://github.com/nodejs/node/blob/6ac3a22f89ae43402d41166baf44266e60595fcb/lib/internal/crypto/random.js#L115
```js
  function randomFillSync(buf, offset = 0, size) {
    if (!isAnyArrayBuffer(buf) && !isArrayBufferView(buf)) {
      throw new ERR_INVALID_ARG_TYPE(
        'buf',
        ['ArrayBuffer', 'ArrayBufferView'],
        buf);
    }
```
`isAnyArrayBuffer` is defined here: https://github.com/nodejs/node/blob/a7e5b413efd5f98d4b9acf39ff5e87ddbd8c63ff/src/node_types.cc#L50

Tested with Node.js versions 14.19.0, 16.18.0 and 18.12.1.

Any chance to work around this issue?

**Comment by XmiliaH** [comment]
You could try to either use a `Buffer` inside of the sandbox which is a host object and should extend from `Uint8Array`.
Another option would be use use a mock for the crypto API and copy the arrays to and from the sandbox.

**Comment by ppedziwiatr** [comment]
@XmiliaH , can you please explain the workaround in a bit more detail?

I'm getting a similar error while executing:
```
crypto.createVerify(this.hashAlgorithm).update(data).verify(
          {
            key: pem,
            padding: crypto.constants.RSA_PKCS1_PSS_PADDING,
          },
          signature
        )
```        

in a NodeVM2:
<img width="1410" alt="image" src="https://user-images.githubusercontent.com/84311757/203995327-c9dbc40a-a3f0-4faa-b157-5516e1a37d86.png">


The NodeVM2 is configured like this:
```ts
const vm = new vm2.NodeVM({
          console: 'off',
          sandbox: {
            SmartWeave: swGlobal,
            BigNumber: BigNumber,
            logger: this.logger,
            ContractError: ContractError,
            ContractAssert: function (cond, message) {
              if (!cond) throw new ContractError(message);
            }
          },
          compiler: 'javascript',
          eval: false,
          wasm: false,
          allowAsync: true,
          wrapper: 'commonjs'
        });
```        

- what exactly should be changed in the above NodeVM configuration?

**Comment by XmiliaH** [comment]
Try with just
```js
const sig = Buffer.from(signature, "base64");
```

**Comment by ppedziwiatr** [comment]
> Try with just
> 
> ```js
> const sig = Buffer.from(signature, "base64");
> ```

That is not an option - I cannot modify the code that runs within the VM2 (which I'm not an author of).

**Comment by XmiliaH** [comment]
In that case I think your option with exposing `Uint8Array` into the sandbox seems good as I do not see an direct attack path here. Maybe it would be good to also expose all [TypedArrays](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray).

**Comment by ppedziwiatr** [comment]
I see, thanks for a quick answer!

I wonder if this info shouldn't be added to docs...
