### ISSUE TITLE
CustomRequire and other options are not taken from NodeVM instance options

### ISSUE THREAD

**Issue by akcyp** [patriksimek/vm2#490]
In the Typescript definitions we can see that `NodeVm.prototype.run` accepts only 3 options
![image](https://user-images.githubusercontent.com/67923777/204011524-d001e5ce-9dbd-40dc-91d7-fd3e69d4c9d3.png)

But inside source code of this method we have:
https://github.com/patriksimek/vm2/blob/ffa93989fbafb43b7a83633d1665c251eba6f8fb/lib/nodevm.js#L380-L386

This is definitely something wrong with configuration, probably some options like `CustomRequire` should be taken from `this.options`. My suggestion is to use merged options object (`this.options` with `options`) when it comes to `strict` and `wrapper`.
Also probably `dirname` is missing in typescript def.

**Comment by XmiliaH** [comment]
These undocumented options are currently experimental and therefore not documented. They are used for the `NodeVM` `Resolver` functionality, but I have not decided yet to make them official.
