### ISSUE TITLE
How to get the result of the code which is run by Node vm2

### ISSUE THREAD

**Issue by SotiriaSte** [patriksimek/vm2#496]
For example 

` const vm = new NodeVM({
    console: 'inherit',
    sandbox: {}
  });`
` 
 const script = 'const y = 2; const x =1; x + y;';
 const result = vm.run(script);`

The result is now {}. How to get the actual result witch is 3 in my case?

**Comment by XmiliaH** [comment]
The script in case of the `NodeVM` is a module. It needs to export the result.
```js
const vm = new NodeVM({ console: 'inherit', sandbox: {} });
const script = 'const y = 2; const x =1; exports.result = x + y;';
const result = vm.run(script).result;
```
