### ISSUE TITLE
`SyntaxError: Illegal return statement` error

### ISSUE THREAD

**Issue by remal** [patriksimek/vm2#497]
```ts
const content = 'any text'
const vm = new VM({
    sandbox: {
        content,
    },
    allowAsync: false,
    eval: false,
    wasm: false,
})
const transformedContent = vm.run('return content.replace(/a/, 'b')')
```

This code fails with `SyntaxError: Illegal return statement` error. How can it be fixed/rewritten?

**Comment by XmiliaH** [comment]
Just remove the return.

**Comment by remal** [comment]
But what if I have a much more complex code with conditions?

**Comment by XmiliaH** [comment]
The value from the last expression is returned. You could also use a function and immediately call it.
```js
(function(){
return something;
})()
```

**Comment by remal** [comment]
@XmiliaH it works, thanks! The issue can be closed.

I think it would be great if this scenario were documented somewhere. What do you think?

**Comment by XmiliaH** [comment]
I would argue that it already is documented. From the README:

> You can also retrieve values from VM.
>
> ```js
> let number = vm.run('1337'); // returns 1337
> ```

But feel free do make a PR.

**Comment by remal** [comment]
@XmiliaH you're absolutely right - it is documented. However, it's a bit confusing why `return` doesn't work.

**Comment by XmiliaH** [comment]
Since the JavaScript top-level scope cannot use the `return` statement. It is the same for the node `vm` module.
