### ISSUE TITLE
Add timeout option to NodeVM

### ISSUE THREAD

**Issue by paulrutter** [patriksimek/vm2#5]
Is there a reason why the "timeout" option is not implemented for the NodeVM case (since it is available for regular VM)?
I think it would be a nice improvement to the possibilities.

Is this something that is going to be added in the future?

**Comment by patriksimek** [comment]
Unfortunately, option `timeout` is not effective in `NodeVM`. This is a limitation of a Node.js itself and there is nothing I can do about it.

**Comment by paulrutter** [comment]
Ok thanks, we can then close this issue.
