### ISSUE TITLE
Exiting/closing a VM

### ISSUE THREAD

**Issue by peey** [patriksimek/vm2#50]
I'm creating multiple VM's in my script and I want to close/kill them and free up their resources as soon as their work is done.

I checked the tests and the script in there is just setting the vm variable to null, allowing the vm object to be garbage collected by js.

Is this is the appropriate way of exiting  a VM? And does it free up the resources allocated to the VM?

**Comment by patriksimek** [comment]
There is no other way to destroy the vm at the moment.

**Comment by edopalmieri** [comment]
Hi @patriksimek 
Is setting the VM to null a good way to force the execution of the code running inside the VM to stop?

I am trying to find a way to stop execution of the script running in the VM at a specific point. This would be done by the "host", ie. the class that created the vm instance. 

What is the best way to do this?
Cheers
Edoardo.

**Comment by patriksimek** [comment]
Setting `vm` to null have no effect because the code inside you VM is synchronous thread and can only be interrupted by throwing an error from the `stopVm` function. But, the code inside the sandbox can try-catch around the `stopVm` function so we end up with no solution to safely break the execution of a code running in the sandbox.

**Comment by edopalmieri** [comment]
Hi @patriksimek 
Thanks for your answer. Indeed, my solution until now was to throw an error, but as you said that can be ineffective if the script code has a try catch around it. 

The only other solution I can think of would be to have the vm run in a child process and kill the child process from stopVM. I will give that a try.

Thanks 
Edoardo

**Comment by edopalmieri** [comment]
Hi,

Using a child process and killing it from the "host" seems to do the trick. Here is my test code.

master process
```
const { fork } = require('child_process');

const vmProcess = fork('vmChildProcess.js');
console.log('Master process - start');
forked.send('run code');
console.log('Master process - finish');
```

child process
```
process.on('message', (msg) => {    
    console.log('Child process - message received');
    runCode();
    console.log('Child process - after runCode() call');
});

function runCode() {
    const { NodeVM, VMScript } = require('vm2');

    let vm = new NodeVM({
        wrapper: 'none',
        require: {
            context: 'sandbox'
        }
    });
    vm.freeze(() => { console.log('stopping vm...'); process.exit(0); }, 'stopVm');

    const code = `console.log('before stopping');
                    stopVm();
                    console.log('after stopping (this should not run)');`;

    console.log('Child process - before vm run');
    vm.run(new VMScript(code));
    console.log('Child process - after vm run');
}
```

**Comment by janhaa** [comment]
Is the implementation of @edopalmieri the preferred solution for controlling the running script for now?

**Comment by edopalmieri** [comment]
Hi @janhaa 

Indeed the child process solution works. However, what we have ended up implementing is a slight variation using Node's [worker threads](https://nodejs.org/api/worker_threads.html). The principle is the same, where the master thread has control over the threads it spawns, including killing them. When a process containing a VM sandbox is killed, the execution in the sandbox also stops at that same moment. 

We have had this implementation in place for over a year now and it has worked well.

I hope this helps.
Edoardo.

**Comment by janhaa** [comment]
Awesome, thanks for the inspiration @edopalmieri ! :)
