### ISSUE TITLE
VM and NodeVM behaves differently on await 

### ISSUE THREAD

**Issue by helloanoop** [patriksimek/vm2#513]
I have a requirement to change wait for vm2 to run asynchronous scripts. This works with `VM` but not with `NodeVM`.

Is this behaviour expected ?

```javascript
const {VM, NodeVM} = require('vm2');
const axios = require('axios');

const vm = new VM({
  sandbox: {
    axios
  }
});

const nodevm = new NodeVM({
  sandbox: {
    axios
  }
});

(async () => {
  const res = await vm.run(`
    axios.get('http://httpbin.org/get')
        .then(x => x.data)
        .then(x => x.url);
  `);

  const res2 = await nodevm.run(`
    axios.get('http://httpbin.org/get')
        .then(x => x.data)
        .then(x => x.url);
  `);

  console.log(res); // => http://httpbin.org/get
  console.log(res2); // => {}
})();
```

**Comment by XmiliaH** [comment]
This is expected. As JonasJonny pointed out for `NodeVM` `module.exports` as the script is run as a module.

**Comment by helloanoop** [comment]
Thanks @JonasJonny @XmiliaH 

We were able to use the solution proposed by @JonasJonny 

In case if anyone in the future bumps into a similar issue, here is the PR that fixed the issue in Bruno: https://github.com/usebruno/bruno/pull/145/files
