### ISSUE TITLE
console.log won't work

### ISSUE THREAD

**Issue by Bizarrus** [patriksimek/vm2#52]
No matter what options I set, `console` is `undefined` all the time.

`ReferenceError: console is not defined`

Trying with following Options: `inherit`, `redirect`

**Comment by Bizarrus** [comment]
Fixed this ugly, for the first time...

Had created an `sandbox` object for the options:

> new VM({
>    sandbox: {
>       console: {
>           log: function(str) { console.log(str); }
>       }
>    }
> });

**Comment by patriksimek** [comment]
Unlike `NodeVM`, console is not available in `VM` by default. Your workaround should be fine.

**Comment by Bizarrus** [comment]
Then, please update the Docs with this inromations. I had spend lot of hrs for that problem.

**Comment by patriksimek** [comment]
It's there:

> VM is a simple sandbox, without require feature, to synchronously run an untrusted code. Only JavaScript built-in objects + Buffer are available.
