### ISSUE TITLE
Accessing .buffer property on a Float32Array

### ISSUE THREAD

**Issue by Brokray** [patriksimek/vm2#523]
Hello there, I am currently using vm2 and would like to do some operations on a Float32Array in it.
However, .buffer seems inaccessible, it always returns an empty object rather than a Float32Array. 

```javascript
const { NodeVM } = require('vm2');

const vm = new NodeVM();
vm.run(`
    console.log(new Float32Array([0.1,-0.2]).buffer)
`);
```

I guess this is something linked to the Proxies and there is no workaround it?  
Would it be possible to add a custom function to the vm2 configuration that would be executed outside the vm container (allowing access to buffer)?

Thank you for your time.

**Comment by XmiliaH** [comment]
Maybe read https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/buffer about what the `buffer` property should return as it seems to work as intended. The only difference is that inspection of the returned `ArrayBuffer` will not print details if the `ArrayBuffer` is from within the sandbox.

**Comment by Brokray** [comment]
Thank you for your quick response. 
I guess my real problem might be elsewhere. Here is my **actual use case** : 

```javascript
const { NodeVM } = require('vm2');

const vm = new NodeVM();
vm.run(`
    function float64Buffer(arr) {
      const float64Array = new Float64Array(arr);
      return Buffer.from(float64Array.buffer);
    }

    float64Buffer([0.1,0.2]);
`);
``` 

This call throws the following error :   

```sh
TypeError: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received an instance of Object
at new NodeError in core node:internal/errors — line 393
at Function.from in core node:buffer — line 328
at ReadOnlyHandler.apply in vm2/lib/bridge.js — line 485
at float64Buffer in core vm.js — line 4
 in core vm.js — line 7
at VM2 Wrapper.apply in vm2/lib/bridge.js — line 485
```

And this seems to only happen in vm2, any idea why?

**Comment by XmiliaH** [comment]
This is happening as `Buffer` is actually the host `Buffer` and it cannot handle the proxied `ArrayBuffer` argument.

**Comment by Brokray** [comment]
Thanks a lot, it does indeed work!  
Do you see any drawback or security concern passing the `ArrayBuffer`?

**Comment by XmiliaH** [comment]
Last time I checked I did not find a security impact.

**Comment by Brokray** [comment]
Alright, thanks again for your help, have a great day!
