### ISSUE TITLE
Lib memory leak

### ISSUE THREAD

**Issue by GabrielLomba** [patriksimek/vm2#524]
The lib seems to be leaking sandboxes. Those are never collected because it appears they're attached to a closure in Object.prototype methods. I can reproduce using the sample code below and the latest vm2 version (3.9.17 at the time of writing):

```js
const {VMScript, VM} = require('vm2');

// class to make it easier to find obj in heap dump
class Leak_sample { constructor(v){ this.v = v; } };

const main = async ()=>{
    const obj = new Leak_sample({data: 'should_be_collected'}), data = [];
    const sandbox = {
        fn: ()=>console.log('Called sandbox fn: ', obj.v),
        collect: d=>data.push(new Leak_sample(d)),
    };
    const s = new VMScript(`
        fn();
        collect({data: 1});
        collect({data: 2});
    `, 'runner.js');
    console.log('Running script');
    await new VM({eval: false, wasm: false, sandbox}).run(s);
    console.log('Ran script: ', data);
}

main().then(()=>{
    global.gc();
    console.log('Ran GC');
});

process.stdin.resume(); // prevents Node from exiting
```

I would expect to have all `Leak_sample` objects collected after finishing `main()` but, even after running `global.gc()` + using the "Collect garbage" feature in Chrome to be sure, the `Leak_sample` objects  are still kept in memory:

![2023-04-28_11h53_00](https://user-images.githubusercontent.com/16962412/235181108-3706fe3c-7389-4040-a483-be9c53af1d71.png)

Shouldn't those objects have been collected? If not, what approach am I missing to force their collection and not result in an ever increasing memory usage?

**Comment by XmiliaH** [comment]
This library does not add any properties to `Object.prototype`. Furthermore, I do not know what the `gc` function does.
The only thing I can say is that the posted code should not leak memory.

**Comment by XmiliaH** [comment]
No, I did not try to reproduce this as I do not know what `gc` does and what it guarantees as it is possible that it will not collect the context object from `vm` modules which is a special object.

**Comment by GabrielLomba** [comment]
@XmiliaH if I understand correctly, the object is currently being kept in memory due to a closure in `Object.prototype.__defineGetter__`, which the lib also touches in [setup-sandbox.js](https://github.com/patriksimek/vm2/blob/4f63dc23fecabc79ee1501fde6e9e83c524d6466/lib/setup-sandbox.js#L162), not really related to the `vm` context object.

![image](https://user-images.githubusercontent.com/16962412/235201139-43f813ce-0872-4459-9314-e0831f1b70ca.png)

**Comment by XmiliaH** [comment]
Yes, we put the `__defineGetter__` function into a `WeakMap` as seen in the image. But that should remove the entry when the key becomes dead.

**Comment by GabrielLomba** [comment]
I see in [this comment](https://github.com/patriksimek/vm2/issues/232#issuecomment-579986161) that `vm` contexts used to not be collected due to GC heuristics (only really collected once we hit `--max-old-space-size`) but it's no longer the case in newer Node versions. I'm experiencing this in Node `v14.19.0`, however. Am I right by saying this is what's happening here? GC just does not want to dispose of the `vm` context because it has available memory elsewhere and this keeps the context `Object.prototype` copy in memory alongside everything else?

**Comment by XmiliaH** [comment]
I do not fully know how the `vm` context object integrates with the garbage collector, but I would assume that this is the case.

**Comment by GabrielLomba** [comment]
I have modified the script to allocate a significant amount of memory with `Leak_sample` and then read a 30MB randomly generated file and GC does end up collecting the `Leak_sample` objects when the process needs more memory (when we reach `--max-old-space-size`). There is no leak here. Appreciate the help @XmiliaH !
