### ISSUE TITLE
Handle error in async callback

### ISSUE THREAD

**Issue by vshymanskyy** [patriksimek/vm2#53]
Is there any way to handle error in async callback?

```js
const {NodeVM} = require('vm2');

const vm = new NodeVM({
    timeout: 10000,
    sandbox: {}
});

try {
  vm.run(`
    setInterval(() => {
      console.log("haha")
      process.exit()              // <--- can't find a way to intercept this!
    }, 1000);

    process.exit()
  `, 'code.js');
} catch(e) {
  console.log(e.message);
}


setInterval(() => {
  console.log("haha 2")
},1000);
```
I'm seeking for a way to prevent whole script crashing.

**Comment by patriksimek** [comment]
You can handle asynchronous errors like this:

```javascript
process.on('uncaughtException', (err) => {
	console.log(err);
})
```

Keep in mind that this catches all exceptions from both inside and outside of the VM.

**Comment by vshymanskyy** [comment]
Thx. Yes, it partially helped me. BTW, is there any way to distinguish if error in 'uncaughtException' is related to a VM (and possibly, which of them) or not?

**Comment by patriksimek** [comment]
Unfortunately not at the moment. I have an idea how to implement this but it will take some time.

**Comment by alsterg** [comment]
I'm wrapping vm.run() with domain.run() and it seems to work. I don't know if it has any side effects though..

```
let domain = Domain.create();
domain.on('error', (err) => {
    console.error('Asynchronous error while executing script.', err.stack);
});
domain.run(() => {
    try {
        vm.run(script, filename);
    } catch (err) {
        console.error('Synchronous error while executing script.', err.stack);
    }
});
```

**Comment by ImSingee** [comment]
@alsterg  The method seems to lose effectiveness..

@patriksimek Could you please tell me if you forgot about this?

**Comment by janhaa** [comment]
Confirming @ImSingee, method unfortunately does not work anymore.
Is there any update on how to handle async errors?

**Comment by AshuGuptaGamer** [comment]
Any updates on this???

**Comment by rob-gordon** [comment]
This is pretty messy so I'm not recommending anyone do this, but I'm posting the way I got around this here. I wanted my scripts to be able to contain `await` so I was already wrapping the scripts in `(async () => { ... })()`

To catch errors inside the async IIFE, I used another IIFE inside a try/catch to store the result, then returned a status key to tell me if there was an error or not.

```javascript
(async () => {
  try {
    let result = (() => {
      // script here
    })();
    return { status: "success", result: result };
  } catch (e) {
    return { status: "error", error: e.message };
  }
})();

```
