### ISSUE TITLE
What does console: 'redirect' mean

### ISSUE THREAD

**Issue by seanc** [patriksimek/vm2#54]
I wanted to know what you mean by "redirect to events" when using the `redirect` option for console in `NodeVM`. I have always used the sandbox method, of just attaching a console object with its own methods, however I wanted to know if there was an alternative cleaner solution

**Comment by patriksimek** [comment]
It's working like this:

```javascript
const vm = new NodeVM({
    console: 'redirect'
});

vm.on('console.log', (msg) => {
	console.log('REDIRECTED:', msg);
})

vm.run("console.log('hello');");
```

You can listen for those events:
- `console.log`
- `console.info`
- `console.warn`
- `console.error`
- `console.dir`
- `console.trace`

**Comment by seanc** [comment]
Awesome thanks!

**Comment by phyng** [comment]
Thanks! maybe we can add this to README or other documentation?
