### ISSUE TITLE
Instanciate Function on NodeVM

### ISSUE THREAD

**Issue by Bizarrus** [patriksimek/vm2#56]
Hey there,

i had instantiate the running script over `VM`. Here is an example:

**Executed Script**

    var Server = function Server() {
        this.test = function test() { console.log("HI"); };
    };

**Instantiate**

    _vm = new VM({/* ... *});
    vm.run(script, _path + '/main.js');
    // Instantiate the Class
    var Server = new _vm._context.Server();
    // Call the method
    Sevrer.test();

It's working fine on `VM`. But i had updated to `NodeVM` to use `require`, `setTimeout` and other,..
But how i can instantiate the `Server` "class" under `NodeVM`?

Under `_vm._context` the `Server` is not available. I had try to use `module.exports`, but here, i can't instantiate it. Not over the context and not over the returned value from `_vm.run()`.

The Result is:
 > TypeError: Server is not a constructor

Can anyone help me?

**Comment by patriksimek** [comment]
Try this:

```javascript
const vm = new NodeVM();
const Server = vm.run("module.exports = function Server() {this.test = function test() { console.log(\"HI\"); };};");
const server = new Server();
server.test();
```

**Comment by Bizarrus** [comment]
Okay, that's working. Big Thanks!

I had try the same before...

Okay, here is an working Update:

    // script is from file-reader!
    var script  = 'var Server = function Server() { this.onServerStart = function onServerStart() { console.log('Server was started'); }; };'; 

    const server	= _vm.run(script + ' module.exports = Server;', _path + '/main.js');
    const Server	= new server();
    if(typeof(Server.onServerStart) != 'undefined') {
        Server.onServerStart();
    }
