### ISSUE TITLE
timeout not work

### ISSUE THREAD

**Issue by NikSmith** [patriksimek/vm2#57]
Hi.
If unsafe code contain setInterval then timeout for VM is not work.

Example:

const {VM} = require('vm2');

const vm = new VM({
    timeout: 1000,
    sandbox: {
        setInterval: setInterval
    }
});

try {
    vm.run("setInterval(function(){},100)")
} catch (e) {
    console.log(e);
}

**Comment by patriksimek** [comment]
Yes, that's why setInterval and other async stuff is not available in VM by default.

**Comment by NikSmith** [comment]
Maybe vm.run should execute script in child process?!

**Comment by patriksimek** [comment]
This is how libraries like [jailed](https://github.com/asvd/jailed) or [sandbox](https://github.com/gf3/sandbox) works, so maybe you should use those.
