### ISSUE TITLE
node vm module API changes

### ISSUE THREAD

**Issue by mko-io** [patriksimek/vm2#58]
Hi, just heard of some v8 developer talked about API changes in the coming node 8.0. Do you know about the details? Will vm2 be affected?

<img width="498" alt="screen shot 2017-02-17 at 6 21 44 pm" src="https://cloud.githubusercontent.com/assets/10137567/23053423/39e0b654-f53e-11e6-9ff0-4e29b1dac1bb.png">

**Comment by patriksimek** [comment]
I have birefly looked at the changelog and didn't find anything that should break the library. vm2 doesn't rely on anything special here so I think there will be no problem with future Node releases.

**Comment by mko-io** [comment]
thank you for your answer
