### ISSUE TITLE
Advantages over the native VM module

### ISSUE THREAD

**Issue by odino** [patriksimek/vm2#59]
Hello there :)

Just wanted to know if there are clear advantages using vm2 over node's native VM module -- tried to look for it in the readme but couldnt find anything. I'm using vm on node 7 and was wondering if I should potentially look at vm2 if it fixes / handles specific use-cases.

Cheers!

**Comment by patriksimek** [comment]
The vm2 library doesn't fix anything, it uses internal VM as is. The reason to use vm2 is to execute a code and prevent it to access things outside the VM context.

**Comment by odino** [comment]
Though would it be the same of just running vm.runInNewContext(code, ctx)
where ctx is a user defined sandbox?

I kind of fail to see how this library would help more than the VM module
already does.

**Comment by patriksimek** [comment]
You can try yourself:

```
const vm = require('vm');
console.log(vm.runInNewContext('this.constructor.constructor("return process")().exit()'));
```

vs

```
const {VM} = require('vm2');
new VM().run('this.constructor.constructor("return process")().exit()');
```

**Comment by odino** [comment]
Ouch :( that's nasty!

Thanks for updating the readme.
