### ISSUE TITLE
Promises / callbacks and exported script methods : Is it safe ?

### ISSUE THREAD

**Issue by netgusto** [patriksimek/vm2#61]
Is it safe to:
* pass a promise to an exported script method ?
* receive a promise from a call to an exported script method ?

And more generally : is it safe to pass/receive a callback to/from an exported script method (not through the sandbox, that is) ?

**Comment by patriksimek** [comment]
Everything should be safe since every non-primitive value (like Promises or callbacks) are proxied between host and guest.
