### ISSUE TITLE
`instanceof` not always accurate

### ISSUE THREAD

**Issue by kellym** [patriksimek/vm2#64]
Because of the way things have to be proxied, it seems there are some situations where `instanceof` does not work as expected. For instance:

```javascript
const { VM } = require('vm2');
const assert = require('assert');
const vm = new VM({ sandbox: { stream: require('stream')} });

// Readable passes
assert.equal(
  new stream.Duplex() instanceof stream.Readable,
  vm.run('new stream.Duplex() instanceof stream.Readable')
);

// Writable does not pass
assert.equal(
  new stream.Duplex() instanceof stream.Writable,
  vm.run('new stream.Duplex() instanceof stream.Writable')
);
```

I'm seeing this is in part because Writable has some custom logic for determining `instanceof`, namely: 
```javascript
  realHasInstance = Function.prototype[Symbol.hasInstance];
  Object.defineProperty(Writable, Symbol.hasInstance, {
    value: function(object) {
      if (realHasInstance.call(this, object))
        return true;

      return object && object._writableState instanceof WritableState;
    }
  });
```

Now, I don't know what I'm doing in here, but adding this just [under here](https://github.com/patriksimek/vm2/blob/ef5f035502bd0304ba10c473b1b086def1c0712b/lib/contextify.js#L297):
```
if (key === 'prototype') return fnc.prototype;
```
and replacing [this line](https://github.com/patriksimek/vm2/blob/ef5f035502bd0304ba10c473b1b086def1c0712b/lib/contextify.js#L184) with this:
```
return object.__proto__;
```

resolves my issue I'm having with my code inheriting from Writable, but it doesn't fix the assertion test shown above. I'm not terribly certain how to work around this, either.

**Comment by patriksimek** [comment]
I will try to look at this soon, it requires a lot of time to investigate those kind of problems. Anyway, both changes you made are security holes.

**Comment by kellym** [comment]
Haha, figured that about the changes I made. Yeah, we are hitting some walls with the requirement of 'use strict' too, which is clearly non-negotiable in terms of security.
