### ISSUE TITLE
Edit the sandbox through a script

### ISSUE THREAD

**Issue by xchopin** [patriksimek/vm2#65]
Hi,

in node.js' VMs you can edit the content of a sandbox with a script, like this example:
```javascript
const util = require('util');
const vm = require('vm');

const sandbox = {
  animal: 'cat',
  count: 2
};

let script = 'count++;'

vm.runInNewContext(script, sandbox);
console.log(util.inspect(sandbox));

// { animal: 'cat', count: 3 }

```

When I do it with VM2 it gives me ``` count = 2 ``` like if it didn't edit the sandbox , is it possible to do something like this with VM2 ?

Thanks

**Comment by patriksimek** [comment]
This is not possible atm. In vm2, the `sandbox` is just a wrapper for vm's globals. You can access vm's globals like this: `console.log(util.inspect(vm.run('count')))`.
