### ISSUE TITLE
`require` external whitelist

### ISSUE THREAD

**Issue by contra** [patriksimek/vm2#66]
`require: { external: [ 'superagent', 'babel-runtime' ] }` would be a good API to do this

**Comment by schwimmfuzzi** [comment]
would also love to see this! :+1:

**Comment by orta** [comment]
I've added this in #88

**Comment by contra** [comment]
Sweet! Can you publish it?

**Comment by patriksimek** [comment]
@orta are you planning more additions or we can release this?

**Comment by orta** [comment]
I have one more PR today, then I think that's out for a bit

**Comment by orta** [comment]
OK, that's all of them ❤️
