### ISSUE TITLE
Does not work with relactive paths

### ISSUE THREAD

**Issue by barenko** [patriksimek/vm2#67]
If you use the follow code:
`vm.run("require('lib/foobar')", "/mysource/lib/script.js");`

Running the nodejs app with:
`NODE_PATH=/mysource node app.js`

The follow error happens:
`VMError: You must specify script path to load relative modules.`

Can you update the api to allow these relative paths too?

**Comment by patriksimek** [comment]
Could you please post a full code to reproduce the issue?

**Comment by XmiliaH** [comment]
This should work. Closed for it's age.
