### ISSUE TITLE
Make vm2 compatible with Webpack

### ISSUE THREAD

**Issue by patriksimek** [patriksimek/vm2#70]
- [x] figure out how to remove `coffee-script` require without breaking a backwards compatibility
- [ ] figure how to instruct webpack to bundle scripts loaded via fs - sandbox.js and contextify.js

**Comment by Coxxs** [comment]
Another issue is `require`. Although webpack just generate warnings for these require:
```
WARNING in ./~/vm2/lib/main.js
147:26-33 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./~/vm2/lib/main.js
251:3-10 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./~/vm2/lib/main.js
295:26-33 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
```
webpack actually replaced these require with exceptions:
For example, before webpack:
```
		Reflect.defineProperty(this, '_internal', {
			value: vm.runInContext(`(function(require, host) { ${cf} \n})`, this._context, {
				filename: `${__dirname}/contextify.js`,
				displayErrors: false
			}).call(this._context, require, host)
		});
```

After webpack:
```
		Reflect.defineProperty(this, '_internal', {
			value: vm.runInContext(`(function(require, host) { ${cf} \n})`, this._context, {
				filename: `${__dirname}/contextify.js`,
				displayErrors: false
			}).call(this._context, !(function webpackMissingModule() { var e = new Error("Cannot find module \".\""); e.code = 'MODULE_NOT_FOUND'; throw e; }()), host)
		});
```

Replace `require` with `eval('require')` can solve the problem for me. I wonder if there is a better solution.

**Comment by Bartozzz** [comment]
Any progress on this issue? Here is the best and probably the simplest way I've found to make `vm2` compatible with `Webpack`. It doesn't require any changes in `vm2` itself, just 3 lines of additional configuration and a simple NPM script:

1. Create a `package.json` in the `output/` directory:
```json
{
    "dependencies": {
        "vm2": "latest"
    }
}
```

2. Mark `vm2` as an external library in the Webpack config:

```javascript
externals: {
    "vm2": "require('vm2')"
}
```

3. Add an additional script in NPM which installs dependencies in `output/` directory once Webpack has finished all the stuff:

```json
"scripts": {
    "prepare-output": "cd output && npm install",
    "prepare": "webpack --progress && npm run prepare-output"
}
```

**Comment by mariohmol** [comment]
I'm receiving an error in this line  
```
	const host = {
			version: parseInt(process.versions.node.split('.')[0]),
			!(function webpackMissingModule() { var e = new Error("Cannot find module \".\""); e.code = 'MODULE_NOT_FOUND'; throw e; }()),
			process,
			console,
 ``` 

``` 
SyntaxError: Unexpected token !
    at new Script (vm.js:51:7)
    at createScript (vm.js:136:10)
    at Object.runInThisContext (vm.js:197:10)
    at Module._compile (internal/modules/cjs/loader.js:618:28)
```

Any ideas?

Thanks

**Comment by titoasty** [comment]
Hi !

I got the same problem and here is how I resolved it :

1. First, I can't directly use the module as a npm module, because I had to modify the sources, so I c/c the lib in a folder of my project (it's only a few files, no problem with that)

2. About the fs for sandbox.js/contextify.js : I renamed them sandbox.txt & contextify.txt, then used a raw-loader to load them as plain text.

main.js (at the top)
```
const sb = require('./sandbox.txt');
const cf = require('./contextify.txt');

```

webpack.config.js
```
{
    test: /\.txt$/,
    use: 'raw-loader'
}
```

**Don't forget to change all references of sandbox.js/contextify.js to sandbox.txt/contextify.txt in main.js.**

3. Last tricky part, require : for NodeVM, I changed one line

main.js (around line 250)
```
[...]
const host = {
	version: parseInt(process.versions.node.split('.')[0]),
	require: eval('require'),
	process,
	console,
[...]
```
I changed the "require" to "require: eval('require')" so webpack doesn't modify it (as suggered by Coxxs) and it did the trick.

Now I can use vm2 properly, without needing it as an external library.
I know it's quite tricky and not very clean, but it's the only solution I got so far.
I hope it can help some of you & also help in a real fix.

If you have better solutions, we'd love to hear them ! :)

**Comment by philcockfield** [comment]
FWIW - bundling with Webpack 5, with a target of `node` appears to work.

**Comment by yalondpsi** [comment]
> FWIW - bundling with Webpack 5, with a target of `node` appears to work.

Can you please submit the basic configuration you are using please. I'm struggling here with webpack 4...
Thank you

**Comment by yalondpsi** [comment]
> Any progress on this issue? Here is the best and probably the simplest way I've found to make `vm2` compatible with `Webpack`. It doesn't require any changes in `vm2` itself, just 3 lines of additional configuration and a simple NPM script:
> 
> 1. Create a `package.json` in the `output/` directory:
> 
> ```json
> {
>     "dependencies": {
>         "vm2": "latest"
>     }
> }
> ```
> 
> 1. Mark `vm2` as an external library in the Webpack config:
> 
> ```js
> externals: {
>     "vm2": "require('vm2')"
> }
> ```
> 
> 1. Add an additional script in NPM which installs dependencies in `output/` directory once Webpack has finished all the stuff:
> 
> ```json
> "scripts": {
>     "prepare-output": "cd output && npm install",
>     "prepare": "webpack --progress && npm run prepare-output"
> }
> ```

@Bartozzz Hi
Can you please submit the basic configuration files you are using please. I'm struggling here with webpack 4...
Thank you

**Comment by yalondpsi** [comment]
> FWIW - bundling with Webpack 5, with a target of `node` appears to work.

@philcockfield Hi,
Can you please submit the basic configuration files you are using please. I'm struggling here..

**Comment by cjahv** [comment]
My plan. Use scripts to statically store JS in JSON

patch: 
```
diff --git a/.gitignore b/.gitignore
index 8c54104..ca573e1 100644
--- a/.gitignore
+++ b/.gitignore
@@ -3,4 +3,5 @@
 .svn
 /node-*
 /test.js
-.vscode
\ No newline at end of file
+.vscode
+/lib/static.json
diff --git a/lib/main.js b/lib/main.js
index 05ed86f..3ad79ce 100644
--- a/lib/main.js
+++ b/lib/main.js
@@ -46,7 +46,12 @@ const MODULE_SUFFIX = '\n});';
  * @return {vm.Script} The compiled script.
  */
 function loadAndCompileScript(filename, prefix, suffix) {
-       const data = fs.readFileSync(filename, 'utf8');
+       let data;
+       if (!fs.existsSync(filename)) {
+               data = require('./static.json')[pa.basename(filename)];
+       } else {
+               data = fs.readFileSync(filename, 'utf8');
+       }
        return new vm.Script(prefix + data + suffix, {
                filename,
                displayErrors: false,
@@ -1304,7 +1309,7 @@ class VMError extends Error {
  */
 const HOST = {
        version: parseInt(process.versions.node.split('.')[0]),
-       require,
+       require: eval('require'),
        process,
        console,
        setTimeout,
diff --git a/package.json b/package.json
index cbc41ae..48efa33 100644
--- a/package.json
+++ b/package.json
@@ -28,7 +28,8 @@
   },
   "scripts": {
     "test": "mocha test",
-    "pretest": "eslint ."
+    "pretest": "eslint .",
+    "prepublishOnly": "node ./scripts/build-static.js"
   },
   "bin": {
     "vm2": "./bin/vm2"
```

scripts/build-static.js
```
#!/usr/bin/env node
const fs = require('fs');
const path = require('path');

const staticFilenameList = [
	'contextify.js',
	'fixasync.js',
	'sandbox.js',
];

const libPath = path.join(__dirname, '../lib');
const staticObject = {};
for (let i = 0; i < staticFilenameList.length; i++) {
	const filename = staticFilenameList[i];
	const fileAbsolute = path.join(libPath, filename);
	staticObject[filename] = fs.readFileSync(fileAbsolute, 'utf-8').toString();
}
fs.writeFileSync(path.join(libPath, 'static.json'), JSON.stringify(staticObject));
```

**Comment by taras** [comment]
> FWIW - bundling with Webpack 5, with a target of `node` appears to work.

@philcockfield any chance you might have an example of webpack config because I'm using Webpack 5 with `target=node` and same problem.

**Comment by vijaybabu4589** [comment]
i am using `angular-devkit/build-angular` to build nodejs server,
```
node ./server/dist-server/main.js

/server/dist-server/main.js:469819
  __webpack_require__(60863),
                      ^^^^^
SyntaxError: Unexpected number
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
```
ENV
```
Angular CLI: 12.2.6
Node: 14.16.0
Package Manager: npm 6.14.11
OS: darwin x64

Angular: 
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1201.4
@angular-devkit/core         12.2.6
@angular-devkit/schematics   12.2.6
@schematics/angular          12.2.6

```

**Comment by reidkersey** [comment]
@taras I have an example working webpack config file in the PR above (https://github.com/patriksimek/vm2/pull/388) and here is a patch file that does what is in the PR. 

vm2+3.9.5.patch
```
diff --git a/node_modules/vm2/lib/main.js b/node_modules/vm2/lib/main.js
index 1b0d867..c8f445e 100644
--- a/node_modules/vm2/lib/main.js
+++ b/node_modules/vm2/lib/main.js
@@ -1335,7 +1335,7 @@ class VMError extends Error {
  */
 const HOST = {
 	version: parseInt(process.versions.node.split('.')[0]),
-	require,
+	require: eval('require'),
 	process,
 	console,
 	setTimeout,
```

**Comment by XmiliaH** [comment]
It is possible to remove the coffee-script warning with
```
ignoreWarnings: [
	{
		message: /Can't resolve 'coffee-script'/,
	},
]
```
and `Critical dependency: require function is used in a way in which dependencies cannot be statically extracted` can be fixed by adding
```
module: {
	parser: {
		javascript: {
			commonjsMagicComments: true
		}
	}
}
```
Finally, it is possible to inline script which are loaded into the sandbox by using the `babel-plugin-static-fs` plugin.
