### ISSUE TITLE
Allow inheriting stdout and stderr

### ISSUE THREAD

**Issue by callumlocke** [patriksimek/vm2#71]
Thank you for this AMAZING module.

I would like the ability for a NodeVM to inherit stdout and stderr streams from the host.

Looks like this was in an [old PR](https://github.com/patriksimek/vm2/pull/3) that never got merged.

Also, even if inheriting is not enabled, it would be good if `process.stdout` and `process.stderr` could be mocked/stubbed anyway, just so they don't cause errors when people do things like [this](https://github.com/mishoo/UglifyJS2/blob/v2.6.4/tools/node.js#L2-L5) (throws `stream is undefined`).

**Comment by patriksimek** [comment]
Thank you for your kind words. This should be an easy addition. Are you also interested in creating a PR for that?

**Comment by tibuurcio** [comment]
Thank you from me as well @patriksimek, great library! 😄 

Hey @callumlocke, I'm not sure if this is what you meant by `inherit stdout and stderr from the host`  but I was trying to get the output from `vm.run()` and did it this way: [gist](https://gist.github.com/iamkvein/2006752) (There's an example with stdout at the end)

Does this seems like a workaround for the requested feature? I would like to get the output from the vm and after a whole day searching this was the best I could find!
