### ISSUE TITLE
Unable to disable promises in the VM

### ISSUE THREAD

**Issue by jtokoph** [patriksimek/vm2#74]
Is there a way to disable promises in the VM? I seem to get different errors when attempting with different methods to disable.

Using `sandbox: { Promise: null }` causes issues with contextify.

```js
VM = require('vm2').VM;
new VM({
  sandbox: {
    Promise: null,
  }
}).run('class Foo {}; new Foo();');
```
```
TypeError: Right-hand side of 'instanceof' is not an object
    at Object.value (/Users/jtokoph/tmp/node_modules/vm2/lib/contextify.js:232:22)
    at VM.run (/Users/jtokoph/tmp/node_modules/vm2/lib/main.js:207:39)
```

Using `sandbox: { Promise: function() }` causes the process to hang with this simple example:

```js
VM = require('vm2').VM;
new VM({
  sandbox: {
    Promise: function() {},
  }
}).run('class Foo {}; new Foo();');
```

**Comment by PostCrafter** [comment]
I've come up with the following solution, which works fine in my test cases, simply replacing Promise with a dummy implementation:
```
function PromiseDummy() {}
function PromiseFactory() {
  return new PromiseDummy();
}
PromiseDummy.prototype.then = PromiseFactory;
PromiseDummy.prototype.catch = PromiseFactory;
PromiseDummy.all = PromiseFactory;
PromiseDummy.race = PromiseFactory;
PromiseDummy.resolve = PromiseFactory;
```

```
sandbox: {
  Promise: PromiseDummy,
}
```

With the addition of JavaScript async functions the user is now able to redefine Promises.
`Promise = (async function(){})().constructor;`

Any idea on how to disable this behaviour?

**Comment by GingerPlusPlus** [comment]
How about changing the check in this line https://github.com/patriksimek/vm2/blob/788d06f28724b68fc1eaa08c881314c466e9f870/lib/contextify.js#L232

to
```js
Promise && value instanceof Promise
```
?

**Comment by GingerPlusPlus** [comment]
> With the addition of JavaScript async functions the user is now able to redefine Promises: Promise = (async function(){})().constructor;.
>
> Any idea on how to disable this behaviour?

Good catch. No idea how to achieve that. Workaround I'll use is to run the app on Node 6.x, before async functions were a thing :P
