### ISSUE TITLE
require.builtin can be escaped when require.context is host

### ISSUE THREAD

**Issue by tommytroylin** [patriksimek/vm2#76]
When `require.context` === host and sets `require.builtin` to block `fs` module.
Everything works fine except for requiring an external module which `require('fs')` in its code.
In this case, `VM` should throw an `Access denied to require 'fs'` error but it doesn't.

Seems like `require` in host is not patched as expected

**Comment by patriksimek** [comment]
Thank you for reporting this, I will investigate this asap.

**Comment by johannesschobel** [comment]
Hey @patriksimek , 
any news on this issue?

**Comment by jaruba** [comment]
i ran into this issue too, ended up using webpack to bundle everything to one file

**Comment by tenry92** [comment]
I think this is the same issue I am experiencing. Let me provide some sample code for testing:

index.js:
```javascript
const fs = require('fs');
const {NodeVM} = require('vm2');

const vm = new NodeVM({
  console: 'inherit',
  sandbox: {},
  require: {
    external: true, // allow require('./module')
    root: 'untrusted/',
    require: {
      builtin: [],
    },
    
    mock: {
       fs: {
         readFileSync() { return 'Nice try!'; },
       },
    },
  },
});

const source = fs.readFileSync('./untrusted/index.js', 'utf8');
vm.run(source, './untrusted/index.js');

console.log('done');

```

untrusted/index.js:
```javascript
console.log('I am ./untrusted/index.js');

const fs = require('fs');
const fileContents = fs.readFileSync(__dirname + '/index.js', 'utf8');

console.log('index.js file read:', fileContents);

require('./module');
```

untrusted/module.js:
```javascript
console.log('I am ./untrusted/module.js');

const fs = require('fs');
const fileContents = fs.readFileSync(__dirname + '/index.js', 'utf8');

console.log('module.js file read:', fileContents);
```

And run `node index.js`. Expected output:

```
I am ./untrusted/index.js
index.js file read: Nice try!
I am ./untrusted/module.js
module.js file read: Nice try!
done
```

Actual output:

```
I am ./untrusted/index.js
index.js file read: Nice try!
I am ./untrusted/module.js
module.js file read: console.log('I am ./untrusted/index.js');

const fs = require('fs');
const fileContents = fs.readFileSync(__dirname + '/index.js', 'utf8');

console.log('index.js file read:', fileContents);

require('./module');

done
```

If I require `some-module` in `untrusted/index.js`, vm2 looks into the mock option, and if found, returns its value.
If I require `some-module` in `untrustred/module.js`, vm2 looks into the mock option, and if found, loads it from the app's node_modules path (possibly outside the path option) or builtin module.
If I require `some-module` in `untrustred/module.js` and vm2 does not find it in the mock option, it will throw the "not found" error.

**Comment by XmiliaH** [comment]
This works as intended, since modules required from the host can require any module in the host, they are not restricted by the sandbox. If this is not intended, use require.context==='sandbox'.
