### ISSUE TITLE
Timeout support for NodeVM

### ISSUE THREAD

**Issue by dbuarque** [patriksimek/vm2#77]
NodeVM is awesome, would be really nice to have a timeout for it. How can we make it happen?

**Comment by bigman73** [comment]
How come timeout works for vm but not for NodeVM?
This is a major concern - untrusted code can easily cause the host to get stuck with a malicious and simple infinite loop

**Comment by RAnders00** [comment]
This should be reopened since it's still relevant. Useless bot.

**Comment by takayama-lily** [comment]
我不明白为什么NodeVM无法实现timeout。
没有timeout攻击者可以轻易使程序进入死循环。
其他对于沙箱逃逸的防止也变得毫无意义。
