### ISSUE TITLE
'use strict' breaks execution of popular modules

### ISSUE THREAD

**Issue by DanielChilcott** [patriksimek/vm2#79]
A number of modules fail to execute when require.context is set to 'sandbox'. This is due to sandbox.js  applying 'use strict'.

Please consider making this a configurable setting - perhaps at require.context.sandbox?

Underscore.js is an example of one module that can't be run with 'use strict'

**Comment by matthew-dean** [comment]
Yeah, injecting `use strict` seems like over-reach. There shouldn't be an expectation that sandboxed code requires it.
