### ISSUE TITLE
Quick Question

### ISSUE THREAD

**Issue by benjsicam** [patriksimek/vm2#8]
How do I use this module to execute untrusted code securely and wait for a return data? The return data can be a JSON Document.

Would you be able to provide a sample gist for the use case above? Thanks!

**Comment by patriksimek** [comment]
```javascript
var vm = require('vm2');
var sb = new vm.VM({timeout: 100});
var json = sb.run('(function(){return "{\\"sample\\": \\"json\\"}"})()');

console.log(json);
```

**Comment by benjsicam** [comment]
Thank you very much!
