### ISSUE TITLE
Script did not time out

### ISSUE THREAD

**Issue by polomoshnov** [patriksimek/vm2#81]
I expected this would time out instantly but it actually took a few seconds to callback the value successfully.

```VM = require('vm2').VM;

vm = new VM({
  timeout: 1
});

functionInSandbox = vm.run('(function (callback) { var i = 10000000000; while (i--) {} callback(2 + 2) })');

functionInSandbox(function (value) {
  console.log(value);
});
```

Although, this times out well:

```VM = require('vm2').VM;

vm = new VM({
  timeout: 1
});

value = vm.run('var i = 10000000000; while (i--) {} 2 + 2');

console.log(value);

**Comment by Kanaye** [comment]
Hi @polomoshnov.
As far as I understand this is expected and you can't do much about it.
To quote the [readme](https://github.com/patriksimek/vm2/blob/master/README.md) `IMPORTANT: Timeout is only effective on code you run through run. Timeout is NOT effective on any method returned by VM.`.
