### ISSUE TITLE
Add support for TypeScript type definitions?

### ISSUE THREAD

**Issue by orta** [patriksimek/vm2#89]
Hi there, as a part of using this module, I've built out a rough TypeScript definition for the API. It's currently in my project:

```ts

declare module "vm2" {
  export interface VMRequire {
    builtin?: any[]
    context?: "host" | "sandbox"
    external?: boolean
    import?: string[]
    root?: string
    mock?: any
  }

  export interface VMOptions {
    compiler?: "javascript" | "coffeescript"
    sandbox?: any
    timeout?: number
  }

  export interface NodeVMOptions extends VMOptions {
    console?: "inherit" | "redirect"
    require?: true | VMRequire
    nesting?: boolean
    wrapper?: "commonjs" | "none"
  }

  export class NodeVM {
    constructor(options?: NodeVMOptions)
    run(js: string, path: string): any
  }

  export class VM {
    constructor(options?: VMOptions)
    run(js: string, path: string): any
  }
}
```

I'm happy to add inline docs and finish the API then PR it to this repo, so that anyone with VS Code will get auto-completion and inline docs. If you'd rather it not be in this repo (which is reasonable) then I can submit those to DefinitelyTyped. If this stuff is new to you, then I'd recommend reading this issue https://github.com/alexa-js/alexa-app/pull/266 where I + others cover the trade-offs.

**Comment by tenry92** [comment]
It looks like NodeVM is extending the event emitter, which is required for listening to "redirected" console logs. That should be added to the TS definitions as well.
