### ISSUE TITLE
VSCode Debugger Crashes with VM2 Code

### ISSUE THREAD

**Issue by jagadishg** [patriksimek/vm2#93]
The following code crashes VSCode Debugger when it hits the break point.

```
const {VM} = require('vm2');
const vm = new VM({});
var func = vm.run('function test() { return "Hello world"; }; test');
console.log(func());
```

The application crashes only when we set the break point, otherwise it executes just fine. I'm not seeing this problem with Node's VM Module.

I'm not sure if it is a problem with vm2 or vscode? Any ideas?

**Comment by wysisoft** [comment]
If you're not totally married to VSCode, I've had the best luck using NIM and chrome, I bailed on visual studio nodejs debugger a few weeks ago because of really poor behavior. NIM and chrome have been rock solid.
