### ISSUE TITLE
Require documentation and resources in order to utilize all available vm2 options

### ISSUE THREAD

**Issue by NishiBangar** [patriksimek/vm2#94]
Hi @patriksimek , i m new to the concept of vm and i am in the middle of implementing a concept wrt vm2 utilization, but, i am finding it difficult to make the implementation since i have found very less documentation and examples on the usage of all its available options. (or may be i couldn't find the proper available resource). Kindly help me with the resources that i can refer in order to proceed with my implementation.

**Comment by orta** [comment]
The README covers nearly all of the general use-cases, but if that's not enough, the majority of the source code you'd need to read to get started is under 1k: [main.js](https://github.com/patriksimek/vm2/blob/master/lib/main.js) / [sandbox.js](https://github.com/patriksimek/vm2/blob/master/lib/sandbox.js)
