### ISSUE TITLE
Question about NodeVM Threading

### ISSUE THREAD

**Issue by Eric24** [patriksimek/vm2#98]
Does NodeVM run in a separate thread? Can it support Promises and/or callbacks? Ideally, I'd like to be able to start multiple NodeVM scripts from the main "supervisor" program and have them run in parallel.

**Comment by evanderkoogh** [comment]
@Eric24 NodeVM is 'just' a layer around the core VM module in node. It will run it in the same thread.
If you want to run things in multiple threads you would have to either use something like Cluster support or spawning off processes with process.spawn/fork
